import {randomBytes, randomUUID, createHash, timingSafeEqual} from 'node:crypto';
import {Pool} from 'pg';

const DAY=86400000;
const digest=value=>createHash('sha256').update(value).digest('hex');
const cookie=(req,name)=>String(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(name+'='))?.slice(name.length+1);
const sources=new Map();
export function registerGame(name,rooms){sources.set(name,rooms);}
export const accountsConfigured=()=>Boolean(process.env.DISCORD_CLIENT_ID&&process.env.DISCORD_CLIENT_SECRET&&process.env.DISCORD_REDIRECT_URI&&process.env.DATABASE_URL);
export function publicOrigin(){return new URL(process.env.DISCORD_REDIRECT_URI||'http://localhost:3000/auth/discord/callback').origin;}
function json(res,status,value){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value));}
function redirect(res,url){res.writeHead(302,{Location:url,'Cache-Control':'no-store','Referrer-Policy':'no-referrer'});res.end();}
function setCookie(res,name,value,maxAge){const secure=publicOrigin().startsWith('https:')?'; Secure':'';res.setHeader('Set-Cookie',`${name}=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${secure}`);}
async function body(req){let raw='';for await(const part of req){raw+=part;if(raw.length>12000)throw Error('Pedido muito grande.');}return JSON.parse(raw||'{}');}
const schema=`
CREATE TABLE IF NOT EXISTS elysium_users(discord_id TEXT PRIMARY KEY,username TEXT NOT NULL,display_name TEXT NOT NULL,avatar TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS elysium_sessions(token_hash TEXT PRIMARY KEY,discord_id TEXT NOT NULL REFERENCES elysium_users(discord_id),expires_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS elysium_sessions_expiry ON elysium_sessions(expires_at);
CREATE TABLE IF NOT EXISTS elysium_inventory(discord_id TEXT NOT NULL REFERENCES elysium_users(discord_id),insignia TEXT NOT NULL,PRIMARY KEY(discord_id,insignia));
CREATE TABLE IF NOT EXISTS elysium_inventory_audit(id TEXT PRIMARY KEY,admin_id TEXT NOT NULL,target_id TEXT NOT NULL,insignia TEXT NOT NULL,operation TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS elysium_matches(id TEXT PRIMARY KEY,game TEXT NOT NULL,room_code TEXT NOT NULL,winner_id TEXT,participants JSONB NOT NULL,wager JSONB NOT NULL,finished_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS elysium_results(match_id TEXT NOT NULL REFERENCES elysium_matches(id),discord_id TEXT NOT NULL REFERENCES elysium_users(discord_id),outcome TEXT NOT NULL CHECK(outcome IN ('win','loss','draw')),PRIMARY KEY(match_id,discord_id));
CREATE INDEX IF NOT EXISTS elysium_results_user ON elysium_results(discord_id);
`;
export class AccountStore{
  constructor(pool){this.pool=pool;this.ready=null;}
  async init(){if(!this.ready)this.ready=this.pool.query(schema).catch(error=>{this.ready=null;throw error;});await this.ready;}
  async query(sql,params=[]){await this.init();return this.pool.query(sql,params);}
  async upsert(user){await this.query('INSERT INTO elysium_users(discord_id,username,display_name,avatar) VALUES($1,$2,$3,$4) ON CONFLICT(discord_id) DO UPDATE SET username=EXCLUDED.username,display_name=EXCLUDED.display_name,avatar=EXCLUDED.avatar',[user.id,user.username,user.global_name||user.username,user.avatar||null]);}
  async session(value){const {rows}=await this.query('SELECT u.* FROM elysium_sessions s JOIN elysium_users u ON u.discord_id=s.discord_id WHERE token_hash=$1 AND expires_at>NOW()',[digest(value)]);return rows[0]||null;}
  async createSession(id){const value=randomBytes(32).toString('hex');await this.query('INSERT INTO elysium_sessions(token_hash,discord_id,expires_at) VALUES($1,$2,$3)',[digest(value),id,new Date(Date.now()+30*DAY)]);await this.query('DELETE FROM elysium_sessions WHERE expires_at<NOW()');return value;}
  async inventory(id){const {rows}=await this.query('SELECT insignia FROM elysium_inventory WHERE discord_id=$1 ORDER BY insignia',[id]);return rows.map(r=>r.insignia);}
  async changeInventory(admin,target,insignia,operation){await this.init();const c=await this.pool.connect();try{await c.query('BEGIN');const exists=await c.query('SELECT discord_id FROM elysium_users WHERE discord_id=$1',[target]);if(!exists.rows.length)throw Error('Esse jogador precisa entrar com Discord ao menos uma vez.');if(operation==='grant')await c.query('INSERT INTO elysium_inventory(discord_id,insignia) VALUES($1,$2) ON CONFLICT DO NOTHING',[target,insignia]);else await c.query('DELETE FROM elysium_inventory WHERE discord_id=$1 AND insignia=$2',[target,insignia]);await c.query('INSERT INTO elysium_inventory_audit(id,admin_id,target_id,insignia,operation) VALUES($1,$2,$3,$4,$5)',[randomUUID(),admin,target,insignia,operation]);await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
  async record(result){await this.init();const c=await this.pool.connect();try{await c.query('BEGIN');const inserted=await c.query('INSERT INTO elysium_matches(id,game,room_code,winner_id,participants,wager) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING RETURNING id',[result.id,result.game,result.room,result.winner,JSON.stringify(result.players),JSON.stringify(result.wager)]);if(inserted.rows.length)for(const p of result.players)await c.query('INSERT INTO elysium_results(match_id,discord_id,outcome) VALUES($1,$2,$3)',[result.id,p.discordId,result.winner===null?'draw':result.winner===p.discordId?'win':'loss']);await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
  async profile(id){const [inventory,matches]=await Promise.all([this.inventory(id),this.query('SELECT m.*,r.outcome FROM elysium_results r JOIN elysium_matches m ON m.id=r.match_id WHERE r.discord_id=$1 ORDER BY m.finished_at DESC LIMIT 50',[id])]);const {rows:stats}=await this.query("SELECT m.game,r.outcome,COUNT(*) AS count FROM elysium_results r JOIN elysium_matches m ON m.id=r.match_id WHERE r.discord_id=$1 GROUP BY m.game,r.outcome",[id]);const totals=await this.query('SELECT m.wager,r.outcome FROM elysium_results r JOIN elysium_matches m ON m.id=r.match_id WHERE r.discord_id=$1',[id]);return {inventory,matches:matches.rows,stats,wagers:summarizeWagers(totals.rows)};}
}
let store;
export function useTestStore(value){if(process.env.NODE_ENV!=='test')throw Error('Apenas para testes.');store=value;}
function database(){if(!store){const pool=new Pool({connectionString:process.env.DATABASE_URL,max:4,connectionTimeoutMillis:10000,idleTimeoutMillis:30000});pool.on('error',()=>console.error('Conexão do banco Elysium interrompida.'));store=new AccountStore(pool);}return store;}
const rates=new Map();
function throttle(req){const key=req.socket.remoteAddress||'local';const now=Date.now();let r=rates.get(key);if(!r||now-r.at>60000){r={at:now,count:0};rates.set(key,r);}if(++r.count>30)return false;if(rates.size>5000)for(const [key,r] of rates)if(now-r.at>60000)rates.delete(key);return true;}
const pendingStates=new Map();
const insignias=new Set();
export function registerInsignias(ids){for(const id of ids)insignias.add(id);}
export async function identify(req){if(req.accountChecked)return req.identity;req.accountChecked=true;req.identity=null;if(!accountsConfigured())return null;const value=cookie(req,'elysium_session');if(value&&/^[a-f0-9]{64}$/.test(value))req.identity=await database().session(value);return req.identity;}
export function assertUniqueAccount(room,p){if(p.discordId&&[...room.players,...room.spectators].some(q=>q!==p&&q.discordId===p.discordId))throw Error('Sua conta já está nesta sala.');}
export async function bindParticipant(req,room,p){const u=await identify(req);if(u){p.discordId=u.discord_id;p.name=u.display_name.slice(0,30);assertUniqueAccount(room,p);}else p.discordId=null;room.createdAt??=Date.now();room.updatedAt=Date.now();}
export async function verifyParticipant(req,p){if(p.discordId&&(await identify(req))?.discord_id!==p.discordId)throw Error('Entre novamente com a conta Discord vinculada a esta vaga.');}
export async function ownedInsignias(p){return !accountsConfigured()?null:p.discordId?database().inventory(p.discordId):[];}
export async function validateInsignias(req,room,p,data){if(!accountsConfigured()||!['propose','accept'].includes(data.type))return;const ids=await ownedInsignias(p);for(const id of [data.insignia,data.legendary].filter(Boolean))if(!ids.includes(id))throw Error('Essa insígnia não pertence ao seu inventário.');if(data.type==='accept'&&room.proposal){const proposer=room.players.find(q=>q.id===room.proposal.by);const owned=await ownedInsignias(proposer);for(const id of [room.proposal.insignia,room.proposal.legendary].filter(Boolean))if(!owned.includes(id))throw Error('Uma insígnia da proposta foi removida pelo administrador.');}}
// Integer Bronze avoids rounding differences between the four denominations.
export function normalizeWager(value){if(!value)return {bronze:0,items:[]};if(typeof value==='string'){const text=value.trim();if(!text)return {bronze:0,items:[]};const re=/(\d+)\s*(Br|Pr|Or|Pl|Bronze|Prata|Ouro|Platina)\b/gi;const matches=[...text.matchAll(re)];if(matches.length&&text.replace(re,'').replace(/[\s+,;·]/g,'')===''){let bronze=0;for(const m of matches){const unit=m[2].toLowerCase();bronze+=Number(m[1])*({br:1,bronze:1,pr:100,prata:100,or:10000,ouro:10000,pl:1000000,platina:1000000}[unit]);}if(!Number.isSafeInteger(bronze)||bronze>1e12)throw Error('Aposta acima do limite.');return {bronze,items:[]};}return {bronze:0,items:[{name:text.slice(0,80),quantity:1}]};}const bronze=Number(value.bronze||0);if(!Number.isSafeInteger(bronze)||bronze<0||bronze>1e12)throw Error('Valor de aposta inválido.');const items=(value.items||[]).slice(0,20).map(item=>{const quantity=Number(item.quantity);const name=String(item.name||'').trim().slice(0,80);if(!name||!Number.isSafeInteger(quantity)||quantity<1||quantity>100000)throw Error('Item de aposta inválido.');return {name,quantity};});return {bronze,items};}
export function summarizeWagers(rows){const result={bet:0,won:0,lost:0,items:{}};for(const {wager,outcome} of rows){result.bet+=Number(wager.bronze||0);if(outcome==='win')result.won+=Number(wager.bronze||0);if(outcome==='loss')result.lost+=Number(wager.bronze||0);for(const item of wager.items||[]){result.items[item.name]??={bet:0,won:0,lost:0};result.items[item.name].bet+=item.quantity;if(outcome==='win')result.items[item.name].won+=item.quantity;if(outcome==='loss')result.items[item.name].lost+=item.quantity;}}return result;}
export function beginMatch(room){room.matchId=randomUUID();room.matchPlayers=room.players.map(p=>({id:p.id,discordId:p.discordId||null,name:p.name,bot:Boolean(p.bot)}));room.matchWager=normalizeWager(room.stake);room.recording='not-finished';}
const retryResults=new Map();
let retryTimer;
export async function persistMatch(room,game){if(room.phase!=='finished'||!room.matchId||room.recording==='saved'||room.recording==='unranked')return;const players=room.matchPlayers||[];if(!accountsConfigured()||players.length!==2||players.some(p=>!p.discordId||p.bot)||players[0].discordId===players[1].discordId){room.recording='unranked';return;}const result={id:room.matchId,game,room:room.code,players,winner:room.winner?players.find(p=>p.id===room.winner)?.discordId:null,wager:room.matchWager||{bronze:0,items:[]}};if(result.winner===undefined)return;try{await database().record(result);room.recording='saved';retryResults.delete(result.id);}catch{room.recording='pending';retryResults.set(result.id,result);console.error('Histórico Elysium pendente: banco temporariamente indisponível.');if(!retryTimer){retryTimer=setInterval(async()=>{for(const [id,result] of retryResults)try{await database().record(result);retryResults.delete(id);}catch{}if(!retryResults.size){clearInterval(retryTimer);retryTimer=null;}},15000);retryTimer.unref();}}}
function roomsList(){return [...sources].flatMap(([game,rooms])=>[...rooms.values()].filter(room=>room.players.length||room.spectators?.length).map(room=>({game,code:room.code,phase:room.phase,round:room.round,recording:room.recording||null,updatedAt:room.updatedAt||room.createdAt||null,players:room.players.map(p=>({name:p.name,linked:Boolean(p.discordId),bot:Boolean(p.bot)})),spectators:room.spectators?.length||0})));}
function safeReturn(value){return typeof value==='string'&&value.startsWith('/')&&!value.startsWith('//')&&!/[\\\r\n]/.test(value)?value:'/';}
export async function handleAccounts(req,res,url){if(!url.pathname.startsWith('/auth/')&&!url.pathname.startsWith('/api/account')&&!url.pathname.startsWith('/api/admin'))return false;try{
  if(!accountsConfigured()){json(res,503,{error:'Login Discord ainda não configurado no servidor.'});return true;}
  if(!throttle(req)){json(res,429,{error:'Muitas solicitações. Aguarde um minuto.'});return true;}
  if(req.method==='POST'&&req.headers.origin!==publicOrigin()){json(res,403,{error:'Origem inválida.'});return true;}
  if(url.pathname==='/auth/discord'&&req.method==='GET'){
    await database().init();const state=randomBytes(32).toString('hex');for(const [key,item] of pendingStates)if(item.expires<Date.now())pendingStates.delete(key);pendingStates.set(digest(state),{returnTo:safeReturn(url.searchParams.get('return')),expires:Date.now()+10*60000});setCookie(res,'elysium_oauth',state,600);const target=new URL('https://discord.com/oauth2/authorize');target.search=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,response_type:'code',scope:'identify',redirect_uri:process.env.DISCORD_REDIRECT_URI,state}).toString();redirect(res,target.href);return true;
  }
  if(url.pathname==='/auth/discord/callback'&&req.method==='GET'){
    const state=url.searchParams.get('state')||'',saved=cookie(req,'elysium_oauth')||'';const flow=pendingStates.get(digest(state));if(!flow||flow.expires<Date.now()||state.length!==saved.length||!state||!timingSafeEqual(Buffer.from(state),Buffer.from(saved))){redirect(res,'/?login_error=expired');return true;}pendingStates.delete(digest(state));if(url.searchParams.has('error')||!url.searchParams.get('code')){redirect(res,'/?login_error=cancelled');return true;}
    const response=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:process.env.DISCORD_CLIENT_ID,client_secret:process.env.DISCORD_CLIENT_SECRET,redirect_uri:process.env.DISCORD_REDIRECT_URI,code:url.searchParams.get('code')}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Discord indisponível');const {access_token}=await response.json();const userResponse=await fetch('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${access_token}`},signal:AbortSignal.timeout(15000)});if(!userResponse.ok)throw Error('Discord indisponível');const u=await userResponse.json();if(!/^\d{15,22}$/.test(u.id)||!u.username)throw Error('Perfil inválido');const db=database();await db.upsert(u);const value=await db.createSession(u.id);setCookie(res,'elysium_session',value,30*86400);res.appendHeader('Set-Cookie','elysium_oauth=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0');redirect(res,flow.returnTo);return true;
  }
  const u=await identify(req);
  if(url.pathname==='/api/account'&&req.method==='GET'){json(res,200,{user:u?{id:u.discord_id,username:u.username,name:u.display_name,admin:u.discord_id===process.env.DISCORD_ADMIN_ID}:null,configured:true});return true;}
  if(!u){json(res,401,{error:'Entre com Discord para acessar seu perfil.'});return true;}
  if(url.pathname==='/auth/logout'&&req.method==='POST'){const value=cookie(req,'elysium_session');if(value)await database().query('DELETE FROM elysium_sessions WHERE token_hash=$1',[digest(value)]);setCookie(res,'elysium_session','',0);json(res,200,{ok:true});return true;}
  if(url.pathname==='/api/account/profile'&&req.method==='GET'){json(res,200,await database().profile(u.discord_id));return true;}
  if(url.pathname.startsWith('/api/admin')){
    if(u.discord_id!==process.env.DISCORD_ADMIN_ID){json(res,403,{error:'Apenas o administrador pode acessar este painel.'});return true;}
    if(url.pathname==='/api/admin/rooms'&&req.method==='GET'){json(res,200,{rooms:roomsList()});return true;}
    if(url.pathname==='/api/admin/players'&&req.method==='GET'){const term=(url.searchParams.get('search')||'').trim().slice(0,80);const {rows}=await database().query('SELECT discord_id AS id,username,display_name AS name FROM elysium_users WHERE discord_id=$1 OR LOWER(username)=LOWER($1) OR LOWER(display_name)=LOWER($1) ORDER BY display_name LIMIT 30',[term]);json(res,200,{players:rows});return true;}
    if(url.pathname==='/api/admin/inventory'&&req.method==='GET'){const id=url.searchParams.get('id');json(res,200,{inventory:await database().inventory(id),catalog:[...insignias].sort()});return true;}
    if(url.pathname==='/api/admin/inventory'&&req.method==='POST'){const data=await body(req);if(!['grant','revoke'].includes(data.operation)||!insignias.has(data.insignia)||!/^\d{15,22}$/.test(data.id))throw Error('Dados de insígnia inválidos.');await database().changeInventory(u.discord_id,data.id,data.insignia,data.operation);json(res,200,{inventory:await database().inventory(data.id)});return true;}
  }
  json(res,404,{error:'Não encontrado.'});return true;
}catch{if(url.pathname==='/auth/discord/callback')redirect(res,'/?login_error=unavailable');else json(res,503,{error:'Não foi possível acessar os dados agora. Tente novamente em instantes.'});return true;}}

// A cookie authenticated mutation must originate from this site, including game actions.
export function validMutationOrigin(req){return !['POST','PUT','PATCH','DELETE'].includes(req.method)||!cookie(req,'elysium_session')||req.headers.origin===publicOrigin();}
