function cloneVisual(source){const copy=source.cloneNode(true);const originals=source.querySelectorAll('canvas'),clones=copy.querySelectorAll('canvas');originals.forEach((canvas,i)=>clones[i]?.getContext('2d').drawImage(canvas,0,0));return copy;}
const $=id=>document.getElementById(id);
const gameBase=location.pathname.startsWith('/runamarca')?'/runamarca/':'/';
let state=null,models=null,selected=null,importedArt={},lastRevision=-1,toastTimer=null,hoverUid=null,serverClockOffset=0,pendingSnap=null,refreshing=false;
let visualGeneration=0,visualMatchKey=null,connectionLost=false;
let visualBooted=false,lastVisualId=0,lastPhase=null,lastBattleStep='',handOrder=[],mulliganSelected=new Set(),audioContext=null,pendingArrival=[],suppressClickUntil=0;let visualQueue=Promise.resolve();
const mulliganDepartures=new Map();
const emanationChoices=new Map(),spellTargets=new Map(),promptedEmanations=new Set();let emanationChoiceTurn='',autoMulliganKey='',noticeQueue=Promise.resolve();
const displayedHealth=new Map(),pendingHealth=new Map(),displayedPatronHealth=new Map();let healthDisplayCombat=null;
const displayedAttack=new Map(),pendingAttack=new Map();let attackDisplayCombat=null;

function syncHealthDisplay(){
 const combat=state?.combat?.id||null;if(healthDisplayCombat!==combat){displayedHealth.clear();pendingHealth.clear();displayedPatronHealth.clear();healthDisplayCombat=combat;}
 const unseen=(state?.events||[]).filter(e=>e.id>lastVisualId&&['spell','cleric_heal'].includes(e.type));for(const p of state?.players||[]){for(const card of p.reserve||[]){const value=Math.max(0,card.health-card.damage);if(!combat&&displayedHealth.has(card.uid)&&displayedHealth.get(card.uid)!==value&&unseen.some(e=>e.healthUpdates?.some(u=>u.uid===card.uid)))pendingHealth.set(card.uid,value);if(!displayedHealth.has(card.uid)||!combat&&!pendingHealth.has(card.uid))displayedHealth.set(card.uid,value);}if(!displayedPatronHealth.has(p.id)||!combat&&!unseen.some(e=>e.healthUpdates?.some(u=>u.patronId===p.id)))displayedPatronHealth.set(p.id,p.patron?.hp??0);}
}
function updateLiquidHeart(node,hp,maxHp,animate=false){
 let canvas=node.querySelector('.health-liquid');if(!canvas){canvas=document.createElement('canvas');canvas.width=900;canvas.height=node.classList.contains('combat-card')?820:1260;canvas.className='health-liquid';canvas.setAttribute('aria-hidden','true');node.append(canvas);}
 const target=Math.max(0,Math.min(1,hp/Math.max(1,maxHp))),from=canvas.fillRatio??target,start=performance.now();
 cancelAnimationFrame(canvas.liquidFrame);const paint=now=>{const progress=animate?Math.min(1,(now-start)/450):1;canvas.fillRatio=from+(target-from)*(1-Math.pow(1-progress,3));RunaCardVisual.drawLiquidHeart(canvas,canvas.fillRatio,node.classList.contains('combat-card'));if(progress<1&&canvas.isConnected)canvas.liquidFrame=requestAnimationFrame(paint);};paint(start);
}
function deferVisual(callback,delay){const generation=visualGeneration;return setTimeout(()=>{if(generation===visualGeneration)callback();},delay);}
function applyHealthUpdates(updates=[]){for(const update of updates){if(update.patronId){displayedPatronHealth.set(update.patronId,update.hp);const player=state.players.find(p=>p.id===update.patronId),head=$(update.patronId===seat()?.id?'self-head':'opponent-head');if(head?.querySelector('.hp'))head.querySelector('.hp').textContent=update.hp+'/'+(player?.patron.maxHp||update.maxHp)+' ♥';continue;}if(update.attack!==undefined){displayedAttack.set(update.uid,update.attack);for(const node of document.querySelectorAll('.card'))if(node.dataset.uid===update.uid){const number=node.querySelector('.attack-value');if(number){number.textContent=String(update.attack);number.classList.toggle('attack-buffed',update.attack>Number(node.dataset.baseAttack));}}}displayedHealth.set(update.uid,update.hp);pendingHealth.delete(update.uid);for(const node of document.querySelectorAll('.card'))if(node.dataset.uid===update.uid){const number=node.querySelector('.health-value');if(number){number.textContent=String(update.hp);number.classList.toggle('health-damaged',update.hp<update.maxHp);number.classList.remove('health-changed');void number.offsetWidth;number.classList.add('health-changed');}updateLiquidHeart(node,update.hp,update.maxHp,true);node.classList.toggle('wounded',update.hp<update.maxHp);}}
}
function damagePatron(owner,amount){const player=state.players.find(p=>p.id===owner);if(player)applyHealthUpdates([{patronId:owner,hp:Math.max(0,(displayedPatronHealth.get(owner)??player.patron.hp)-amount),maxHp:player.patron.maxHp}]);}

function syncAttackDisplay(){const combat=state?.combat?.id||null;if(attackDisplayCombat!==combat){displayedAttack.clear();pendingAttack.clear();attackDisplayCombat=combat;}for(const p of state?.players||[])for(const card of p.reserve||[]){const value=card.effectiveAttack??Math.max(0,card.attack+(card.attackMod||0)),previous=displayedAttack.get(card.uid);if(!combat&&previous!==undefined&&value>previous&&(state.events||[]).some(e=>e.id>lastVisualId&&['attack_modifier','stat_buff'].includes(e.op)&&e.targetId===card.uid))pendingAttack.set(card.uid,value);if(!displayedAttack.has(card.uid)||(!combat&&!pendingAttack.has(card.uid)))displayedAttack.set(card.uid,value);}}
let commandBusy=false,activeDrag=null;const movingCards=new Set(),deadVisuals=new Map();
const spellTargetRects=new Map();
function rememberSpellTargets(){for(const node of document.querySelectorAll('#game .card'))if(node.dataset.uid)spellTargetRects.set(node.dataset.uid,node.getBoundingClientRect());if(spellTargetRects.size>200)for(const uid of [...spellTargetRects.keys()].slice(0,100))spellTargetRects.delete(uid);}
function spellTarget(uid){return tableCard(uid)||(spellTargetRects.has(uid)?{getBoundingClientRect:()=>spellTargetRects.get(uid)}:null);}
function tableCard(uid){return [...document.querySelectorAll('#game .card,#game .spell-mark,#mulligan-cards .card')].find(node=>node.dataset.uid===uid&&!node.closest('#visual-layer'));}
function cleanupDrag(){activeDrag?.();activeDrag=null;document.querySelectorAll('.drag-preview').forEach(node=>node.remove());document.querySelectorAll('.dragging-source,.drop-ready').forEach(node=>node.classList.remove('dragging-source','drop-ready'));}
window.addEventListener('blur',cleanupDrag);document.addEventListener('visibilitychange',()=>{if(document.hidden)cleanupDrag();});
const isInvitation=()=>new URLSearchParams(location.search).has('invite');
const laneSymbols=['☀','☽','✦'];
const avatar=(seat)=>seat?.patron?.affinity==='ruptura'?'◆':seat?.patron?.affinity==='fluxo'?'◇':'✦';
const seat=()=>state?.players.find(p=>p.id===state.you)||(state?.spectator?state?.players[0]:null);
const rival=()=>state?.players.find(p=>p.id!==seat()?.id);
const err=error=>{const message=error?.message||String(error);$('welcome-error').textContent=message;const t=$('toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3500);};
async function api(route,data,method='POST'){
 const controller=method==='GET'?new AbortController():null,timer=controller?setTimeout(()=>controller.abort(),10000):null;
 try{
  const headers={'Content-Type':'application/json'};const saved=sessionStorage.getItem('runamarca-nova-seat');if(saved)headers['x-player-token']=JSON.parse(saved).token;
  const response=await fetch(gameBase+route.replace(/^\//,''),{method,headers,...(controller?{signal:controller.signal}:{}),...(data?{body:JSON.stringify(data)}:{})});if(response.status===204)return null;if(response.status===403){location.assign(gameBase+'access');throw Object.assign(Error('Acesso necessário.'),{code:'ACCESS_REQUIRED'});}const result=await response.json();if(!response.ok)throw Object.assign(Error(result.error||'Ação não concluída.'),{code:result.code,status:response.status});return result;
 }finally{clearTimeout(timer);}
}
function trackArrivals(previous,next){
 const hand=next.players.find(p=>p.id===next.you)?.hand||[],present=new Set(hand.map(c=>c.uid));pendingArrival=pendingArrival.filter(uid=>present.has(uid));
 if(!previous||previous.you!==next.you||next.spectator||previous.matchId!==next.matchId)return;
 const draws=new Set((next.events||[]).filter(e=>e.type==='draw'&&e.playerId===next.you&&e.id>(previous.eventId??previous.events?.at(-1)?.id??0)).map(e=>e.cardId));
 for(const card of hand)if(draws.has(card.uid)&&!pendingArrival.includes(card.uid))pendingArrival.push(card.uid);
}
function prepareOpeningArrivals(){
 if(!visualBooted||!state||state.spectator)return;
 const opening=(state.events||[]).find(e=>e.type==='opening'&&e.playerId===state.you&&e.id>lastVisualId);if(!opening)return;
 const hand=seat()?.hand||[],ids=new Set(opening.cardIds||hand.slice(0,opening.count||5).map(c=>c.uid));
 for(const c of hand)if(ids.has(c.uid)&&!pendingArrival.includes(c.uid))pendingArrival.push(c.uid);
}
async function command(data,dragRect=null){if(commandBusy)return;commandBusy=true;try{
 const movingId=data.cardId||(data.type==='assign'?seat()?.formation[data.lane]:null),source=tableCard(movingId),movedCard=[...(seat()?.hand||[]),...(seat()?.reserve||[]),...(state?.players.flatMap(p=>p.prepared?.map(item=>item.card).filter(Boolean)||[])||[])].find(c=>c.uid===movingId);
 const transfer=source&&['play','assign','emanate','unprepare','movePrepared'].includes(data.type)?{uid:movingId,copy:data.type==='unprepare'&&movedCard?cardEl(movedCard):cloneVisual(source),rect:dragRect||source.getBoundingClientRect(),card:movedCard}:null;const opening=data.type==='confirmMulligan'?[...$('mulligan-cards').querySelectorAll('.card')].map(node=>({uid:node.dataset.uid,copy:cloneVisual(node),rect:node.getBoundingClientRect()})):null;const returning=data.type==='mulligan'?data.cardIds.map(uid=>{const node=tableCard(uid);return node?{uid,copy:cloneVisual(node),rect:node.getBoundingClientRect()}:null;}).filter(Boolean):null;if(data.type==='emanate')promptedEmanations.delete(data.cardId);const next=await api(`/api/rooms/${state.code}/act`,data);if(next.left){sessionStorage.removeItem('runamarca-nova-seat');state=null;selected=null;visualBooted=false;lastRevision=-1;history.replaceState(null,'',gameBase);render();return;}if(returning?.length){const event=next.events?.find(e=>e.type==='mulligan'&&e.playerId===state.you&&e.id>(state.eventId||0));if(event)mulliganDepartures.set(event.id,returning);}trackArrivals(state,next);serverClockOffset=Date.now()-next.serverNow;state=next;if(opening?.length)for(const item of opening)movingCards.add(item.uid);if(transfer)movingCards.add(transfer.uid);render();if(opening?.length)await animateOpeningToHand(opening);if(transfer)await animateTransfer(transfer);}catch(e){err(e);}finally{commandBusy=false;if(data.type==='assign'&&data.cardId){const card=seat()?.reserve.find(c=>c.uid===data.cardId);if(card?.effects?.some(e=>e.op==='taunt')&&!Number.isInteger(seat().taunts?.[card.uid]))showTauntPicker(card);}}}
async function refresh(){const saved=sessionStorage.getItem('runamarca-nova-seat');if(!saved||refreshing||commandBusy||activeDrag)return;refreshing=true;try{const info=JSON.parse(saved);const next=await api(`/api/rooms/${info.code}/state?revision=${lastRevision}`,null,'GET');if(!next){connectionLost=false;return;}connectionLost=false;serverClockOffset=Date.now()-next.serverNow;if(next.revision>lastRevision||!state){trackArrivals(state,next);state=next;render();}}catch(e){if(['SEAT_INVALID','ROOM_NOT_FOUND'].includes(e.code)){sessionStorage.removeItem('runamarca-nova-seat');state=null;render();err(e);}else if(e.code!=='ACCESS_REQUIRED'&&!connectionLost){connectionLost=true;err(e.code==='ACCOUNT_REQUIRED'?e:Error('Conexão interrompida. Tentando reconectar sem perder sua vaga.'));}}finally{refreshing=false;}}
function button(label,handler,klass='',disabled=false){const b=document.createElement('button');b.type='button';b.textContent=label;b.className=klass;b.disabled=disabled;b.onclick=handler;return b;}
function text(parent,tag,value,klass){const el=document.createElement(tag);el.textContent=value;if(klass)el.className=klass;parent.append(el);return el;}
function manaAffinity(value){return ['ruptura','forja','fluxo'].includes(value)?value:'fluxo';}
function affordable(card){const p=seat();if(!p||state.spectator||state.phase!=='prep'||state.turn!==p.id||!p.hand?.some(c=>c.uid===card?.uid))return false;const sources=p.emanation.filter(uid=>p.reserve.find(c=>c.uid===uid)?.modelId==='M04').length;const cost=card.type!=='creature'&&sources&&!p.discountUsed&&!p.directPlayed?Math.max(1,card.cost-sources):card.cost;return p.mana>=cost;}
const cardFaceCache=new Map();
function paintCardFace(canvas,design,combat,flat){
 const key=JSON.stringify([design,combat,flat,canvas.width,canvas.height]);let entry=cardFaceCache.get(key);
 if(!entry){
  const frame=document.createElement('canvas');frame.width=canvas.width;frame.height=canvas.height;entry={frame,ready:false};cardFaceCache.set(key,entry);
  const render=combat?RunaCardVisual.drawCombat:RunaCardVisual.drawCard;
  entry.promise=(!combat&&flat?new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{frame.getContext('2d').drawImage(image,0,0,frame.width,frame.height);resolve();};image.onerror=reject;image.src=design.art;}):render(frame,design,{assets:'criador/',hideStats:true,flat})).then(()=>{entry.ready=true;}).catch(error=>{cardFaceCache.delete(key);console.error(error);});
  if(cardFaceCache.size>32)cardFaceCache.delete(cardFaceCache.keys().next().value);
 }
 const paint=()=>canvas.getContext('2d').drawImage(entry.frame,0,0);
 if(entry.ready){paint();return Promise.resolve();}return entry.promise.then(paint);
}
function cardEl(card,{mini=false,back=false,active=false,combat=false}={}){
  const el=document.createElement('button');el.type='button';el.className=`card${mini?' mini':''}${back?' back':''}${active?' selected':''}${card?.imageKind==='card'?' has-art':''}`;el.dataset.uid=card?.uid||'';if(!back&&affordable(card))el.classList.add('payable');if(movingCards.has(card?.uid))el.style.visibility='hidden';if(card?.type==='creature'&&card.damage>0)el.classList.add('wounded');el.setAttribute('aria-label',back?'Magia oculta':`${card.name} · custo ${card.cost} · ${card.text||''}`);
  if(!back){el.classList.add('styled-card','energy-'+manaAffinity(card.affinity));if(combat)el.classList.add('combat-card');if(card.image){const image=document.createElement('img');image.src=card.image;image.alt='';el.append(image);}else text(el,'div',card.type==='creature'?'✦':'◈','fallback');text(el,'div',card.name,'card-title');text(el,'span',String(card.cost??0),`mana-gem mana-${manaAffinity(card.affinity)}`);if(card.type==='creature'){const ns='http://www.w3.org/2000/svg',stats=document.createElementNS(ns,'svg');stats.classList.add('card-stats-svg');stats.setAttribute('viewBox',combat?'0 0 900 820':'0 0 900 1260');stats.setAttribute('aria-hidden','true');el.append(stats);const attack=displayedAttack.get(card.uid)??card.effectiveAttack??Math.max(0,card.attack+(card.attackMod||0)),health=displayedHealth.get(card.uid)??Math.max(0,card.health-card.damage);const baseAttack=card.baseStats?.attack??card.attack;el.dataset.baseAttack=baseAttack;for(const [value,x,y,klass] of [[attack,83.3,combat?739:1172,'attack-value'+(attack>baseAttack?' attack-buffed':'')],[health,826,combat?744.12:1177.12,'health-value'+(health<card.health?' health-damaged':'')]]){const number=document.createElementNS(ns,'text');number.setAttribute('x',x);number.setAttribute('y',y);number.setAttribute('text-anchor','middle');number.setAttribute('dominant-baseline','central');number.setAttribute('class',klass);number.textContent=String(value);stats.append(number);}}if(card.sleep){el.classList.add('sleeping-card');text(el,'span','Zzz','sleep-badge');el.title='Adormecida: não ataca nem pode sair desta posição.';}if(card.rarity)text(el,'span',card.rarity,'rarity');}
  if(!back){const canvas=document.createElement('canvas');canvas.width=900;canvas.height=combat?820:1260;canvas.className='card-art-canvas';el.prepend(canvas);const design={name:card.name,rarity:card.rarity,kind:card.type==='creature'?'creature':'spell',rules:card.text,subtype:card.subtype||'',themeEnergy:manaAffinity(card.affinity),art:card.image,artZoom:card.artZoom||100,artX:card.artX??50,artY:card.artY??0,fontName:card.fontName,fontSubtype:card.fontSubtype,fontRules:card.fontRules,generic:card.cost,power:card.attack,health:card.health};el.visualReady=paintCardFace(canvas,design,combat,card.imageKind==='card');if(card.type==='creature')updateLiquidHeart(el,displayedHealth.get(card.uid)??Math.max(0,card.health-card.damage),card.health);}
  el.onclick=()=>{if(state?.phase==='formation'&&seat()?.formation.includes(card.uid)&&card.effects?.some(e=>e.op==='taunt')&&!seat().ready){showTauntPicker(card);return;}if(back||Date.now()<suppressClickUntil)return;if(state?.phase==='mulligan'&&seat()?.hand?.some(c=>c.uid===card.uid)){mulliganSelected.has(card.uid)?mulliganSelected.delete(card.uid):mulliganSelected.add(card.uid);render();return;}if(state?.phase==='prep'&&state.turn===state.you&&seat()?.emanation.includes(card.uid)){showEmanationMenu(card);return;}if(state?.phase==='prep'&&state.turn===state.you&&!state.spectator){if(seat()?.hand?.some(c=>c.uid===card.uid)&&card.type!=='creature'){chooseSpellTarget(card);return;}if(seat()?.reserve?.some(c=>c.uid===card.uid)&&JSON.stringify(card.effects||[]).includes('emanat')){showEmanationMenu(card);return;}}};el.ondblclick=null;
  if(!back){el.onmouseenter=event=>showHover(card,event);el.onmousemove=moveHover;el.onmouseleave=hideHover;el.onfocus=()=>{const r=el.getBoundingClientRect();showHover(card,{clientX:r.right,clientY:r.top+r.height/2});};el.onblur=hideHover;}
  return el;
}
let narrativeTimer=null;
const keywordGlossary=[
 [/adorme[çc]|adormec/i,'Adormecer','A criatura fica presa na posição e não ataca durante o combate de ativação e o seguinte. Continua recebendo dano.'],
 [/âncor|ancor/i,'Ancoragem','A criatura permanece na mesma posição até participar de mais um combate.'],
 [/barreira/i,'Barreira','A posição protege seu ocupante com 2 de vida temporária durante dois combates.'],
 [/transpassar/i,'Transpassar','O dano de combate que excede a vida do defensor atinge o Patrono.'],
 [/provocar/i,'Provocar','Escolha uma posição adjacente: seu atacante enfrenta esta criatura.'],
 [/iniciativa/i,'Iniciativa','Ataca antes de criaturas sem Iniciativa. Um rival morto não revida.'],
 [/revela[çc][ãa]o/i,'Revelação','Resolve após as magias de posição e antes dos ataques.'],
 [/emana[çc][ãa]o/i,'Emanação','Efeito da criatura em uma vaga de Emanação. Ataques normais e magias em área não a atingem.'],
 [/\bentrada\b|ao entrar/i,'Entrada','Efeito que acontece quando a criatura entra em campo.'],
 [/convoc|invoc|ficha/i,'Convocar','Cria uma criatura adicional na reserva.'],
 [/neste combate/i,'Neste combate','O bônus termina quando este combate acaba.'],
 [/dano em [áa]rea/i,'Dano em área','Atinge várias criaturas, exceto as que estão em Emanação.'],
 [/armadilha|magia preparada/i,'Magia preparada','Ativa quando uma criatura é revelada na posição escolhida.']
];
function showHover(card,event){
 const holder=$('hover-preview');if(holder.parentElement!==document.body)document.body.append(holder);if(hoverUid!==card.uid){
  clearTimeout(narrativeTimer);hoverUid=card.uid;holder.replaceChildren();
  const picture=cardEl(card);picture.classList.add('big');picture.onclick=picture.ondblclick=picture.onmouseenter=picture.onmousemove=picture.onmouseleave=picture.onfocus=picture.onblur=null;
  const terms=keywordGlossary.filter(([pattern])=>pattern.test(card.text||'')),narrative=String(card.narrative||'').trim();
  if(narrative){const side=document.createElement('aside');side.className='hover-context narrative-context';const dream=document.createElement('div');dream.className='hover-dream';dream.textContent=narrative;side.append(dream);holder.append(side);narrativeTimer=setTimeout(()=>{if(hoverUid===card.uid&&!holder.hidden)dream.classList.add('revealed');},900);}
  holder.append(picture);
  if(terms.length){const side=document.createElement('aside');side.className='hover-context mechanics-context';const keys=document.createElement('div');keys.className='hover-keywords';for(const [,name,definition] of terms){const item=document.createElement('div');text(item,'strong',name);text(item,'p',definition);keys.append(item);}side.append(keys);holder.append(side);}
 }holder.hidden=false;moveHover(event);
}
function moveHover(event){const holder=$('hover-preview');if(holder.hidden)return;const w=holder.offsetWidth||245,h=holder.offsetHeight||380;holder.style.left=`${Math.max(10,Math.min(innerWidth-w-10,event.clientX+(event.clientX>innerWidth*.68?-w-26:22)))}px`;holder.style.top=`${Math.max(70,Math.min(innerHeight-h-10,event.clientY-h*.38))}px`;}
function hideHover(){clearTimeout(narrativeTimer);narrativeTimer=null;const holder=$('hover-preview');holder.hidden=true;hoverUid=null;}
function showCard(card){hideHover();const d=$('card-detail');const area=$('detail-content');area.replaceChildren();const picture=cardEl(card);picture.classList.add('big');picture.onclick=picture.ondblclick=picture.onmouseenter=picture.onmousemove=picture.onmouseleave=null;area.append(picture);const body=document.createElement('div');text(body,'h2',card.name);text(body,'p',card.type==='creature'?`Criatura · ${card.attack}/${card.health} · custo ${card.cost}`:`Magia · custo ${card.cost}`);text(body,'p',card.text||'Sem texto.');area.append(body);d.showModal();}
function selectedCard(){if(!state)return null;return [...(seat()?.hand||[]),...(seat()?.reserve||[]),...(rival()?.reserve||[]),...state.players.flatMap(p=>p.prepared.filter(item=>item.caster===state.you&&item.card).map(item=>item.card))].find(c=>c.uid===selected);}
function role(card){const ef=Array.isArray(card.effects)?card.effects[0]:card.effects;if(['draw','area_stat_buff'].includes(ef?.op))return 'self';if(['area_damage','area_attack_modifier'].includes(ef?.op))return 'enemy-board';if(ef?.op==='choose_one')return 'friendly-or-patron';if(['heal','attack_modifier','stat_buff','barrier'].includes(ef?.op)&&ef?.target==='chosen_allied_creature')return 'friendly';return 'enemy';}
function matchSeat(player,position){if(!player)return;const self=position==='self';const node=$(`${position}-head`);node.replaceChildren();const portrait=document.createElement('div');portrait.className='patron-card';portrait.dataset.owner=player.id;if(player.patron?.image){const image=document.createElement('img');image.src=player.patron.image;image.alt=`Retrato de ${player.patron.name}`;portrait.append(image);}else text(portrait,'span',avatar(player));portrait.title=player.patron?.name||'Patrono';portrait.onclick=()=>{if(player.patron)showPatron(player.patron);};node.append(portrait);const info=document.createElement('div');info.className='patron-info';text(info,'small',state.spectator?'PATRONO':self?'SEU PATRONO':'PATRONO RIVAL');text(info,'strong',player.patron?.name||'Patrono');text(info,'span',player.name,'muted');text(info,'span',`${player.deckCount} no deck · ${player.handCount} na mão`,'muted');node.append(info);const stats=document.createElement('div');stats.className='patron-stats';if(player.patron){const affinity=manaAffinity(player.patron.affinity);const mana=text(stats,'span','',`resource mana-resource mana-${affinity}`);const icon=document.createElement('img');icon.src=`energy-icons/${affinity}.png`;icon.alt='';mana.append(icon);text(mana,'span',`${player.mana}/${player.manaMax} ${affinity}`);text(stats,'span',`${displayedPatronHealth.get(player.id)??player.patron.hp}/${player.patron.maxHp} ♥`,'hp');}node.append(stats);const deck=document.createElement('div');deck.id=position+'-deck';deck.className='deck-stack';deck.title='Baralho';const back=document.createElement('img');back.src='card-back.png';back.alt='Baralho de compra';deck.append(back);node.append(deck);}
function showPatron(patron){const d=$('card-detail'),area=$('detail-content');area.replaceChildren();const card=document.createElement('div');card.className='patron-large';if(patron.image){const image=document.createElement('img');image.src=patron.image;image.alt='';card.append(image);}text(card,'strong',patron.name);area.append(card);const body=document.createElement('div');text(body,'h2',patron.name);text(body,'p',`${patron.affinity.toUpperCase()} · ${patron.hp}/${patron.maxHp} de vida`);text(body,'p','Patrono do baralho. Começa em jogo e fica fora do limite de 30 cartas.');area.append(body);d.showModal();}
function renderGate(){
  $('welcome').hidden=Boolean(state);$('lobby').hidden=!state||state.phase!=='lobby';$('mulligan-overlay').hidden=!state||state.phase!=='mulligan'||Boolean(seat()?.mulliganReady);$('game').hidden=!state;$('game').classList.toggle('is-obscured',Boolean(state&&(state.phase==='lobby'||state.phase==='mulligan'&&!seat()?.mulliganReady)));
  $('room-name').textContent=state?`SALA ${state.code}`:'';$('spectators-game').hidden=!state;$('rules-toggle').hidden=!state;$('copy-link').hidden=!state;$('leave-room').hidden=!state;$('change-role').hidden=!state;$('change-role').textContent=state?.spectator?'Ocupar vaga':'Ir à arquibancada';$('change-role').disabled=Boolean(state?.spectator&&(state.phase!=='lobby'||state.players.length>=2));
  $('phase-label').textContent=state?`${({lobby:'SALA',coin:'MOEDA',mulligan:'MÃO INICIAL',prep:'PREPARAÇÃO',vote:'DECISÃO',formation:'FORMAÇÃO',resolving:'COMBATE',finished:'FIM'})[state.phase]||state.phase.toUpperCase()} · RODADA ${state.round}`:'';
  if(!state){$('entry-title').textContent=isInvitation()?'Entre na sala convidada':'Abra a mesa';$('entry-note').textContent=isInvitation()?'Informe seu nome. Se as duas vagas estiverem ocupadas, você entra na arquibancada.':'Jogue em duas abas ou convide outra pessoa para entrar na sala.';$('create').hidden=isInvitation();$('join').textContent=isInvitation()?'Entrar na sala':'Entrar com código';$('join-code-label').hidden=isInvitation();$('role-label').hidden=isInvitation();}
  if(!state)return;
  const crowd=`Arquibancada · ${state.spectators?.length||0}: ${state.spectators?.map(p=>p.name+(p.id===state.you?' (você)':'')).join(', ')||'ninguém'}`;$('spectators').textContent=crowd;$('spectators-game').textContent=crowd;
  if(state.phase==='lobby'){
    $('lobby-players').textContent=state.players.map(p=>`${p.name}${p.bot?' · bot fácil':''}${p.deckId?' ✓':''}`).join('  ·  ');
    $('lobby-note').textContent=state.spectator?'Você está assistindo. Ocupe uma vaga para escolher um deck.':state.players.length<2?'Escolha seu deck ou convide outra pessoa. Você também pode treinar contra o bot fácil.':state.players.every(p=>p.deckId)?'Os decks estão prontos.':'Cada jogador escolhe um deck.';
    const holder=$('deck-options');holder.replaceChildren();if(!state.spectator)for(const deck of models?.decks||[]){const box=document.createElement('article');box.className=`deck-option ${deck.affinity}`;const art=document.createElement('div');art.className='deck-art';const image=document.createElement('img');image.src=deck.cards.find(c=>c.type==='creature'&&c.image)?.image||'card-back.png';image.alt='';art.append(image);text(art,'span',deck.archetype,'deck-archetype');box.append(art);const content=document.createElement('div');content.className='deck-content';text(content,'span',deck.affinity.toUpperCase(),'affinity');text(content,'h2',deck.name);text(content,'p',deck.plan);text(content,'small',`PATRONO · ${deck.patron.name} · ${deck.cards.reduce((sum,card)=>sum+card.quantity,0)} CARTAS`);content.append(button(seat()?.deckId===deck.id?'Deck escolhido':'Escolher este deck',()=>command({type:'deck',deckId:deck.id,art:importedArt[deck.id]||{}}),'primary',Boolean(seat()?.deckId)));box.append(content);holder.append(box);}
    const botSetup=$('bot-setup');botSetup.hidden=state.spectator||state.players.length!==1;const select=$('bot-deck');if(!select.options.length)for(const deck of models?.decks||[]){const option=document.createElement('option');option.value=deck.id;option.textContent=`Bot: ${deck.name}`;select.append(option);}
  }
}
function renderMulliganOverlay(){if(state.phase!=='mulligan')return;const self=seat();const status=$('mulligan-status'),cards=$('mulligan-cards'),controls=$('mulligan-controls');cards.replaceChildren();controls.replaceChildren();if(state.spectator){status.textContent='Os jogadores estão escolhendo suas mãos iniciais.';return;}status.textContent=self.mulliganReady?'Mão confirmada. Aguardando o adversário.':`${state.first===self.id?'Você joga primeiro':'Você joga em segundo'} · ${self.mulligansLeft} troca(s) restante(s). Selecione individualmente as cartas que deseja devolver ao deck.`;if(self.mulliganReady)return;for(const card of self.hand||[]){const node=cardEl(card,{active:mulliganSelected.has(card.uid)});node.classList.add('opening-card');if(pendingArrival.includes(card.uid))node.classList.add('pending-arrival');cards.append(node);}if(!self.mulligansLeft){text(controls,'p','Trocas concluídas. Confirmando sua mão automaticamente…');return;}controls.append(button(`Trocar ${mulliganSelected.size} carta(s)`,()=>{const cardIds=[...mulliganSelected];mulliganSelected.clear();command({type:'mulligan',cardIds});},'primary',!self.mulligansLeft||!mulliganSelected.size));controls.append(button('Manter e confirmar mão',()=>{mulliganSelected.clear();command({type:'confirmMulligan'});}));}
function renderBoard(){const self=seat()||{id:'',name:'Aguardando jogador',hand:[],reserve:[],discard:[],formation:[null,null,null],emanation:[],handCount:0,discardCount:0,deckCount:0,mana:0,manaMax:0},opp=rival();matchSeat(self,'self');matchSeat(opp,'opponent');
  for(const [id,p] of [['self',self],['opponent',opp]]){
    const holder=$(`${id}-reserve`);holder.replaceChildren();const cards=(p?.reserve||[]).filter(c=>!p.emanation?.includes(c.uid)&&!p.formation?.includes(c.uid));$(`${id}-reserve-count`).textContent='';
    for(const c of cards){const node=cardEl(c,{mini:true,active:selected===c.uid});if(!state.spectator&&p.id===self.id)makeDraggable(node,c);holder.append(node);}
    const eman=$(`${id}-emana`);eman.replaceChildren();for(let slot=0;slot<2;slot++){const em=p?.reserve?.find(c=>c.uid===p.emanation?.[slot]);if(em)eman.append(cardEl(em,{mini:true,active:selected===em.uid}));else text(eman,'span',String(slot+1),'emana-empty');}
    const grave=$(`${id}-grave`);grave.replaceChildren();const top=p?.discard?.at(-1);if(top&&top.image){const art=document.createElement('img');art.src=top.image;art.alt='';grave.append(art);}else text(grave,'span','✝');text(grave,'b',`${p?.discardCount||0} carta(s)`);grave.onclick=()=>showCemetery(p);
  }
  const reserveDrop=$('self-reserve-area');reserveDrop.ondragover=event=>{if(state.phase==='formation'&&!self.ready){event.preventDefault();reserveDrop.classList.add('drop-ready');}};
  reserveDrop.ondragleave=event=>{if(!reserveDrop.contains(event.relatedTarget))reserveDrop.classList.remove('drop-ready');};
  reserveDrop.ondrop=event=>{reserveDrop.classList.remove('drop-ready');const uid=event.dataTransfer.getData('text/plain');const lane=self.formation.indexOf(uid);if(state.phase==='formation'&&!self.ready&&lane!==-1){event.preventDefault();command({type:'assign',lane,cardId:null});}};
  renderHand(self);
  const lanes=$('lanes');lanes.replaceChildren();for(let i=0;i<3;i++){
    const lane=document.createElement('div');lane.className='lane';lane.dataset.lane=i;lane.dataset.symbol=laneSymbols[i];lane.setAttribute('aria-label',`Posição ${laneSymbols[i]}`);
    for(const player of [opp,self]){
      const side=document.createElement('div');side.className='lane-side';side.dataset.owner=player?.id||'';side.dataset.lane=i;
      const placed=player?.reserve?.find(c=>c.uid===player.formation?.[i]);
      const aura=(player?.emanation||[]).some(uid=>{const c=player.reserve.find(c=>c.uid===uid);return i===0&&c?.modelId==='R05'||c?.effects?.some(e=>['lane_attack_aura','lane_health_aura'].includes(e.op)&&e.lane===i);});
      const buff=(player?.prepared||[]).some(item=>item.lane===i&&item.caster===player.id&&item.card?.effects?.some(e=>['attack_modifier','stat_buff','barrier'].includes(e.op)&&((e.amount||e.attack||e.health)>0)));if(aura||buff||state.laneBonuses?.[player?.id]?.[i])side.classList.add('lane-buffed');
      if(placed?.sleep){side.classList.add('sleeping-space');text(side,'span','☾','sleep-space-mark');}if(placed?.anchor){side.classList.add('anchored-space');text(side,'span','⚓','anchor-mark');}if(placed){const node=cardEl(placed,{mini:true,combat:true,active:selected===placed.uid});if(!state.spectator&&player.id===self.id)makeDraggable(node,placed);if(player.id===self.id&&pendingSnap?.lane===i&&pendingSnap.until>Date.now())node.classList.add('snapping');side.append(node);}else{const secret=state.phase==='formation'&&player?.id!==state.you;text(side,'span',secret?'?':state.phase==='formation'&&player?.id===state.you?'Solte aqui':'Vazia',secret?'drop-label secret-alert':'drop-label');}
      for(const prep of player?.prepared?.filter(item=>item.lane===i)||[]){const symbol=document.createElement('span');symbol.className=`spell-mark ${prep.caster===player.id?'ally-spell':'trap-spell'}${prep.hidden?' hidden-spell':''}`;symbol.textContent=prep.hidden?'':'✧';symbol.title=prep.hidden?'Magia inimiga oculta':prep.card?.name||'Magia';if(prep.card){symbol.dataset.uid=prep.card.uid;if(movingCards.has(prep.card.uid))symbol.style.visibility='hidden';}
 symbol.onclick=()=>{if(prep.hidden||!prep.card||Date.now()<suppressClickUntil)return;if(prep.caster===state.you){selected=prep.card.uid;render();}else showCard(prep.card);};
 if(prep.caster===state.you&&((state.phase==='prep'&&state.turn===state.you)||(state.phase==='formation'&&!self.ready)))bindCardDrag(symbol,prep.card,'prepared');side.append(symbol);}
      if(!state.spectator&&player?.id){
        if(player.id===self.id)side.classList.add('own-drop');
        side.classList.add('spell-drop');
        side.ondragover=event=>{
          const uid=event.dataTransfer.getData('text/plain');
          const spell=self.hand?.find(card=>card.uid===uid&&card.type!=='creature');
          if((state.phase==='formation'&&player.id===self.id&&!self.ready)||(state.phase==='prep'&&state.turn===self.id&&spell)){event.preventDefault();side.classList.add('drop-ready');}
        };
        side.ondragleave=event=>{if(!side.contains(event.relatedTarget))side.classList.remove('drop-ready');};
        side.ondrop=event=>{
          event.preventDefault();side.classList.remove('drop-ready');const uid=event.dataTransfer.getData('text/plain');
          const spell=self.hand?.find(card=>card.uid===uid&&card.type!=='creature');
          if(spell&&!spell.directOnly&&canPrepareOn(spell,player.id)&&state.phase==='prep')command({type:'play',cardId:uid,mode:'lane',lane:i,targetSide:player.id});
          else if(uid&&state.phase==='formation'&&player.id===self.id&&self.reserve.some(card=>card.uid===uid)){pendingSnap={lane:i,until:Date.now()+900};command({type:'assign',lane:i,cardId:uid});}
        };
      }
      for(const caster of state.players){for(const [uid,targetLane] of Object.entries(caster.taunts||{})){const sourceLane=caster.formation.indexOf(uid);if(sourceLane<0)continue;if(caster.id!==player?.id&&Number(targetLane)===i){side.classList.add('taunted-space');text(side,'span','⚑','taunt-space-mark').title='Provocada por '+caster.reserve.find(c=>c.uid===uid)?.name;}if(caster.id===player?.id&&placed?.uid===uid){text(side,'span','⚑ '+laneSymbols[targetLane],'taunt-source-mark').title='Provoca a posição '+laneSymbols[targetLane];}}}
      lane.append(side);
    }
    lanes.append(lane);
  }
  const log=$('log');log.replaceChildren();let group=null;for(const item of state.log.slice(-10)){const entry=typeof item==='string'?{message:item,round:state.round,turn:null,phase:'lobby'}:item;const key=`${entry.round}:${entry.phase==='prep'?entry.turn:entry.phase}`;if(key!==group){const name=state.players.find(player=>player.id===entry.turn)?.name;const phase={vote:'Decisão',formation:'Formação',resolving:'Combate',finished:'Resultado',lobby:'Sala',coin:'Moeda',mulligan:'Mão inicial'}[entry.phase]||entry.phase;const title=entry.phase==='prep'&&name?`Rodada ${entry.round} · turno de ${name}`:`Rodada ${entry.round} · ${phase}`;text(log,'h4',title,'log-divider');group=key;}text(log,'p',entry.message,entry.actor===state.you?'log-own':entry.actor&&state.players.some(p=>p.id===entry.actor)?'log-rival':'log-neutral');}
}
function layoutHand(){const cards=[...$('hand').querySelectorAll('.hand-card')];cards.forEach((node,index)=>{node.style.setProperty('--fan-angle',`${(index-(cards.length-1)/2)*4.3}deg`);node.style.setProperty('--fan-rise',`${Math.abs(index-(cards.length-1)/2)*5}px`);node.style.zIndex=index+1;});}
function renderHand(self){const hand=$('hand');hand.replaceChildren();const current=state.phase==='mulligan'&&!self.mulliganReady?[]:self.hand||[];handOrder=handOrder.filter(uid=>current.some(c=>c.uid===uid));for(const card of current)if(!handOrder.includes(card.uid))handOrder.push(card.uid);for(const uid of handOrder){const card=current.find(c=>c.uid===uid);const node=cardEl(card,{active:selected===uid||mulliganSelected.has(uid)});node.classList.add('hand-card');if(pendingArrival.includes(uid))node.classList.add('pending-arrival');if(!state.spectator)bindLiveHandDrag(node,card);hand.append(node);}layoutHand();}
function bindCardDrag(node,card,kind='hand'){
 node.draggable=false;node.style.touchAction='none';node.classList.add('draggable');node.querySelectorAll('img').forEach(img=>img.draggable=false);
 node.onpointerdown=event=>{
  if(event.button!==0||commandBusy||state.phase==='mulligan')return;cleanupDrag();
  const origin={x:event.clientX,y:event.clientY};let ghost=null,timer;
  const clean=()=>{clearTimeout(timer);ghost?.remove();node.classList.remove('dragging-source');document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',release);document.removeEventListener('pointercancel',cancel);document.querySelectorAll('.drop-ready').forEach(el=>el.classList.remove('drop-ready'));activeDrag=null;};
  const cancel=()=>clean();
  const move=e=>{
   if(!ghost&&Math.hypot(e.clientX-origin.x,e.clientY-origin.y)<7)return;
   e.preventDefault();if(!ghost){hideHover();ghost=cloneVisual(node);ghost.classList.remove('pending-arrival');ghost.classList.add('drag-preview');ghost.style.visibility='';ghost.style.setProperty('width',node.offsetWidth+'px','important');ghost.style.setProperty('height',node.offsetHeight+'px','important');$('visual-layer').append(ghost);node.classList.add('dragging-source');}
   ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';
   document.querySelectorAll('.drop-ready').forEach(el=>el.classList.remove('drop-ready'));
   const target=document.elementFromPoint(e.clientX,e.clientY),lane=target?.closest('.lane-side'),zone=target?.closest('#self-reserve-area,#self-emana-zone,#hand');
   if(lane||zone)(lane||zone).classList.add('drop-ready');
   const over=target?.closest('.hand-card');if(kind==='hand'&&over&&over!==node){const rect=over.getBoundingClientRect();$('hand').insertBefore(node,e.clientX>rect.left+rect.width/2?over.nextSibling:over);handOrder=[...$('hand').querySelectorAll('.hand-card')].map(el=>el.dataset.uid);layoutHand();}
  };
  const release=e=>{
   const rect=ghost?.getBoundingClientRect(),target=document.elementFromPoint(e.clientX,e.clientY),lane=target?.closest('.lane-side'),zone=target?.closest('#self-reserve-area,#self-emana-zone,#hand');let action=null;
   if(kind==='prepared'){
    if(lane&&canPrepareOn(card,lane.dataset.owner))action={type:'movePrepared',cardId:card.uid,lane:Number(lane.dataset.lane),targetSide:lane.dataset.owner};
    else if(zone)action={type:'unprepare',cardId:card.uid};
   }
   else if(kind==='hand'&&state.phase==='prep'&&state.turn===seat()?.id){
    if(card.type==='creature'&&zone&&zone.id!=='hand')action={type:'play',cardId:card.uid,...(zone.id==='self-emana-zone'?{mode:'emanate'}:{})};
    else if(card.type!=='creature'&&lane&&!card.directOnly&&canPrepareOn(card,lane.dataset.owner))action={type:'play',cardId:card.uid,mode:'lane',lane:Number(lane.dataset.lane),targetSide:lane.dataset.owner};
   }else if(kind==='reserve'&&state.phase==='formation'&&!seat().ready){
    if(lane?.dataset.owner===seat().id)action={type:'assign',cardId:card.uid,lane:Number(lane.dataset.lane)};
    else if(zone?.id==='self-reserve-area'){const index=seat().formation.indexOf(card.uid);if(index!==-1)action={type:'assign',cardId:null,lane:index};}
   }
   const moved=Boolean(ghost),held=action&&ghost?cloneVisual(ghost):null;
   if(held){held.classList.remove('drag-preview');held.classList.add('release-ghost');held.style.pointerEvents='none';document.body.append(held);}
   clean();if(!moved)return;suppressClickUntil=Date.now()+450;selected=null;
   if(action){movingCards.add(card.uid);node.style.visibility='hidden';command(action,rect).finally(()=>{held?.remove();finishVisual(card.uid);});}
  };
  activeDrag=clean;timer=setTimeout(clean,15000);document.addEventListener('pointermove',move,{passive:false});document.addEventListener('pointerup',release);document.addEventListener('pointercancel',cancel);
 };
}
function bindLiveHandDrag(node,card){bindCardDrag(node,card,'hand');}
function makeDraggable(node,card){if(state.phase==='formation'&&!seat().ready&&!seat().emanation.includes(card.uid))bindCardDrag(node,card,'reserve');}
function revealArrival(uid=pendingArrival[0]){if(!uid)return;pendingArrival=pendingArrival.filter(id=>id!==uid);for(const node of document.querySelectorAll('.card'))if(node.dataset.uid===uid){node.classList.remove('pending-arrival');node.classList.add('arrived');setTimeout(()=>node.classList.remove('arrived'),650);}}
function showCemetery(player){hideHover();const dialog=$('cemetery-detail'),area=$('cemetery-content');area.replaceChildren();text(area,'h2',`Nartvanyr · ${player.name}`);text(area,'p',`${player.discardCount} carta(s) consumida(s) ou derrotada(s). Clique numa carta para ler tudo.`);const row=document.createElement('div');row.className='cemetery-cards';for(const card of [...(player.discard||[])].reverse()){const node=cardEl(card);node.classList.add('cemetery-card');node.onmouseenter=node.onmousemove=node.onmouseleave=null;node.onclick=()=>showCard(card);row.append(node);}area.append(row);dialog.showModal();}
function makeSelect(options){const select=document.createElement('select');for(const [value,label] of options){const option=document.createElement('option');option.value=value;option.textContent=label;select.append(option);}return select;}
function showTauntPicker(card){
 if(state.phase!=='formation'||seat().ready||!seat().formation.includes(card.uid))return;
 hideHover();const dialog=$('target-picker'),content=$('target-picker-content');content.replaceChildren();text(content,'h2','Escolha a posição para Provocar');
 const row=document.createElement('div');row.className='taunt-options';const ownLane=seat().formation.indexOf(card.uid);
 for(let lane=0;lane<3;lane++)if(Math.abs(lane-ownLane)===1){const occupied=Object.entries(seat().taunts||{}).some(([uid,value])=>uid!==card.uid&&value===lane&&seat().formation.includes(uid));row.append(button(laneSymbols[lane],()=>{dialog.close();command({type:'taunt',cardId:card.uid,lane});},seat().taunts?.[card.uid]===lane?'primary':'',occupied));}
 content.append(row);if(!dialog.open)dialog.showModal();
}
function showTargetPicker(source,ids,onChoose){
 hideHover();const dialog=$('target-picker'),content=$('target-picker-content');const targets=ids.map(uid=>({uid,card:state.players.flatMap(p=>p.reserve).find(c=>c.uid===uid)})).filter(t=>t.card||t.uid==='patron');if(!targets.length){if(dialog.open)dialog.close();return;}content.replaceChildren();text(content,'h2','Escolha o alvo');const row=document.createElement('div');row.className='target-options';
 for(const {uid,card} of targets){const picture=uid==='patron'?$('self-head').querySelector('.patron-card').cloneNode(true):cardEl(card);picture.classList.add('target-card');if(uid==='patron'){picture.setAttribute('role','button');picture.setAttribute('aria-label','Patrono: '+seat().patron.name);picture.tabIndex=0;picture.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();picture.onclick();}};}picture.onmouseenter=()=>tableCard(uid)?.classList.add('target-highlight');picture.onmouseleave=()=>tableCard(uid)?.classList.remove('target-highlight');picture.onmousemove=picture.ondblclick=null;picture.onclick=()=>{document.querySelectorAll('.target-highlight').forEach(n=>n.classList.remove('target-highlight'));dialog.close();onChoose(uid);};row.append(picture);}content.append(row);if(!dialog.open)dialog.showModal();
}
function chooseEmanationTarget(card){if(state.phase!=='prep'||state.turn!==state.you)return;const effect=card.effects?.find(e=>e.op==='heal');if(seat().mana<(effect?.mana_cost||0))return;showTargetPicker(card,[...seat().reserve.filter(c=>c.damage>0&&(!effect?.exclude_self||c.uid!==card.uid)).map(c=>c.uid),...(effect?.allow_patron&&seat().patron.hp<seat().patron.maxHp?['patron']:[])],uid=>{emanationChoices.set(card.uid,uid);render();},true);}
function promptEmanationTarget(){if(state?.phase!=='prep'||state.turn!==state.you||state.spectator||$('target-picker').open)return;const card=seat().reserve.find(c=>seat().emanation.includes(c.uid)&&c.effects?.some(e=>e.op==='heal'&&String(e.timing).includes('emanat'))&&!promptedEmanations.has(c.uid));if(!card)return;promptedEmanations.add(card.uid);visualQueue.then(()=>noticeQueue).then(()=>pause(250)).then(()=>{if(state?.phase==='prep'&&state.turn===state.you&&seat().emanation.includes(card.uid)&&!$('target-picker').open)chooseEmanationTarget(card);}).catch(err);}
function showEmanationMenu(card){hideHover();const dialog=$('target-picker'),content=$('target-picker-content');content.replaceChildren();text(content,'h2',card.name);content.append(button('Trocar de local · 1 mana',()=>{dialog.close();command({type:'emanate',cardId:card.uid});},'',seat().mana<1));if(card.effects?.some(e=>e.op==='heal'&&String(e.timing).includes('emanat'))){content.append(button('Mudar alvo',()=>chooseEmanationTarget(card)));if(emanationChoices.has(card.uid))content.append(button('Cancelar cura',()=>{emanationChoices.delete(card.uid);dialog.close();render();}));text(content,'p','A cura acontece ao encerrar a preparação e exige a mana indicada.');}else text(content,'p','Esta Emanação aplica seu efeito automaticamente.');if(!dialog.open)dialog.showModal();}
let targetLinkFrame=null;
function renderTargetLinks(){
 const svg=$('target-links');if(targetLinkFrame)cancelAnimationFrame(targetLinkFrame);targetLinkFrame=null;
 if(!state||!['prep','vote','formation','resolving'].includes(state.phase)||state.spectator){svg.replaceChildren();return;}
 const bounds=svg.getBoundingClientRect();svg.setAttribute('viewBox',`0 0 ${bounds.width} ${bounds.height}`);svg.setAttribute('preserveAspectRatio','none');svg.style.overflow='visible';const ns='http://www.w3.org/2000/svg',active=new Set();
 for(const [sourceId,targetId] of [...emanationChoices,...spellTargets]){
  if(!seat().emanation.includes(sourceId)&&!seat().hand?.some(c=>c.uid===sourceId))continue;
  const from=tableCard(sourceId),to=targetId==='patron'?$('self-head').querySelector('.patron-card'):tableCard(targetId);if(!from||!to)continue;
  const key=sourceId+':'+targetId;active.add(key);let group=[...svg.children].find(n=>n.dataset.key===key);if(!group){group=document.createElementNS(ns,'g');group.dataset.key=key;for(const cls of ['target-link','target-flow','target-arrow']){const path=document.createElementNS(ns,'path');path.setAttribute('class',cls);group.append(path);}svg.append(group);}
  const motion=RunaMotion.link(from.getBoundingClientRect(),to.getBoundingClientRect()),matrix=svg.getScreenCTM();if(!matrix)continue;const convert=p=>new DOMPoint(p.x,p.y).matrixTransform(matrix.inverse()),a=convert(motion.start),b=convert(motion.end),c=convert(motion.control),d='M '+a.x+' '+a.y+' Q '+c.x+' '+c.y+' '+b.x+' '+b.y;group.children[0].setAttribute('d',d);group.children[1].setAttribute('d',d);const angle=Math.atan2(b.y-c.y,b.x-c.x),backX=b.x-10*Math.cos(angle),backY=b.y-10*Math.sin(angle);group.children[2].setAttribute('d',`M ${backX+5*Math.sin(angle)} ${backY-5*Math.cos(angle)} L ${b.x} ${b.y} L ${backX-5*Math.sin(angle)} ${backY+5*Math.cos(angle)}`);
 }
 for(const group of [...svg.children])if(!active.has(group.dataset.key))group.remove();
 if(active.size)targetLinkFrame=requestAnimationFrame(renderTargetLinks);
}
function scheduleAutomaticMulligan(){const p=seat();if(state?.spectator||state?.phase!=='mulligan'||p?.mulliganReady||p?.mulligansLeft!==0){autoMulliganKey='';return;}const key=`${state.code}:${p.id}`;if(autoMulliganKey===key)return;autoMulliganKey=key;visualQueue=visualQueue.then(async()=>{await pause(1000);if(autoMulliganKey===key&&state?.phase==='mulligan'&&!seat()?.mulliganReady&&seat()?.mulligansLeft===0){mulliganSelected.clear();await command({type:'confirmMulligan'});}}).catch(err);}
window.addEventListener('resize',renderTargetLinks);window.addEventListener('scroll',renderTargetLinks,true);
function renderSelection(){const panel=$('selection-panel');panel.replaceChildren();panel.hidden=true;}
function canPrepareOn(card,owner){const op=card.effects?.[0]?.op;if(op==='anchor')return true;const allied=['friendly','friendly-or-patron','self'].includes(role(card))||op==='barrier';return (owner===state.you)===(!card.enemyOnly&&allied);}
function chooseSpellTarget(card){
 if(commandBusy||state.phase!=='prep'||state.turn!==state.you)return;
 if(!affordable(card)){err('Mana insuficiente.');return;}
 if(card.positionOnly){const dialog=$('target-picker'),content=$('target-picker-content');content.replaceChildren();text(content,'h2','Escolha a posição');for(const p of state.players){if(!canPrepareOn(card,p.id))continue;text(content,'p',p.id===state.you?'Aliado':'Rival');const row=document.createElement('div');row.className='taunt-options';for(let lane=0;lane<3;lane++)row.append(button(laneSymbols[lane],()=>{dialog.close();command({type:'play',cardId:card.uid,mode:'lane',lane,targetSide:p.id});}));content.append(row);}dialog.showModal();return;}
 const kind=role(card),self=seat(),cast=targetId=>{selected=null;command({type:'play',cardId:card.uid,mode:'direct',targetId});};
 if(['self','enemy-board'].includes(kind)){const dialog=$('target-picker'),content=$('target-picker-content');content.replaceChildren();text(content,'h2','Usar magia');content.append(button(card.name,()=>{dialog.close();cast('');},'primary'));dialog.showModal();return;}
 const ids=kind==='enemy'?(rival()?.reserve||[]).filter(c=>!card.reserveOnly||!rival().emanation.includes(c.uid)).map(c=>c.uid):self.reserve.map(c=>c.uid);if(kind==='friendly-or-patron')ids.unshift('patron');showTargetPicker(card,ids,cast);
}
function promptDiscard(){if(!seat()?.pendingDiscard)return;hideHover();const dialog=$('target-picker'),content=$('target-picker-content');if(dialog.dataset.discardRevision===String(state.revision)&&dialog.open)return;dialog.dataset.discardRevision=String(state.revision);content.replaceChildren();text(content,'h2','Escolha uma carta para descartar');const row=document.createElement('div');row.className='target-options';for(const c of seat().hand||[]){const node=cardEl(c);node.onmouseenter=node.onmousemove=node.onmouseleave=null;node.onclick=()=>{dialog.close();command({type:'discard',cardId:c.uid});};row.append(node);}content.append(row);if(!dialog.open)dialog.showModal();}
function renderActions(){const box=$('phase-actions');box.replaceChildren();const self=seat();if(!self)return;const choiceTurn=!state.spectator?`${state.code}:${state.round}:${self.id}`:'';if(choiceTurn!==emanationChoiceTurn){emanationChoices.clear();spellTargets.clear();promptedEmanations.clear();emanationChoiceTurn=choiceTurn;}$('game').dataset.phase=state.phase;const message=$('match-status');
  const label=state.phase==='coin'?'Moeda lançada':state.phase==='mulligan'?'Escolha da mão inicial':state.phase==='prep'?state.turn===self.id?'Sua preparação':'Preparação rival':state.phase==='vote'?'Decisão de combate':state.phase==='formation'?'Formação secreta':state.phase==='resolving'?'Confronto em curso':state.phase==='finished'?'Partida encerrada':'Aguardando';
  message.textContent=state.phase==='prep'?'':label+` · rodada ${state.round}`;message.hidden=['prep','finished'].includes(state.phase);if(state.phase==='finished')message.textContent='';
  if(state.spectator){text(box,'h3','Arquibancada');text(box,'p','Você acompanha a partida sem ver as mãos nem as formações secretas.');return;}
  if(state.phase==='coin'){
    text(box,'h3','O vencedor da moeda joga primeiro.');
  }else if(state.phase==='mulligan'){
    text(box,'h3','Mão inicial');text(box,'p','Escolha as cartas na janela central.');
  }else if(state.phase==='prep'){
    if(state.turn===self.id){const clerics=self.emanation.map(uid=>self.reserve.find(c=>c.uid===uid)).filter(c=>c?.effects?.some(e=>e.op==='heal'&&String(e.timing).includes('emanat')));for(const cleric of clerics){const uid=emanationChoices.get(cleric.uid),target=self.reserve.find(c=>c.uid===uid&&c.damage>0);if(uid&&!target&&!(uid==='patron'&&cleric.effects.some(e=>e.allow_patron)&&self.patron.hp<self.patron.maxHp))emanationChoices.delete(cleric.uid);}
      const healingCost=clerics.filter(c=>emanationChoices.has(c.uid)).reduce((n,c)=>n+(c.effects.find(e=>e.op==='heal'&&String(e.timing).includes('emanat'))?.mana_cost||0),0);if(healingCost)text(box,'p',`Curas escolhidas: ${healingCost} mana ao encerrar${self.mana<healingCost?' · falta mana':''}`);text(box,'h3',`Preparação - Rodada ${state.round}`);box.append(button('Encerrar',()=>command({type:'endPrep',healTargetIds:clerics.map(c=>emanationChoices.get(c.uid)||'')}),'primary',self.mana<healingCost));}else{text(box,'h3',`Preparação - Rodada ${state.round}`);box.append(button('Turno do oponente',()=>{},'',true));}
  }else if(state.phase==='vote'){
    if(self.voted)text(box,'p','Você recusou. Aguardando a decisão rival.','status-pill');else{box.append(button('Começar combate',()=>command({type:'vote',fight:true}),'primary'));box.append(button('Não combater',()=>command({type:'vote',fight:false})));}
  }else if(state.phase==='formation'){
    text(box,'h3',`Combate - Rodada ${state.round}`);
    if(self.ready)box.append(button('Turno do oponente',()=>{},'',true));else box.append(button('Encerrar',()=>command({type:'ready'}),'primary'));
  }else if(state.phase==='resolving'){
    text(box,'h3',`Combate - Rodada ${state.round}`);box.append(button('Turno de combate',()=>{},'',true));
  }else if(state.phase==='finished'){
    if(!state.winner)text(box,'h3','Empate!');box.append(button('Nova partida',()=>{selected=null;command({type:'reset'});},'primary'));
  }
}
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const unlockAudio=()=>{try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();}catch{}};
document.addEventListener('pointerdown',()=>{unlockAudio();warmSounds();});document.addEventListener('keydown',unlockAudio,{once:true});
function visualMessage(title,caption='',duration=1050){const generation=visualGeneration;noticeQueue=noticeQueue.catch(()=>{}).then(async()=>{if(generation!==visualGeneration)return;const layer=$('notice-layer'),box=document.createElement('div');box.className='visual-message';box.style.animationDuration=duration+'ms';text(box,'strong',title);if(caption)text(box,'span',caption);layer.replaceChildren(box);await pause(duration);box.remove();});return noticeQueue;}
const soundFiles={impactLow:['impactGeneric_light_000.ogg','impactGeneric_light_002.ogg'],impactMedium:['impactPunch_medium_000.ogg','impactPunch_medium_002.ogg'],impactHeavy:['impactPunch_heavy_000.ogg','impactPunch_heavy_002.ogg'],grave:['bookClose.ogg','dropLeather.ogg'],place:['bookPlace1.ogg','bookPlace2.ogg'],arrow:['knifeSlice.ogg','knifeSlice2.ogg'],gun:['chop.ogg'],capture:['capture-shot.wav'],heal:['impactBell_heavy_000.ogg'],burn:['cloth1.ogg'],coin:['handleCoins.ogg','handleCoins2.ogg'],draw:['bookFlip1.ogg','bookFlip2.ogg','bookFlip3.ogg'],magic:['impactGlass_light_000.ogg','impactBell_heavy_002.ogg']};
const soundBuffers=new Map();let soundLoading=null;
function warmSounds(){if(soundLoading)return soundLoading;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();soundLoading=Promise.all([...new Set(Object.values(soundFiles).flat())].map(async file=>{try{const response=await fetch(gameBase+'audio/'+file);if(!response.ok)return;const buffer=await audioContext.decodeAudioData(await response.arrayBuffer());soundBuffers.set(file,buffer);}catch{}}));return soundLoading;}catch{return Promise.resolve();}}
function sound(kind='magic',attack=0){try{if(!audioContext||audioContext.state!=='running')return;const key=kind==='impact'?(attack<=3?'impactLow':attack<=6?'impactMedium':'impactHeavy'):kind,files=soundFiles[key]||soundFiles.magic,buffer=soundBuffers.get(files[Math.floor(Math.random()*files.length)]);if(!buffer)return;const source=audioContext.createBufferSource(),gain=audioContext.createGain();source.buffer=buffer;gain.gain.value=kind==='heal'?.18:kind==='impact'?.42:.3;source.connect(gain).connect(audioContext.destination);source.start(audioContext.currentTime);}catch{}}
function animationCue(animation,fraction,callback){const generation=visualGeneration;let frame;const duration=Number(animation.effect.getTiming().duration);function check(){if(animation.playState==='idle'||generation!==visualGeneration)return;if(Number(animation.currentTime)>=duration*fraction){callback();return;}frame=requestAnimationFrame(check);}frame=requestAnimationFrame(check);animation.finished.catch(()=>{}).finally(()=>cancelAnimationFrame(frame));}
warmSounds();
function spellSound(name,op){return /flecha|arco|besta|seta/i.test(name)?'arrow':/tiro|disparo|cartucho|pistola/i.test(name)?'gun':op==='heal'||op==='stat_buff'?'heal':'magic';}
function currentVisualTarget(target){if(target&&!target.nodeType)return target;if(target?.isConnected)return target;if(target?.dataset?.uid)return tableCard(target.dataset.uid)||target;if(target?.matches('.patron-card')&&target.dataset.owner)return $(target.dataset.owner===seat()?.id?'self-head':'opponent-head')?.querySelector('.patron-card')||target;return target;}
function impact(target,positive=false){target=currentVisualTarget(target);if(!target)return;if(target.matches?.('.patron-card')&&!positive){patronImpact(target);return;}const pos=center(target),ring=document.createElement('div');ring.className=`spell-impact${positive?' positive':''}`;ring.style.left=`${pos.x}px`;ring.style.top=`${pos.y}px`;$('visual-layer').append(ring);for(let i=0;i<12;i++){const spark=document.createElement('span');spark.style.setProperty('--angle',`${i*30}deg`);ring.append(spark);}setTimeout(()=>ring.remove(),1050);target.classList?.add('visual-hit');setTimeout(()=>target.classList?.remove('visual-hit'),800);}
function healPulse(target){if(!target)return;const p=center(target),aura=document.createElement('div');aura.className='healing-aura';Object.assign(aura.style,{left:p.x+'px',top:p.y+'px'});aura.textContent='✦';$('visual-layer').append(aura);setTimeout(()=>aura.remove(),1200);}
function buffRise(target,amount=1,attackAfter=null){const generation=visualGeneration;if(!target)return;amount=Number(amount)||0;const card=target.matches('.card')?target:target.querySelector('.card'),uid=card?.dataset.uid,shown=displayedAttack.get(uid)??(Number(card?.querySelector('.attack-value')?.textContent)||0),combatId=state?.combat?.id||null;const r=target.getBoundingClientRect(),arrow=document.createElement('div');arrow.className='buff-rise';Object.assign(arrow.style,{left:(r.right+8)+'px',top:(r.top+r.height/2)+'px'});arrow.textContent=`↑ +${amount}`;$('visual-layer').append(arrow);setTimeout(()=>{arrow.remove();if(generation!==visualGeneration||!uid||(state?.combat?.id||null)!==combatId)return;const value=attackAfter??pendingAttack.get(uid)??Math.max(0,shown+amount);displayedAttack.set(uid,value);if(value>=(pendingAttack.get(uid)??value))pendingAttack.delete(uid);for(const node of document.querySelectorAll('.card'))if(node.dataset.uid===uid){const number=node.querySelector('.attack-value');if(number){number.textContent=String(value);number.classList.remove('attack-increased');void number.offsetWidth;number.classList.add('attack-increased');number.classList.toggle('attack-buffed',value>Number(node.dataset.baseAttack));}}},1100);}
function patronImpact(patron){patron=currentVisualTarget(patron);if(!patron)return;const pos=center(patron),ring=document.createElement('div');ring.className='patron-impact-ring';Object.assign(ring.style,{left:pos.x+'px',top:pos.y+'px'});$('visual-layer').append(ring);setTimeout(()=>ring.remove(),450);patron.classList.remove('visual-hit');const direction=patron.closest('#self-head')?1:-1;patron.animate([{transform:'translateY(0)'},{transform:`translateY(${direction*10}px)`,offset:.35},{transform:'translateY(0)'}],{duration:300,easing:'ease-out'});const tint=document.createElement('div');tint.className='patron-red-flash';patron.append(tint);setTimeout(()=>tint.remove(),350);}
function speechBubble(event){const zone=$(event.zone==='emana'?(event.playerId===seat()?.id?'self-emana':'opponent-emana'):(event.playerId===seat()?.id?'self-reserve':'opponent-reserve'));const target=tableCard(event.cardId)||zone;if(!target)return;const box=document.createElement('div');box.className='speech-bubble';box.textContent=event.speech||'Estou a postos!';const pos=center(target);box.dataset.eventId=event.id;box.style.position='fixed';box.style.zIndex='200';box.style.left=`${Math.max(145,Math.min(innerWidth-145,pos.x))}px`;box.style.top=`${Math.max(($('top')?.getBoundingClientRect().bottom||115)+70,Math.min(innerHeight-20,pos.y-45))}px`;document.body.append(box);setTimeout(()=>box.remove(),3600);}
function center(node){const rect=node?.getBoundingClientRect();return rect?{x:rect.left+rect.width/2,y:rect.top+rect.height/2}:{x:innerWidth/2,y:innerHeight/2};}
function fly(symbol,from,to,kind='spell',onHit=null){const start=center(from),end=center(to),node=document.createElement('div');node.className=`flying-effect ${kind}`;node.textContent=symbol;node.style.left=`${start.x}px`;node.style.top=`${start.y}px`;(kind==='capture-bullet'?document.querySelector('.capture-scene'):$('visual-layer')).append(node);const animation=node.animate([{transform:'translate(-50%,-50%) scale(.7)',opacity:0},{transform:'translate(-50%,-50%) scale(1.2)',opacity:1,offset:.18},{transform:`translate(calc(${end.x-start.x}px - 50%),calc(${end.y-start.y}px - 50%)) scale(.9)`,opacity:1,offset:.84},{transform:`translate(calc(${end.x-start.x}px - 50%),calc(${end.y-start.y}px - 50%)) scale(1.8)`,opacity:0}],{duration:900,easing:'ease-in-out'});if(onHit)animationCue(animation,.84,onHit);animation.finished.catch(()=>{}).finally(()=>node.remove());return animation;}
function weightOf(card){return Math.max(0,Math.min(1,((card?.attack||0)+(card?.health||0)-6)/14));}
function finishVisual(uid,copy){copy?.remove();movingCards.delete(uid);pendingArrival=pendingArrival.filter(id=>id!==uid);for(const node of document.querySelectorAll('#game .card,#game .spell-mark'))if(node.dataset.uid===uid){node.classList.remove('pending-arrival');node.style.visibility=state?.phase==='resolving'&&state.combat?.casualties?.some(c=>c.uid===uid)?'hidden':'';}}
async function safeFlight(copy,frames,options,uid){const generation=visualGeneration,animation=copy.animate(frames,options);try{await Promise.race([animation.finished.catch(()=>{}),pause((options.duration||1000)+(options.delay||0)+400)]);}finally{animation.cancel();if(generation===visualGeneration)finishVisual(uid,copy);else copy.remove();}}
async function settleAnimation(animation,duration=2000){try{await Promise.race([animation.finished,pause(duration+400)]);}catch{}finally{animation.cancel();}}
function visualCard(source){const rect=source.getBoundingClientRect(),copy=cloneVisual(source);copy.classList.remove('hand-card','dragging-source','pending-arrival','selected','arrived','snapping','visual-hit');copy.classList.add('visual-card');Object.assign(copy.style,{left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px',visibility:'',transform:'none',animation:'none',margin:'0',transformOrigin:'center',transition:'none'});$('visual-layer').append(copy);movingCards.add(source.dataset.uid);source.style.visibility='hidden';return copy;}
async function animateTransfer({uid,copy,rect,card,duration:customDuration,delay=0,destination=null}){
 const generation=visualGeneration;let arrival=null,flight=null;
 try{
  const target=destination?document.querySelector(destination):tableCard(uid);if(!target||!rect)return;
  const changesFace=copy.classList.contains('combat-card')!==target.classList.contains('combat-card')||copy.classList.contains('spell-mark');
  if(changesFace)await Promise.race([target.visualReady,pause(1800)]);if(generation!==visualGeneration||!target.isConnected&&target.isConnected!==undefined)return;
  const end=target.getBoundingClientRect(),bounds=$('visual-layer').getBoundingClientRect();if(!end.width||!end.height)return;
  movingCards.add(uid);target.style.visibility='hidden';pendingArrival=pendingArrival.filter(id=>id!==uid);
  const dx=end.left+end.width/2-rect.left-rect.width/2,dy=end.top+end.height/2-rect.top-rect.height/2;
  const make=(face,w,h)=>{const wrapper=document.createElement('div');wrapper.className='card-flight';Object.assign(wrapper.style,{left:(rect.left+rect.width/2-w/2-bounds.left)+'px',top:(rect.top+rect.height/2-h/2-bounds.top)+'px',width:w+'px',height:h+'px'});face.classList.remove('hand-card','opening-card','dragging-source','drag-preview','pending-arrival','selected','arrived','snapping','visual-hit','payable');face.classList.add('flight-face');face.removeAttribute('style');wrapper.append(face);$('visual-layer').append(wrapper);return wrapper;};
  flight=make(copy,rect.width,rect.height);
  document.querySelectorAll('.release-ghost').forEach(node=>node.remove());
  const duration=customDuration??(720+weightOf(card)*180),options={duration,delay,easing:'cubic-bezier(.22,.65,.22,1)',fill:'both'};
  const oldScale=end.width/rect.width,newScale=rect.width/end.width;
  if(!changesFace){
   const animation=flight.animate([{transform:'translate(0,0) scale(1)'},{transform:'translate('+dx+'px,'+dy+'px) scale('+oldScale+')'}],options);await settleAnimation(animation,duration+delay);
   if(generation===visualGeneration)sound('place');return;
  }
  arrival=make(cloneVisual(target),end.width,end.height);
  const departing=flight.animate([{transform:'translate(0,0) scale(1)',opacity:1},{opacity:1,offset:.15},{opacity:0,offset:.7},{transform:'translate('+dx+'px,'+dy+'px) scale('+oldScale+')',opacity:0}],options);
  const arriving=arrival.animate([{transform:'translate(0,0) scale('+newScale+')',opacity:0},{opacity:0,offset:.15},{opacity:1,offset:.7},{transform:'translate('+dx+'px,'+dy+'px) scale(1)',opacity:1}],options);
  await Promise.all([settleAnimation(departing,duration+delay),settleAnimation(arriving,duration+delay)]);if(generation===visualGeneration)sound('place');
 }catch(error){console.error(error);}finally{flight?.remove();if(generation===visualGeneration)finishVisual(uid,arrival);else arrival?.remove();if(!flight)copy?.remove();}
}
async function animateMulliganReturn(event){
 const generation=visualGeneration,cards=mulliganDepartures.get(event.id)||[];mulliganDepartures.delete(event.id);
 if(!cards.length){await pause(350);return;}
 const end=center($('self-deck')),bounds=$('visual-layer').getBoundingClientRect();
 await Promise.all(cards.map(async({copy,rect},i)=>{
  const wrapper=document.createElement('div');wrapper.className='card-flight';Object.assign(wrapper.style,{left:(rect.left-bounds.left)+'px',top:(rect.top-bounds.top)+'px',width:rect.width+'px',height:rect.height+'px'});
  copy.classList.remove('opening-card','hand-card','selected','pending-arrival','arrived','payable');copy.classList.add('flight-face');copy.removeAttribute('style');wrapper.append(copy);$('visual-layer').append(wrapper);
  const dx=end.x-rect.left-rect.width/2,dy=end.y-rect.top-rect.height/2;
  try{await settleAnimation(wrapper.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:'translate('+dx+'px,'+dy+'px) scale(.28)',opacity:0}],{duration:600,delay:i*75,easing:'cubic-bezier(.4,0,.6,1)',fill:'both'}),600+i*75);}finally{wrapper.remove();}
 }));if(generation===visualGeneration)sound('place');
}
async function animateOpeningToHand(cards){
 const notice=visualMessage('MÃO CONFIRMADA','As cartas seguem para sua mão',1450);
 await Promise.all(cards.map((item,index)=>animateTransfer({...item,destination:'#hand .card[data-uid="'+item.uid+'"]',duration:1150,delay:index*110})));await notice;
}
async function animateDraw(uid,mine=true){
 const generation=visualGeneration;
 const target=mine?(state?.phase==='mulligan'&&!seat()?.mulliganReady?[...$('mulligan-cards').querySelectorAll('.card')].find(n=>n.dataset.uid===uid):tableCard(uid)):$('opponent-head');if(!target){if(mine)revealArrival(uid);return;}
 const from=center($(mine?'self-deck':'opponent-deck')),to=center(target),card=seat()?.hand?.find(c=>c.uid===uid),copy=mine&&card?cardEl(card):document.createElement('div');copy.classList.add('card');copy.classList.remove('pending-arrival');copy.classList.add('draw-flight');copy.style.left=(from.x-42)+'px';copy.style.top=(from.y-58)+'px';copy.style.width='84px';copy.style.height='116px';copy.style.visibility='';const front=[...copy.childNodes];copy.replaceChildren();copy.classList.remove('has-art','wounded','payable');copy.classList.add('back');copy.removeAttribute('data-uid');copy.removeAttribute('aria-label');const backImage=document.createElement('img');backImage.src='card-back.png';backImage.className='concealed-back-image';backImage.alt='Verso da carta';copy.append(backImage);$('visual-layer').append(copy);const dx=to.x-from.x,dy=to.y-from.y;
 const flip=mine?'90deg':'0deg';const anim=copy.animate([{transform:'translate(0,0) rotateY(0deg) scale(.7)',opacity:0},{transform:`translate(${dx*.4}px,${dy*.4}px) rotateY(${flip}) scale(1)`,opacity:1,offset:.45},{transform:`translate(${dx}px,${dy}px) rotateY(0deg) scale(${mine?target.getBoundingClientRect().width/84:.7})`,opacity:1}],{duration:630,easing:'cubic-bezier(.25,.1,.25,1)',fill:'forwards'});sound('draw');
 setTimeout(()=>{if(mine&&generation===visualGeneration){copy.classList.remove('back');if(card?.imageKind==='card')copy.classList.add('has-art');copy.replaceChildren(...front);}},285);
 try{await settleAnimation(anim,630);}finally{copy.remove();if(mine&&generation===visualGeneration)revealArrival(uid);}
}
function attackTarget(hit){
 if(!hit.targetOwner||hit.targetOwner===hit.owner)return null;
 if(hit.targetId){const node=[...document.querySelectorAll('#lanes .lane-side .card')].find(n=>n.dataset.uid===hit.targetId&&n.closest('.lane-side')?.dataset.owner===hit.targetOwner);return node||null;}
 return $(hit.targetOwner===seat()?.id?'self-head':'opponent-head')?.querySelector('.patron-card')||null;
}
async function animateLaneClash(entry){
 const generation=visualGeneration;
 for(const card of entry.cards.filter(Boolean)){displayedAttack.set(card.uid,card.attack);const number=tableCard(card.uid)?.querySelector('.attack-value');if(number){number.textContent=String(card.attack);number.classList.toggle('attack-buffed',card.attack>Number(number.closest('.card').dataset.baseAttack));}}
 const [left,right]=entry.cards,parts=entry.cards.map(card=>card?tableCard(card.uid):null);if(!parts.some(Boolean))return;
 const weight=Math.max(...entry.cards.filter(Boolean).map(weightOf));const attackStrength=Math.max(...entry.cards.filter(Boolean).map(c=>c.attack||0));
 if(left&&right){
  if(!parts.every(Boolean))return;
  const a=center(parts[0]),b=center(parts[1]),{dx,dy}=RunaMotion.contact(parts[0].getBoundingClientRect(),parts[1].getBoundingClientRect()),copies=parts.map(visualCard),duration=1350+weight*350;
  const animations=copies.map((copy,i)=>copy.animate(RunaMotion.strikeFrames(i?-dx:dx,i?-dy:dy),{duration,easing:'linear',fill:'forwards'}));
  animationCue(animations[0],.42,()=>{copies.forEach(node=>impact(node));applyHealthUpdates(entry.healthUpdates||entry.cards.map((card,i)=>({uid:card.uid,hp:Math.max(0,card.health-entry.cards[1-i].attack),maxHp:state.players.flatMap(p=>p.reserve).find(c=>c.uid===card.uid)?.health||card.health})));sound('impact',attackStrength);});
  await Promise.all(animations.map(a=>settleAnimation(a,duration)));
  if(generation!==visualGeneration){copies.forEach(copy=>copy.remove());return;}
  copies.forEach((copy,i)=>{if((entry.healthUpdates?.find(u=>u.uid===entry.cards[i].uid)?.hp??(entry.cards[i].health-entry.cards[1-i].attack))<=0){copy.classList.add('visual-dead');deadVisuals.set(entry.cards[i].uid,{copy,owner:entry.cards[i].owner});}else finishVisual(entry.cards[i].uid,copy);});return;
 }
 const card=left||right,source=parts[left?0:1],targetOwner=entry.targetOwner||state.players.find(p=>p.id!==card.owner)?.id,patron=attackTarget({owner:card.owner,targetOwner,targetId:null});if(!source||!card.owner||!patron)return;
 const copy=visualCard(source),motion=RunaMotion.contact(source.getBoundingClientRect(),patron.getBoundingClientRect(),false),duration=1550+weight*350;
 const hitAnimation=copy.animate(RunaMotion.strikeFrames(motion.dx,motion.dy),{duration,easing:'linear',fill:'forwards'});animationCue(hitAnimation,.42,()=>{patronImpact(patron);damagePatron(targetOwner,card.attack);sound('impact',attackStrength);});try{await settleAnimation(hitAnimation,duration);}catch{}finally{if(generation===visualGeneration)finishVisual(card.uid,copy);else copy.remove();}return;

}
async function animateDirectedStrike(strike){
 const generation=visualGeneration;
 if(strike.pair){const cards=[strike,strike.pair].map(hit=>{const c=state.combat.visual.flatMap(x=>x.cards.filter(Boolean)).find(x=>x.uid===hit.sourceId);return {...c,uid:hit.sourceId,owner:hit.owner,attack:hit.amount};});await animateLaneClash({lane:strike.lane,cards,healthUpdates:strike.healthUpdates});if(generation!==visualGeneration)return;for(const hit of [strike,strike.pair]){if(hit.patronDamage)damagePatron(hit.targetOwner,hit.patronDamage);for(const uid of hit.adjacent||[]){const target=tableCard(hit.targetId),neighbor=tableCard(uid);if(target&&neighbor)fly('✷',target,neighbor,'spell',()=>impact(neighbor));}}return;}

 if(strike.blocked)return;const preview=state.combat?.visual?.flatMap(entry=>entry.cards.filter(Boolean)).find(c=>c.uid===strike.sourceId);if(preview){displayedAttack.set(preview.uid,preview.attack);const number=tableCard(preview.uid)?.querySelector('.attack-value');if(number){number.textContent=String(preview.attack);number.classList.toggle('attack-buffed',preview.attack>Number(number.closest('.card').dataset.baseAttack));}}const source=tableCard(strike.sourceId),target=attackTarget(strike);if(!source||!target)return;
 const card=state.players.flatMap(p=>p.reserve).find(c=>c.uid===strike.sourceId),copy=visualCard(source),from=center(source),to=center(target),motion=RunaMotion.contact(source.getBoundingClientRect(),target.getBoundingClientRect(),false),dx=motion.dx,dy=motion.dy;
 if(strike.initiative)copy.classList.add('initiative-strike');const animation=copy.animate(RunaMotion.strikeFrames(dx,dy),{duration:1150,easing:'linear',fill:'forwards'});
 animationCue(animation,.42,()=>{if(strike.targetId)impact(target);else patronImpact(target);applyHealthUpdates(strike.healthUpdates);if(strike.patronDamage)damagePatron(strike.targetOwner,strike.patronDamage);sound('impact',strike.amount);for(const uid of strike.adjacent||[]){const neighbor=tableCard(uid);if(neighbor)fly('✷',target,neighbor,'spell',()=>impact(neighbor));}});
 try{await settleAnimation(animation,1150);}catch{}finally{if(generation===visualGeneration)finishVisual(strike.sourceId,copy);else copy.remove();}
}
function animateCasualties(battle){const generation=visualGeneration;
 for(const card of battle.casualties||[]){let record=deadVisuals.get(card.uid);if(!record){const source=tableCard(card.uid);if(!source)continue;record={copy:visualCard(source),owner:card.owner};record.copy.classList.add('visual-dead');}const {copy}=record,from=center(copy),to=center($(card.owner===seat()?.id?'self-grave':'opponent-grave'));
 safeFlight(copy,[{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${to.x-from.x}px,${to.y-from.y}px) scale(.35)`,opacity:0}],{duration:850,easing:'ease-in',fill:'forwards'},card.uid).then(()=>{if(generation===visualGeneration)sound('grave');});deadVisuals.delete(card.uid);}
}
async function animateBanquet(event){const generation=visualGeneration,updates=event.healthUpdates||[];sound('heal');await Promise.all(updates.map(async(update,i)=>{await pause(i*70);if(generation!==visualGeneration)return;const target=tableCard(update.uid);if(target){healPulse(target);const r=target.getBoundingClientRect(),spark=document.createElement('div');spark.className='banquet-halo';spark.style.left=(r.left+r.width/2)+'px';spark.style.top=(r.top+r.height/2)+'px';document.body.append(spark);setTimeout(()=>spark.remove(),1500);}applyHealthUpdates([update]);}));}
async function animateEvent(event,generation=visualGeneration){await noticeQueue;await warmSounds();if(generation!==visualGeneration)return;const player=state?.players.find(p=>p.id===event.playerId);const mine=player?.id===seat()?.id;const from=$(mine?'self-head':'opponent-head');const target=event.targetPatronId?$(event.targetPatronId===seat()?.id?'self-head':'opponent-head')?.querySelector('.patron-card'):event.targetId?spellTarget(event.targetId):null;
   if(event.type==='coin'){$('mulligan-overlay').classList.add('coin-pending');sound('coin');visualMessage('A MOEDA DECIDIU',`${player?.name||'Jogador'} joga primeiro`,1900);const coin=document.createElement('div');coin.className='coin-toss';coin.textContent='✦';$('visual-layer').append(coin);setTimeout(()=>coin.remove(),1900);await pause(1900);if(generation===visualGeneration)$('mulligan-overlay').classList.remove('coin-pending');}
   else if(event.type==='first'){visualMessage('ORDEM DEFINIDA',`${player?.name||'Jogador'} joga primeiro`,1500);await pause(1250);}
   else if(event.type==='opening'){if(mine){visualMessage('MÃO INICIAL','Você recebe cinco cartas',1900);const ids=event.cardIds||[...(seat()?.hand||[])].slice(0,event.count||5).map(c=>c.uid);for(const uid of ids){if(generation!==visualGeneration)break;await animateDraw(uid,true);}}}
   else if(event.type==='mulligan'){visualMessage('TROCA INICIAL',`${player?.name||'Jogador'} troca ${event.count} carta(s)`,950);await animateMulliganReturn(event);}
   else if(event.type==='turn'){await visualMessage('INÍCIO DE TURNO',`${player?.name||'Jogador'} · rodada ${event.round}`,1150);}
   else if(event.type==='draw'){await animateDraw(event.cardId||pendingArrival[0],mine);}
   else if(event.type==='burn'){visualMessage('CARTA QUEIMADA',`Mão cheia: ${event.name||'uma carta'} foi para o Nartvanyr`,1700);$('hand').classList.add('hand-burn');setTimeout(()=>$('hand').classList.remove('hand-burn'),1000);fly('▰',from,$(mine?'self-grave':'opponent-grave'),'burn');sound('burn');await pause(1550);}
   else if(event.type==='return'){visualMessage('RETORNO À MÃO',event.name,1100);const destination=mine?$('hand'):$('opponent-head');fly('▰',$(mine?'self-reserve':'opponent-reserve'),destination,'spell',()=>{if(mine)revealArrival(event.returnedId);});sound('magic');await pause(950);if(mine&&generation===visualGeneration)revealArrival(event.returnedId);}
   else if(event.type==='spell'&&event.op==='return_to_hand'){visualMessage(event.name,'Criatura devolvida à mão',900);sound('magic');await pause(500);}
   else if(event.type==='spell'){visualMessage(event.name,event.op==='area_damage'?'Dano em área':event.op==='heal'?'Cura':event.op==='attack_modifier'?(event.amount<0?'Redução permanente de ataque':'Aprimoramento'):event.op==='area_attack_modifier'?'Redução de ataque em área':'Magia resolvida',1600);const destination=target||(event.targetId?null:$('lanes'));if(event.op==='area_stat_buff'){await animateBanquet(event);}else if(['heal','choose_one'].includes(event.op)){healPulse(destination);deferVisual(()=>applyHealthUpdates(event.healthUpdates),500);}else if(['attack_modifier','stat_buff'].includes(event.op)&&event.amount>0){buffRise(destination,event.amount||2,event.attackAfter??null);deferVisual(()=>applyHealthUpdates(event.healthUpdates),500);}else{fly(event.op==='draw'?'▰':event.op==='area_damage'?'✷':'➶',from,destination,'spell',()=>{impact(destination);applyHealthUpdates(event.healthUpdates);sound('impact',event.amount||1);});}sound(spellSound(event.name,event.op==='choose_one'?'heal':event.op));await pause(1500);sound('grave');}
   else if(event.type==='cleric_heal'){healPulse(target);sound('heal');applyHealthUpdates(event.healthUpdates||[]);await pause(800);}
   else if(event.type==='creature'){if(!mine){const card=player?.reserve?.find(c=>c.uid===event.cardId),source=$(mine?'self-deck':'opponent-deck');if(card&&source)await animateTransfer({uid:card.uid,card,copy:cardEl(card),rect:source.getBoundingClientRect()});}if(generation===visualGeneration)speechBubble(event);await pause(750);}
  else if(event.type==='summon'){visualMessage('CONVOCAÇÃO',event.name,950);fly('✦',from,$(mine?'self-reserve':'opponent-reserve'),'positive');speechBubble(event);await pause(900);}
   else if(event.type==='expire'){sound('grave');fly('✧',from,$(mine?'self-grave':'opponent-grave'),'spell');await pause(500);}
}
function resetVisualSession(){
 const key=state?[state.code,state.you,state.matchId||'lobby'].join(':'):null;if(key===visualMatchKey)return;const sameSeat=state&&visualMatchKey?.startsWith([state.code,state.you].join(':')+':'),previousId=lastVisualId,wasBooted=visualBooted;
 visualMatchKey=key;visualGeneration++;visualQueue=Promise.resolve();noticeQueue=Promise.resolve();visualBooted=Boolean(sameSeat&&wasBooted);lastVisualId=sameSeat?previousId:0;lastBattleStep='';pendingArrival=[];movingCards.clear();deadVisuals.clear();displayedAttack.clear();pendingAttack.clear();displayedHealth.clear();pendingHealth.clear();displayedPatronHealth.clear();spellTargetRects.clear();mulliganDepartures.clear();
 for(const layer of ['visual-layer','notice-layer']){const node=$(layer);node?.getAnimations?.({subtree:true}).forEach(animation=>animation.cancel());node?.replaceChildren();}document.querySelectorAll('.speech-bubble,.banquet-halo').forEach(node=>node.remove());
}
function recoverVisualGap(){
 const events=state?.events||[],newest=state?.eventId??events.at(-1)?.id??0;
 if(!visualBooted||(state?.eventsFrom??events[0]?.id??newest+1)<=lastVisualId+1)return;
 visualGeneration++;visualQueue=Promise.resolve();noticeQueue=Promise.resolve();pendingArrival=[];movingCards.clear();deadVisuals.clear();displayedHealth.clear();pendingHealth.clear();displayedAttack.clear();pendingAttack.clear();displayedPatronHealth.clear();mulliganDepartures.clear();lastVisualId=newest;
 const layer=$('visual-layer');layer?.getAnimations?.({subtree:true}).forEach(a=>a.cancel());layer?.replaceChildren();$('notice-layer')?.replaceChildren();document.querySelectorAll('#game .card,#game .spell-mark').forEach(node=>{node.classList.remove('pending-arrival');node.style.visibility='';});
}
function queueEvents(){const events=state?.events||[];const newest=state?.eventId??events.at(-1)?.id??0,generation=visualGeneration;if(!visualBooted){lastVisualId=newest;visualBooted=true;for(const event of events.filter(e=>['creature','summon'].includes(e.type)&&Date.now()-serverClockOffset-e.at<3000))setTimeout(()=>{if(generation===visualGeneration)speechBubble(event);},850);return;}for(const event of events.filter(x=>x.id>lastVisualId)){visualQueue=visualQueue.then(()=>generation===visualGeneration?animateEvent(event,generation):null).catch(()=>{});}lastVisualId=newest;}
function tickCombat(){
  const overlay=$('battle-overlay');if(!state?.combat||state.phase!=='resolving'){overlay.hidden=true;lastBattleStep='';for(const [uid,{copy}] of deadVisuals)finishVisual(uid,copy);deadVisuals.clear();return;}
  const battle=state.combat,elapsed=Math.max(0,Date.now()-serverClockOffset-battle.startedAt);let remaining=elapsed,index=0;for(;index<battle.timeline.length-1&&remaining>=battle.timeline[index].duration;index++)remaining-=battle.timeline[index].duration;
  const key=`${battle.id}:${index}`;if(key===lastBattleStep)return;lastBattleStep=key;overlay.hidden=false;
  const step=battle.timeline[index],lanes=[...document.querySelectorAll('.lane')];for(const lane of lanes){lane.classList.remove('battle-reveal','battle-magic','battle-revelation','battle-clash','battle-aftermath');for(const side of lane.querySelectorAll('.lane-side')){side.classList.remove('effect-positive','effect-negative');delete side.dataset.effect;}}
  if(step.kind==='reveal'){applyHealthUpdates(battle.auraHealthUpdates||[]);for(const p of state.players){const bonus=p.emanation.reduce((n,uid)=>{const c=p.reserve.find(c=>c.uid===uid);return n+(c?.modelId==='R05'?1:0)+(c?.effects||[]).filter(e=>e.op==='lane_attack_aura'&&e.lane===0).reduce((sum,e)=>sum+e.amount,0);},0);if(bonus){const target=tableCard(p.formation[0]);if(target)buffRise(target,bonus);}}}
  const classes={reveal:'battle-reveal',magic:'battle-magic',revelation:'battle-revelation',clash:'battle-clash',strike:'battle-clash',growth:'battle-revelation',result:'battle-aftermath'};
  let caption={reveal:'As formações deixam de ser segredo.',revelation:'Habilidades de Revelação entram em ação.',clash:'Criaturas se chocam; posições vazias expõem o Patrono.',result:'O resultado está sendo aplicado.'}[step.kind]||'';
   if(step.kind==='magic'){const spell=step.spell;caption=`${spell.name} · posição ${laneSymbols[spell.lane]} · ${spell.positive?'efeito aliado':'efeito hostil'}`;const side=lanes[spell.lane]?.querySelector(`.lane-side[data-owner="${spell.targetSide}"]`);if(side){side.classList.add(spell.positive?'effect-positive':'effect-negative');side.dataset.effect=`${spell.positive?'+':'−'}${spell.amount||'efeito'}`;const target=side.querySelector('.card')||side;if(spell.op==='area_stat_buff'){animateBanquet(spell);}else if(['attack_modifier','stat_buff'].includes(spell.op)&&Number(spell.amount)>0){buffRise(target,spell.amount);deferVisual(()=>{applyHealthUpdates(spell.healthUpdates);for(const update of spell.healthUpdates||[])if(update.attack!==undefined)buffRise(tableCard(update.uid),0,update.attack);},500);}else if(['heal','choose_one'].includes(spell.op)){healPulse(target);deferVisual(()=>applyHealthUpdates(spell.healthUpdates),500);}else{fly(spell.op==='area_damage'?'✷':'➶',$(spell.casterId===seat()?.id?'self-head':'opponent-head'),target,'spell',()=>{impact(target,spell.positive);applyHealthUpdates(spell.healthUpdates);sound('impact',spell.amount||1);});}sound(spellSound(spell.name,['heal','choose_one'].includes(spell.op)?'heal':spell.op));setTimeout(()=>sound('grave'),1050);}}
  if(step.kind==='revelation'&&step.ability?.op==='damage_curse'){caption=`${step.ability.name} · Maldição pronta`;const source=tableCard(step.ability.sourceId);if(source)source.animate([{boxShadow:'0 0 0 transparent'},{boxShadow:'0 0 18px #a58cc0'},{boxShadow:'0 0 0 transparent'}],{duration:900});}
  else if(step.kind==='revelation'&&step.ability?.op==='adjacent_attack_buff'){caption=`${step.ability.name} · Casas fortalecidas`;for(const u of step.ability.healthUpdates||[]){const target=tableCard(u.uid);target?.closest('.lane-side')?.classList.add('lane-buffed');buffRise(target,3,u.attack);}deferVisual(()=>applyHealthUpdates(step.ability.healthUpdates),1100);}
  else if(step.kind==='revelation'&&step.ability){const ability=step.ability,source=tableCard(ability.sourceId),side=lanes[ability.lane]?.querySelector(`.lane-side[data-owner="${ability.targetSide}"]`),target=side?.querySelector('.card')||side;if(source&&target){const positive=ability.op==='attack_modifier'||ability.op==='heal';if(ability.op==='attack_modifier'&&ability.amount>0){const update=ability.healthUpdates?.find(u=>u.uid===target.dataset.uid);buffRise(target,ability.amount,update?.attack);}else if(ability.op==='heal')healPulse(target);else{fly('➶',source,target,'spell',()=>{impact(target,positive);applyHealthUpdates(ability.healthUpdates);sound('impact',ability.amount||1);});}sound(spellSound(ability.name,ability.op));}caption=`${ability.name} · Revelação · ${laneSymbols[ability.lane]}`;}
  if(step.kind==='growth'){for(const update of step.updates){buffRise(tableCard(update.uid),update.amount,update.attack);}deferVisual(()=>applyHealthUpdates(step.updates),1100);caption='CRESCIMENTO PERMANENTE';}if(step.kind==='strike'){animateDirectedStrike(step.strike);caption=step.strike.initiative?'INICIATIVA':'CONFRONTO';}if(step.kind==='clash'){const entry=battle.visual?.find(entry=>entry.lane===step.lane);if(entry)animateLaneClash(entry);caption=`Posição ${laneSymbols[step.lane]} · confronto da esquerda para a direita`; }if(step.kind==='result')animateCasualties(battle);
  lanes.forEach((lane,index)=>{if(!['clash','strike'].includes(step.kind)||index===step.lane)lane.classList.add(classes[step.kind]);});$('battle-banner').textContent={reveal:'FORMAÇÕES REVELADAS',magic:'MAGIA EM AÇÃO',revelation:'REVELAÇÃO',clash:'CONFRONTO',strike:'CONFRONTO',growth:'CRESCIMENTO',result:'RESULTADO'}[step.kind];$('battle-caption').textContent=caption;
}

let finaleKey='',finaleGeneration=0;
function scheduleFinale(){
 if(state?.phase!=='finished'){if(finaleKey){finaleGeneration++;document.querySelector('.capture-scene')?.remove();}finaleKey='';return;}
 if(!state.winner)return;const key=state.code+':'+state.round+':'+state.winner;if(finaleKey===key)return;finaleKey=key;const generation=++finaleGeneration,winner=state.players.find(p=>p.id===state.winner),loser=state.players.find(p=>p.id!==state.winner);
 visualQueue=visualQueue.then(()=>noticeQueue).then(()=>animateFinale(winner,loser,generation)).catch(err);
}
async function animateFinale(winner,loser,generation){
 if(generation!==finaleGeneration||state?.phase!=='finished')return;hideHover();$('target-picker').open&&$('target-picker').close();await warmSounds();
 const scene=document.createElement('div');scene.className='capture-scene';scene.setAttribute('role','dialog');scene.setAttribute('aria-label','Resultado da caçada');const stage=document.createElement('div');stage.className='capture-stage';scene.append(stage);const title=text(scene,'h2','O CONTRATO SE FECHA','capture-title');
 const makePortrait=p=>{const holder=document.createElement('div');holder.className='final-patron';const image=document.createElement('img');image.src=p.patron.image||'card-back.png';image.alt=p.patron.name;holder.append(image);text(holder,'strong',p.patron.name);return holder;};
 const portrait=makePortrait(loser);stage.append(portrait);document.body.append(scene);const valid=()=>generation===finaleGeneration&&scene.isConnected;
 const stars=document.createElement('div');stars.className='wanted-stars';stage.append(stars);
 for(let i=0;i<6;i++){if(!valid())return;const star=text(stars,'span','★','wanted-star');const angle=(-165+i*30)*Math.PI/180;star.style.left=(50+48*Math.cos(angle))+'%';star.style.top=(66+54*Math.sin(angle))+'%';sound('coin');await pause(220);}
 if(!valid())return;const sight=document.createElement('div');sight.className='capture-sight';portrait.append(sight);await pause(550);if(!valid())return;
 const barrel=document.createElement('div');barrel.className='capture-barrel';scene.append(barrel);sound('capture');await fly('•',barrel,portrait,'capture-bullet',()=>{portrait.classList.add('capture-hit');}).finished.catch(()=>{});if(!valid())return;
 const turn=portrait.animate([{transform:'rotateY(0deg)'},{transform:'rotateY(90deg)'}],{duration:260,fill:'forwards'});await turn.finished.catch(()=>{});portrait.replaceChildren();portrait.classList.add('captured-scroll');text(portrait,'strong','CAPTURADO');text(portrait,'span',loser.patron.name);turn.cancel();await portrait.animate([{transform:'rotateY(-90deg)'},{transform:'rotateY(0deg)'}],{duration:300}).finished.catch(()=>{});await pause(700);if(!valid())return;
 stars.remove();portrait.classList.remove('captured-scroll','capture-hit');portrait.replaceChildren();const jailedImage=document.createElement('img');jailedImage.src=loser.patron.image||'card-back.png';jailedImage.alt=loser.patron.name;portrait.append(jailedImage);text(portrait,'strong','CAPTURADO');portrait.classList.add('jailed-patron');title.textContent='RECOMPENSA CONQUISTADA';const champion=makePortrait(winner);champion.classList.add('champion');stage.append(champion);champion.animate([{transform:'scale(.35) translateY(70px)',opacity:0},{transform:'scale(1.12)',opacity:1},{transform:'scale(1)',opacity:1}],{duration:800,easing:'cubic-bezier(.2,.7,.25,1)'});
 for(let burst=0;burst<6;burst++){if(!valid())return;const firework=document.createElement('div');firework.className='victory-firework';firework.style.left=(burst%2?78:22)+'%';firework.style.top=(20+(burst%3)*25)+'%';scene.append(firework);for(let i=0;i<18;i++){const spark=document.createElement('i');spark.style.setProperty('--a',i*20+'deg');spark.style.setProperty('--color',['#ffc76c','#8be3c3','#ffe9ac'][burst%3]);firework.append(spark);}sound('magic');setTimeout(()=>firework.remove(),1700);await pause(280);}
 if(!valid())return;text(scene,'p',winner.name+' venceu a caçada.','capture-result');const done=button('Nova partida',()=>{selected=null;command({type:'reset'});},'primary');done.classList.add('capture-done');scene.append(done);done.focus();
}

function render(){resetVisualSession();recoverVisualGap();prepareOpeningArrivals();rememberSpellTargets();cleanupDrag();if(!state||!state.players.some(p=>[...(p.hand||[]),...(p.reserve||[])].some(c=>c.uid===hoverUid)))hideHover();renderGate();lastRevision=state?.revision??-1;if(!state){scheduleFinale();lastPhase=null;handOrder=[];pendingArrival=[];mulliganSelected.clear();return;}if(lastPhase==='resolving'&&state.phase!=='resolving')visualMessage('CONFRONTO ENCERRADO',state.phase==='finished'?'Partida concluída':'A próxima rodada começa',1250);if(lastPhase&&lastPhase!==state.phase&&state.phase==='formation')visualMessage('COMBATE INICIADO','Posicione suas criaturas em segredo',1500);if(lastPhase&&lastPhase!==state.phase&&state.phase==='mulligan')mulliganSelected.clear();lastPhase=state.phase;syncAttackDisplay();syncHealthDisplay();renderBoard();renderSelection();renderActions();renderMulliganOverlay();tickCombat();queueEvents();renderTargetLinks();scheduleAutomaticMulligan();promptEmanationTarget();promptDiscard();scheduleFinale();if(!seat()?.pendingDiscard&&!((state.phase==='prep'&&state.turn===state.you)||(state.phase==='formation'&&!seat()?.ready))){$('target-picker').open&&$('target-picker').close();}}
async function enter(mode){try{const name=$('player-name').value.trim();if(!name)throw Error('Informe seu nome.');const id=$('join-code').value.trim().toUpperCase();const role=isInvitation()?'auto':$('entry-role').value;const result=mode==='create'?await api('/api/create',{name,role,stake:document.getElementById('account-wager')?.value||''}):await api(`/api/rooms/${id}/join`,{name,role});sessionStorage.setItem('runamarca-nova-seat',JSON.stringify({code:result.code,token:result.token}));history.replaceState(null,'',`${gameBase}?room=${result.code}`);state=result.state;serverClockOffset=Date.now()-state.serverNow;render();}catch(e){err(e);}}
$('create').onclick=()=>enter('create');$('join').onclick=()=>enter('join');$('copy-link').onclick=async()=>{const link=`${location.origin}${gameBase}?room=${state.code}&invite=${state.inviteToken}`;try{await navigator.clipboard.writeText(link);err('Convite copiado. Quem receber o link entra sem código de acesso.');}catch{err(link);}};
$('add-bot').onclick=()=>command({type:'addBot',deckId:$('bot-deck').value});
$('leave-room').onclick=()=>command({type:'leave'});$('change-role').onclick=()=>command({type:state.spectator?'takeSeat':'spectate'});
$('close-detail').onclick=()=>$('card-detail').close();$('rules-toggle').onclick=()=>$('rules-dialog').showModal();$('close-rules').onclick=()=>$('rules-dialog').close();
$('close-cemetery').onclick=()=>$('cemetery-detail').close();
$('art-import').onchange=async event=>{try{const data=JSON.parse(await event.target.files[0].text());if(data.format!=='runamarca-prototipo-editor'||!Array.isArray(data.cards))throw Error('Exporte o projeto editável no novo criador de cartas.');let count=0;for(const card of data.cards){if(!card.starterDeck)continue;const deck=models.decks.find(d=>d.id===card.starterDeck);const model=[...deck?.cards||[],deck?.patron].find(c=>c?.name===card.name);if(model){(importedArt[deck.id]??={})[model.id]={...(card.art?{image:card.art,kind:'illustration',artZoom:card.artZoom,artX:card.artX,artY:card.artY}:{}),speech:String(card.speech||'').slice(0,160),narrative:String(card.narrative||'').slice(0,1200)};count++;}}$('art-message').textContent=`${count} carta(s) com artes e textos prontos. Escolha o deck depois de importar.`;}catch(e){err(e);}event.target.value='';};
const slug=name=>String(name).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
async function compactImage(file){const bitmap=await createImageBitmap(file);const scale=Math.min(1,900/bitmap.width,1260/bitmap.height);const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.92);}
$('art-files').onchange=async event=>{let count=0;try{for(const file of event.target.files){if(!['image/png','image/jpeg','image/webp'].includes(file.type))continue;const stem=slug(file.name.replace(/\.[^.]+$/,''));for(const deck of models.decks){const model=[...deck.cards,deck.patron].find(card=>slug(card.name)===stem);if(model){(importedArt[deck.id]??={})[model.id]={image:await compactImage(file),kind:'card'};count++;break;}}}$('art-message').textContent=`${count} imagem(ns) associada(s). Escolha o deck depois de importar. Os arquivos devem ter o nome da carta.`;}catch(e){err(e);}event.target.value='';};
async function init(){try{models=await (await fetch('cartas.json')).json();const room=new URLSearchParams(location.search).get('room');if(room)$('join-code').value=room.toUpperCase();const saved=sessionStorage.getItem('runamarca-nova-seat');if(room&&saved&&JSON.parse(saved).code!==room.toUpperCase())sessionStorage.removeItem('runamarca-nova-seat');await refresh();render();setInterval(refresh,500);setInterval(tickCombat,90);}catch(e){err(e);}}
init();

$('open-creator').onclick=()=>{const frame=$('creator-frame');if(!frame.getAttribute('src'))frame.src=gameBase+'criador/';$('creator-dialog').showModal();};$('close-creator').onclick=()=>$('creator-dialog').close();

$('close-target-picker').onclick=()=>$('target-picker').close();$('target-picker').addEventListener('close',()=>document.querySelectorAll('.target-highlight').forEach(n=>n.classList.remove('target-highlight')));
