const $=id=>document.getElementById(id);
const gameBase=location.pathname.startsWith('/runamarca')?'/runamarca/':'/';
let state=null,models=null,selected=null,importedArt={},lastRevision=-1,toastTimer=null,hoverUid=null,serverClockOffset=0,pendingSnap=null,refreshing=false;
let visualBooted=false,lastVisualId=0,lastPhase=null,lastBattleStep='',handOrder=[],mulliganSelected=new Set(),audioContext=null,pendingArrival=[],suppressClickUntil=0;let visualQueue=Promise.resolve();
const emanationChoices=new Map();let emanationChoiceTurn='';
const displayedAttack=new Map(),pendingAttack=new Map();let attackDisplayCombat=null;
function syncAttackDisplay(){const combat=state?.combat?.id||null;if(attackDisplayCombat!==combat){displayedAttack.clear();pendingAttack.clear();attackDisplayCombat=combat;}for(const p of state?.players||[])for(const card of p.reserve||[]){const value=Math.max(0,card.attack+(card.attackMod||0)),previous=displayedAttack.get(card.uid);if(!combat&&previous!==undefined&&value>previous&&(state.events||[]).some(e=>e.id>lastVisualId&&e.op==='attack_modifier'&&e.targetId===card.uid))pendingAttack.set(card.uid,value);if(!displayedAttack.has(card.uid)||(!combat&&!pendingAttack.has(card.uid)))displayedAttack.set(card.uid,value);}}
let commandBusy=false,activeDrag=null;const movingCards=new Set(),deadVisuals=new Map();
function tableCard(uid){return [...document.querySelectorAll('#game .card,#game .spell-mark,#mulligan-cards .card')].find(node=>node.dataset.uid===uid&&!node.closest('#visual-layer'));}
function cleanupDrag(){activeDrag?.();activeDrag=null;document.querySelectorAll('.drag-preview').forEach(node=>node.remove());document.querySelectorAll('.dragging-source,.drop-ready').forEach(node=>node.classList.remove('dragging-source','drop-ready'));}
window.addEventListener('blur',cleanupDrag);document.addEventListener('visibilitychange',()=>{if(document.hidden)cleanupDrag();});
const isInvitation=()=>new URLSearchParams(location.search).has('invite');
const laneSymbols=['☀','☽','✦'];
const avatar=(seat)=>seat?.patron?.affinity==='ruptura'?'◆':seat?.patron?.affinity==='fluxo'?'◇':'✦';
const seat=()=>state?.players.find(p=>p.id===state.you)||(state?.spectator?state?.players[0]:null);
const rival=()=>state?.players.find(p=>p.id!==seat()?.id);
const err=error=>{const message=error?.message||String(error);$('welcome-error').textContent=message;const t=$('toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3500);};
async function api(route,data,method='POST'){
  const headers={'Content-Type':'application/json'};const saved=sessionStorage.getItem('runamarca-nova-seat');if(saved)headers['x-player-token']=JSON.parse(saved).token;
  const response=await fetch(gameBase+route.replace(/^\//,''),{method,headers,...(data?{body:JSON.stringify(data)}:{})});if(response.status===204)return null;if(response.status===403){location.assign(gameBase+'access');throw Error('Acesso necessário.');}const result=await response.json();if(!response.ok)throw Error(result.error||'Ação não concluída.');return result;
}
function trackArrivals(previous,next){if(!previous||previous.you!==next.you||next.spectator)return;const before=new Set(previous.players.find(p=>p.id===previous.you)?.hand?.map(c=>c.uid)||[]);for(const card of next.players.find(p=>p.id===next.you)?.hand||[])if(!before.has(card.uid)&&!pendingArrival.includes(card.uid))pendingArrival.push(card.uid);}
async function command(data,dragRect=null){if(commandBusy)return;commandBusy=true;try{
 const movingId=data.cardId||(data.type==='assign'?seat()?.formation[data.lane]:null),source=tableCard(movingId);
 const transfer=source&&['play','assign','emanate','unprepare','movePrepared'].includes(data.type)?{uid:movingId,copy:source.cloneNode(true),rect:dragRect||source.getBoundingClientRect(),card:selectedCard()||seat()?.hand?.find(c=>c.uid===movingId)||seat()?.reserve?.find(c=>c.uid===movingId)}:null;const opening=data.type==='confirmMulligan'?[...$('mulligan-cards').querySelectorAll('.card')].map(node=>({uid:node.dataset.uid,copy:node.cloneNode(true),rect:node.getBoundingClientRect()})):null;const next=await api(`/api/rooms/${state.code}/act`,data);if(next.left){sessionStorage.removeItem('runamarca-nova-seat');state=null;selected=null;visualBooted=false;lastRevision=-1;history.replaceState(null,'',gameBase);render();return;}trackArrivals(state,next);serverClockOffset=Date.now()-next.serverNow;state=next;render();if(opening?.length)animateOpeningToHand(opening);if(transfer)animateTransfer(transfer);}catch(e){err(e);}finally{commandBusy=false;}}
async function refresh(){const saved=sessionStorage.getItem('runamarca-nova-seat');if(!saved||refreshing||commandBusy||activeDrag)return;refreshing=true;try{const info=JSON.parse(saved);const next=await api(`/api/rooms/${info.code}/state?revision=${lastRevision}`,null,'GET');if(!next)return;serverClockOffset=Date.now()-next.serverNow;if(next.revision>lastRevision||!state){trackArrivals(state,next);state=next;render();}}catch(e){sessionStorage.removeItem('runamarca-nova-seat');state=null;render();err(e);}finally{refreshing=false;}}
function button(label,handler,klass='',disabled=false){const b=document.createElement('button');b.type='button';b.textContent=label;b.className=klass;b.disabled=disabled;b.onclick=handler;return b;}
function text(parent,tag,value,klass){const el=document.createElement(tag);el.textContent=value;if(klass)el.className=klass;parent.append(el);return el;}
function manaAffinity(value){return ['ruptura','forja','fluxo'].includes(value)?value:'fluxo';}
function affordable(card){const p=seat();if(!p||state.spectator||state.phase!=='prep'||state.turn!==p.id||!p.hand?.some(c=>c.uid===card?.uid))return false;const sources=p.emanation.filter(uid=>p.reserve.find(c=>c.uid===uid)?.modelId==='M04').length;const cost=card.type!=='creature'&&sources&&!p.discountUsed&&!p.directPlayed?Math.max(1,card.cost-sources):card.cost;return p.mana>=cost;}
function cardEl(card,{mini=false,back=false,active=false}={}){
  const el=document.createElement('button');el.type='button';el.className=`card${mini?' mini':''}${back?' back':''}${active?' selected':''}${card?.imageKind==='card'?' has-art':''}`;el.dataset.uid=card?.uid||'';if(!back&&affordable(card))el.classList.add('payable');if(movingCards.has(card?.uid))el.style.visibility='hidden';if(card?.type==='creature'&&card.damage>0)el.classList.add('wounded');el.setAttribute('aria-label',back?'Magia oculta':`${card.name} · custo ${card.cost} · ${card.text||''}`);
  if(!back){if(card.image){const image=document.createElement('img');image.src=card.image;image.alt='';el.append(image);}else text(el,'div',card.type==='creature'?'✦':'◈','fallback');text(el,'div',card.name,'card-title');text(el,'span',String(card.cost??0),`mana-gem mana-${manaAffinity(card.affinity)}`);if(card.type==='creature'){const stats=text(el,'span','','numbers');text(stats,'span',String(displayedAttack.get(card.uid)??Math.max(0,card.attack+(card.attackMod||0))),'attack-value');text(stats,'span',` / ${Math.max(0,card.health-card.damage)}`);}if(card.rarity)text(el,'span',card.rarity,'rarity');if(card.damage)text(el,'span',`−${card.damage}`,'damage');}
  el.onclick=()=>{if(back||Date.now()<suppressClickUntil)return;if(state?.phase==='mulligan'&&seat()?.hand?.some(c=>c.uid===card.uid)){mulliganSelected.has(card.uid)?mulliganSelected.delete(card.uid):mulliganSelected.add(card.uid);render();return;}selected=card.uid;render();};el.ondblclick=null;
  if(!back){el.onmouseenter=event=>showHover(card,event);el.onmousemove=moveHover;el.onmouseleave=hideHover;}
  return el;
}
function showHover(card,event){const holder=$('hover-preview');if(hoverUid!==card.uid){hoverUid=card.uid;holder.replaceChildren();const picture=cardEl(card);picture.classList.add('big');picture.onclick=picture.ondblclick=picture.onmouseenter=picture.onmousemove=picture.onmouseleave=null;holder.append(picture);text(holder,'div',card.text||card.name,'hover-rule');}holder.hidden=false;moveHover(event);}
function moveHover(event){const holder=$('hover-preview');if(holder.hidden)return;const w=holder.offsetWidth||245,h=holder.offsetHeight||380;holder.style.left=`${Math.max(10,Math.min(innerWidth-w-10,event.clientX+(event.clientX>innerWidth*.68?-w-26:22)))}px`;holder.style.top=`${Math.max(70,Math.min(innerHeight-h-10,event.clientY-h*.38))}px`;}
function hideHover(){const holder=$('hover-preview');holder.hidden=true;hoverUid=null;}
function showCard(card){hideHover();const d=$('card-detail');const area=$('detail-content');area.replaceChildren();const picture=cardEl(card);picture.classList.add('big');picture.onclick=picture.ondblclick=picture.onmouseenter=picture.onmousemove=picture.onmouseleave=null;area.append(picture);const body=document.createElement('div');text(body,'h2',card.name);text(body,'p',card.type==='creature'?`Criatura · ${card.attack}/${card.health} · custo ${card.cost}`:`Magia · custo ${card.cost}`);text(body,'p',card.text||'Sem texto.');area.append(body);d.showModal();}
function selectedCard(){if(!state)return null;return [...(seat()?.hand||[]),...(seat()?.reserve||[]),...(rival()?.reserve||[]),...state.players.flatMap(p=>p.prepared.filter(item=>item.caster===state.you&&item.card).map(item=>item.card))].find(c=>c.uid===selected);}
function role(card){const ef=Array.isArray(card.effects)?card.effects[0]:card.effects;if(ef?.op==='draw')return 'self';if(ef?.op==='area_damage')return 'enemy-board';if(ef?.op==='choose_one')return 'friendly-or-patron';if(['heal','attack_modifier'].includes(ef?.op)&&ef?.target==='chosen_allied_creature')return 'friendly';return 'enemy';}
function matchSeat(player,position){if(!player)return;const self=position==='self';const node=$(`${position}-head`);node.replaceChildren();const portrait=document.createElement('div');portrait.className='patron-card';if(player.patron?.image){const image=document.createElement('img');image.src=player.patron.image;image.alt=`Retrato de ${player.patron.name}`;portrait.append(image);}else text(portrait,'span',avatar(player));portrait.title=player.patron?.name||'Patrono';portrait.onclick=()=>{if(player.patron)showPatron(player.patron);};node.append(portrait);const info=document.createElement('div');info.className='patron-info';text(info,'small',state.spectator?'PATRONO':self?'SEU PATRONO':'PATRONO RIVAL');text(info,'strong',player.patron?.name||'Patrono');text(info,'span',player.name,'muted');text(info,'span',`${player.deckCount} no deck · ${player.handCount} na mão`,'muted');node.append(info);const stats=document.createElement('div');stats.className='patron-stats';if(player.patron){const affinity=manaAffinity(player.patron.affinity);const mana=text(stats,'span','',`resource mana-resource mana-${affinity}`);const icon=document.createElement('img');icon.src=`energy-icons/${affinity}.png`;icon.alt='';mana.append(icon);text(mana,'span',`${player.mana}/${player.manaMax} ${affinity}`);text(stats,'span',`${player.patron.hp}/${player.patron.maxHp} ♥`,'hp');}node.append(stats);const deck=document.createElement('div');deck.id=position+'-deck';deck.className='deck-stack';deck.title='Baralho';const back=document.createElement('img');back.src='card-back.png';back.alt='Baralho de compra';deck.append(back);node.append(deck);}
function showPatron(patron){const d=$('card-detail'),area=$('detail-content');area.replaceChildren();const card=document.createElement('div');card.className='patron-large';if(patron.image){const image=document.createElement('img');image.src=patron.image;image.alt='';card.append(image);}text(card,'strong',patron.name);area.append(card);const body=document.createElement('div');text(body,'h2',patron.name);text(body,'p',`${patron.affinity.toUpperCase()} · ${patron.hp}/${patron.maxHp} de vida`);text(body,'p','Patrono do baralho. Começa em jogo e fica fora das 24 cartas.');area.append(body);d.showModal();}
function renderGate(){
  $('welcome').hidden=Boolean(state);$('lobby').hidden=!state||state.phase!=='lobby';$('mulligan-overlay').hidden=!state||state.phase!=='mulligan';$('game').hidden=!state;$('game').classList.toggle('is-obscured',Boolean(state&&['lobby','mulligan'].includes(state.phase)));
  $('room-name').textContent=state?`SALA ${state.code}`:'';$('spectators-game').hidden=!state;$('rules-toggle').hidden=!state;$('copy-link').hidden=!state;$('leave-room').hidden=!state;$('change-role').hidden=!state;$('change-role').textContent=state?.spectator?'Ocupar vaga':'Ir à arquibancada';$('change-role').disabled=Boolean(state?.spectator&&(state.phase!=='lobby'||state.players.length>=2));
  $('phase-label').textContent=state?`${({lobby:'SALA',coin:'MOEDA',mulligan:'MÃO INICIAL',prep:'PREPARAÇÃO',vote:'DECISÃO',formation:'FORMAÇÃO',resolving:'COMBATE',finished:'FIM'})[state.phase]||state.phase.toUpperCase()} · RODADA ${state.round}`:'';
  if(!state){$('entry-title').textContent=isInvitation()?'Entre na sala convidada':'Abra a mesa';$('entry-note').textContent=isInvitation()?'Informe seu nome. Se as duas vagas estiverem ocupadas, você entra na arquibancada.':'Jogue em duas abas ou convide outra pessoa para entrar na sala.';$('create').hidden=isInvitation();$('join').textContent=isInvitation()?'Entrar na sala':'Entrar com código';$('join-code-label').hidden=isInvitation();$('role-label').hidden=isInvitation();}
  if(!state)return;
  const crowd=`Arquibancada · ${state.spectators?.length||0}: ${state.spectators?.map(p=>p.name+(p.id===state.you?' (você)':'')).join(', ')||'ninguém'}`;$('spectators').textContent=crowd;$('spectators-game').textContent=crowd;
  if(state.phase==='lobby'){
    $('lobby-players').textContent=state.players.map(p=>`${p.name}${p.bot?' · bot fácil':''}${p.deckId?' ✓':''}`).join('  ·  ');
    $('lobby-note').textContent=state.spectator?'Você está assistindo. Ocupe uma vaga para escolher um deck.':state.players.length<2?'Escolha seu deck ou convide outra pessoa. Você também pode treinar contra o bot fácil.':state.players.every(p=>p.deckId)?'Os decks estão prontos.':'Cada jogador escolhe um deck.';
    const holder=$('deck-options');holder.replaceChildren();if(!state.spectator)for(const deck of models?.decks||[]){const box=document.createElement('article');box.className=`deck-option ${deck.affinity}`;const art=document.createElement('div');art.className='deck-art';const image=document.createElement('img');image.src=deck.cards.find(c=>c.type==='creature'&&c.image)?.image||'card-back.png';image.alt='';art.append(image);text(art,'span',deck.archetype,'deck-archetype');box.append(art);const content=document.createElement('div');content.className='deck-content';text(content,'span',deck.affinity.toUpperCase(),'affinity');text(content,'h2',deck.name);text(content,'p',deck.plan);text(content,'small',`PATRONO · ${deck.patron.name} · 24 CARTAS`);content.append(button(seat()?.deckId===deck.id?'Deck escolhido':'Escolher este deck',()=>command({type:'deck',deckId:deck.id,art:importedArt[deck.id]||{}}),'primary',Boolean(seat()?.deckId)));box.append(content);holder.append(box);}
    const botSetup=$('bot-setup');botSetup.hidden=state.spectator||state.players.length!==1;const select=$('bot-deck');if(!select.options.length)for(const deck of models?.decks||[]){const option=document.createElement('option');option.value=deck.id;option.textContent=`Bot: ${deck.name}`;select.append(option);}
  }
}
function renderMulliganOverlay(){if(state.phase!=='mulligan')return;const self=seat();const status=$('mulligan-status'),cards=$('mulligan-cards'),controls=$('mulligan-controls');cards.replaceChildren();controls.replaceChildren();if(state.spectator){status.textContent='Os jogadores estão escolhendo suas mãos iniciais.';return;}status.textContent=self.mulliganReady?'Mão confirmada. Aguardando o adversário.':`${state.first===self.id?'Você joga primeiro':'Você joga em segundo'} · ${self.mulligansLeft} troca(s) restante(s). Selecione individualmente as cartas que deseja devolver ao deck.`;if(self.mulliganReady)return;for(const card of self.hand||[]){const node=cardEl(card,{active:mulliganSelected.has(card.uid)});node.classList.add('opening-card');node.onmouseenter=node.onmousemove=node.onmouseleave=null;if(pendingArrival.includes(card.uid))node.classList.add('pending-arrival');cards.append(node);}controls.append(button(`Trocar ${mulliganSelected.size} carta(s)`,()=>{const cardIds=[...mulliganSelected];mulliganSelected.clear();command({type:'mulligan',cardIds});},'primary',!self.mulligansLeft||!mulliganSelected.size));controls.append(button('Manter e confirmar mão',()=>{mulliganSelected.clear();command({type:'confirmMulligan'});}));}
function renderBoard(){const self=seat()||{id:'',name:'Aguardando jogador',hand:[],reserve:[],discard:[],formation:[null,null,null],emanation:[],handCount:0,discardCount:0,deckCount:0,mana:0,manaMax:0},opp=rival();matchSeat(self,'self');matchSeat(opp,'opponent');
  for(const [id,p] of [['self',self],['opponent',opp]]){
    const holder=$(`${id}-reserve`);holder.replaceChildren();const cards=(p?.reserve||[]).filter(c=>!p.emanation?.includes(c.uid)&&!p.formation?.includes(c.uid));$(`${id}-reserve-count`).textContent=`${cards.length} criatura(s)`;
    for(const c of cards){const node=cardEl(c,{mini:true,active:selected===c.uid});if(!state.spectator&&p.id===self.id)makeDraggable(node,c);holder.append(node);}
    const eman=$(`${id}-emana`);eman.replaceChildren();for(let slot=0;slot<2;slot++){const em=p?.reserve?.find(c=>c.uid===p.emanation?.[slot]);if(em)eman.append(cardEl(em,{mini:true,active:selected===em.uid}));else text(eman,'span',`Vaga ${slot+1}`,'emana-empty');}
    const grave=$(`${id}-grave`);grave.replaceChildren();const top=p?.discard?.at(-1);if(top&&top.image){const art=document.createElement('img');art.src=top.image;art.alt='';grave.append(art);}else text(grave,'span','✝');text(grave,'b',`${p?.discardCount||0} carta(s)`);grave.onclick=()=>showCemetery(p);
  }
  const reserveDrop=$('self-reserve-area');reserveDrop.ondragover=event=>{if(state.phase==='formation'&&!self.ready){event.preventDefault();reserveDrop.classList.add('drop-ready');}};
  reserveDrop.ondragleave=event=>{if(!reserveDrop.contains(event.relatedTarget))reserveDrop.classList.remove('drop-ready');};
  reserveDrop.ondrop=event=>{reserveDrop.classList.remove('drop-ready');const uid=event.dataTransfer.getData('text/plain');const lane=self.formation.indexOf(uid);if(state.phase==='formation'&&!self.ready&&lane!==-1){event.preventDefault();command({type:'assign',lane,cardId:null});}};
  renderHand(self);
  const lanes=$('lanes');lanes.replaceChildren();for(let i=0;i<3;i++){
    const lane=document.createElement('div');lane.className='lane';lane.dataset.lane=i;lane.dataset.symbol=laneSymbols[i];lane.setAttribute('aria-label',`Posição ${laneSymbols[i]}`);
    for(const player of [opp,self]){
      const side=document.createElement('div');side.className='lane-side';side.dataset.owner=player?.id||'';side.dataset.lane=i;
      const placed=player?.reserve?.find(c=>c.uid===player.formation?.[i]);
      if(placed){const node=cardEl(placed,{mini:true,active:selected===placed.uid});if(!state.spectator&&player.id===self.id)makeDraggable(node,placed);if(player.id===self.id&&pendingSnap?.lane===i&&pendingSnap.until>Date.now())node.classList.add('snapping');side.append(node);}else{const secret=state.phase==='formation'&&player?.id!==state.you;text(side,'span',secret?'?':state.phase==='formation'&&player?.id===state.you?'Solte aqui':'Vazia',secret?'drop-label secret-alert':'drop-label');}
      for(const prep of player?.prepared?.filter(item=>item.lane===i)||[]){const symbol=document.createElement('span');symbol.className=`spell-mark ${prep.caster===player.id?'ally-spell':'trap-spell'}${prep.hidden?' hidden-spell':''}`;symbol.textContent=prep.hidden?'':'✧';symbol.title=prep.hidden?'Magia inimiga oculta':prep.card?.name||'Magia';if(prep.card){symbol.dataset.uid=prep.card.uid;if(movingCards.has(prep.card.uid))symbol.style.visibility='hidden';}
 symbol.onclick=()=>{if(prep.hidden||!prep.card||Date.now()<suppressClickUntil)return;if(prep.caster===state.you){selected=prep.card.uid;render();}else showCard(prep.card);};
 if(prep.caster===state.you&&((state.phase==='prep'&&state.turn===state.you)||(state.phase==='formation'&&!self.ready)))bindCardDrag(symbol,prep.card,'prepared');side.append(symbol);}
      if(!state.spectator&&player?.id){
        if(player.id===self.id)side.classList.add('own-drop');
        side.classList.add('spell-drop');
        side.ondragover=event=>{
          const uid=event.dataTransfer.getData('text/plain');
          const spell=self.hand?.find(card=>card.uid===uid&&card.type!=='creature');
          if((state.phase==='formation'&&player.id===self.id&&!self.ready)||(state.phase==='prep'&&state.turn===self.id&&spell)){event.preventDefault();side.classList.add('drop-ready');}
        };
        side.ondragleave=event=>{if(!side.contains(event.relatedTarget))side.classList.remove('drop-ready');};
        side.ondrop=event=>{
          event.preventDefault();side.classList.remove('drop-ready');const uid=event.dataTransfer.getData('text/plain');
          const spell=self.hand?.find(card=>card.uid===uid&&card.type!=='creature');
          if(spell&&state.phase==='prep')command({type:'play',cardId:uid,mode:'lane',lane:i,targetSide:player.id});
          else if(uid&&state.phase==='formation'&&player.id===self.id&&self.reserve.some(card=>card.uid===uid)){pendingSnap={lane:i,until:Date.now()+900};command({type:'assign',lane:i,cardId:uid});}
        };
      }
      lane.append(side);
    }
    lanes.append(lane);
  }
  const log=$('log');log.replaceChildren();let group=null;for(const item of state.log.slice(-10)){const entry=typeof item==='string'?{message:item,round:state.round,turn:null,phase:'lobby'}:item;const key=`${entry.round}:${entry.phase==='prep'?entry.turn:entry.phase}`;if(key!==group){const name=state.players.find(player=>player.id===entry.turn)?.name;const phase={vote:'Decisão',formation:'Formação',resolving:'Combate',finished:'Resultado',lobby:'Sala',coin:'Moeda',mulligan:'Mão inicial'}[entry.phase]||entry.phase;const title=entry.phase==='prep'&&name?`Rodada ${entry.round} · turno de ${name}`:`Rodada ${entry.round} · ${phase}`;text(log,'h4',title,'log-divider');group=key;}text(log,'p',entry.message,entry.actor===state.you?'log-own':entry.actor&&state.players.some(p=>p.id===entry.actor)?'log-rival':'log-neutral');}
}
function layoutHand(){const cards=[...$('hand').querySelectorAll('.hand-card')];cards.forEach((node,index)=>{node.style.setProperty('--fan-angle',`${(index-(cards.length-1)/2)*4.3}deg`);node.style.setProperty('--fan-rise',`${Math.abs(index-(cards.length-1)/2)*5}px`);node.style.zIndex=index+1;});}
function renderHand(self){const hand=$('hand');hand.replaceChildren();const current=state.phase==='mulligan'&&!self.mulliganReady?[]:self.hand||[];handOrder=handOrder.filter(uid=>current.some(c=>c.uid===uid));for(const card of current)if(!handOrder.includes(card.uid))handOrder.push(card.uid);for(const uid of handOrder){const card=current.find(c=>c.uid===uid);const node=cardEl(card,{active:selected===uid||mulliganSelected.has(uid)});node.classList.add('hand-card');if(pendingArrival.includes(uid))node.classList.add('pending-arrival');if(!state.spectator)bindLiveHandDrag(node,card);hand.append(node);}layoutHand();$('hand-count').textContent=`${self.handCount} cartas`;}
function bindCardDrag(node,card,kind='hand'){
 node.draggable=false;node.style.touchAction='none';node.classList.add('draggable');node.querySelectorAll('img').forEach(img=>img.draggable=false);
 node.onpointerdown=event=>{
  if(event.button!==0||commandBusy||state.phase==='mulligan')return;cleanupDrag();
  const origin={x:event.clientX,y:event.clientY};let ghost=null,timer;
  const clean=()=>{clearTimeout(timer);ghost?.remove();node.classList.remove('dragging-source');document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',release);document.removeEventListener('pointercancel',cancel);document.querySelectorAll('.drop-ready').forEach(el=>el.classList.remove('drop-ready'));activeDrag=null;};
  const cancel=()=>clean();
  const move=e=>{
   if(!ghost&&Math.hypot(e.clientX-origin.x,e.clientY-origin.y)<7)return;
   e.preventDefault();if(!ghost){hideHover();ghost=node.cloneNode(true);ghost.classList.remove('pending-arrival');ghost.classList.add('drag-preview');ghost.style.visibility='';$('visual-layer').append(ghost);node.classList.add('dragging-source');}
   ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';
   document.querySelectorAll('.drop-ready').forEach(el=>el.classList.remove('drop-ready'));
   const target=document.elementFromPoint(e.clientX,e.clientY),lane=target?.closest('.lane-side'),zone=target?.closest('#self-reserve-area,#self-emana-zone,#hand');
   if(lane||zone)(lane||zone).classList.add('drop-ready');
   const over=target?.closest('.hand-card');if(kind==='hand'&&over&&over!==node){const rect=over.getBoundingClientRect();$('hand').insertBefore(node,e.clientX>rect.left+rect.width/2?over.nextSibling:over);handOrder=[...$('hand').querySelectorAll('.hand-card')].map(el=>el.dataset.uid);layoutHand();}
  };
  const release=e=>{
   const moved=Boolean(ghost),rect=ghost?.getBoundingClientRect(),target=document.elementFromPoint(e.clientX,e.clientY),lane=target?.closest('.lane-side'),zone=target?.closest('#self-reserve-area,#self-emana-zone,#hand');clean();if(!moved)return;suppressClickUntil=Date.now()+450;selected=null;
   if(kind==='prepared'){
    if(lane)command({type:'movePrepared',cardId:card.uid,lane:Number(lane.dataset.lane),targetSide:lane.dataset.owner},rect);
    else if(zone)command({type:'unprepare',cardId:card.uid},rect);return;
   }
   if(kind==='hand'&&state.phase==='prep'&&state.turn===seat()?.id){
    if(card.type==='creature'&&zone&&zone.id!=='hand')command({type:'play',cardId:card.uid,...(zone.id==='self-emana-zone'?{mode:'emanate'}:{})},rect);
    else if(card.type!=='creature'&&lane)command({type:'play',cardId:card.uid,mode:'lane',lane:Number(lane.dataset.lane),targetSide:lane.dataset.owner},rect);
   }else if(kind==='reserve'&&state.phase==='formation'&&!seat().ready){
    if(lane?.dataset.owner===seat().id)command({type:'assign',cardId:card.uid,lane:Number(lane.dataset.lane)},rect);
    else if(zone?.id==='self-reserve-area'){const index=seat().formation.indexOf(card.uid);if(index!==-1)command({type:'assign',cardId:null,lane:index},rect);}
   }
  };
  activeDrag=clean;timer=setTimeout(clean,15000);document.addEventListener('pointermove',move,{passive:false});document.addEventListener('pointerup',release);document.addEventListener('pointercancel',cancel);
 };
}
function bindLiveHandDrag(node,card){bindCardDrag(node,card,'hand');}
function makeDraggable(node,card){if(state.phase==='formation'&&!seat().ready&&!seat().emanation.includes(card.uid))bindCardDrag(node,card,'reserve');}
function revealArrival(uid=pendingArrival[0]){if(!uid)return;pendingArrival=pendingArrival.filter(id=>id!==uid);for(const node of document.querySelectorAll('.card'))if(node.dataset.uid===uid){node.classList.remove('pending-arrival');node.classList.add('arrived');setTimeout(()=>node.classList.remove('arrived'),650);}}
function showCemetery(player){hideHover();const dialog=$('cemetery-detail'),area=$('cemetery-content');area.replaceChildren();text(area,'h2',`Nartvanyr · ${player.name}`);text(area,'p',`${player.discardCount} carta(s) consumida(s) ou derrotada(s). Clique numa carta para ler tudo.`);const row=document.createElement('div');row.className='cemetery-cards';for(const card of [...(player.discard||[])].reverse()){const node=cardEl(card);node.classList.add('cemetery-card');node.onmouseenter=node.onmousemove=node.onmouseleave=null;node.onclick=()=>showCard(card);row.append(node);}area.append(row);dialog.showModal();}
function makeSelect(options){const select=document.createElement('select');for(const [value,label] of options){const option=document.createElement('option');option.value=value;option.textContent=label;select.append(option);}return select;}
function renderSelection(){const panel=$('selection-panel');panel.replaceChildren();const card=selectedCard();panel.hidden=!card;if(!card)return;
  const actions=document.createElement('div');actions.className='buttons';
  if(state.spectator){panel.hidden=true;return;}
  const self=seat(),prepared=state.players.flatMap(p=>p.prepared).find(item=>item.caster===self.id&&item.card?.uid===card.uid),inHand=self.hand?.some(c=>c.uid===card.uid),inReserve=self.reserve?.some(c=>c.uid===card.uid);
  if(prepared&&((state.phase==='prep'&&state.turn===self.id)||(state.phase==='formation'&&!self.ready))){actions.append(button(prepared.refund?`Retirar magia · devolver ${prepared.refund} mana`:'Retirar magia · sem reembolso',()=>{command({type:'unprepare',cardId:card.uid});selected=null;}));text(actions,'span','Arraste a magia para outra posição ou de volta à mão.','muted');}
  if(state.phase==='prep'&&state.turn===self.id){
    if(inHand&&card.type==='creature'){
      actions.append(button(`Jogar criatura · ${card.cost} mana`,()=>{command({type:'play',cardId:card.uid});selected=null;},'primary',self.mana<card.cost));
      if(card.effects&&JSON.stringify(card.effects).includes('emanat'))actions.append(button(`Jogar direto em Emanação · ${card.cost} mana`,()=>{command({type:'play',cardId:card.uid,mode:'emanate'});selected=null;},'',self.mana<card.cost||self.emanation.length>=2));
    }
    if(inHand&&card.type!=='creature'){
      const kind=role(card);const allied=(self.reserve||[]).map(c=>[c.uid,`${c.name} (${c.health-c.damage} vida)`]);const targetOptions=kind==='self'||kind==='enemy-board'?[]:kind==='enemy'?(rival()?.reserve||[]).map(c=>[c.uid,`${c.name} (${c.health-c.damage} vida)`]):kind==='friendly-or-patron'?[['patron','Seu Patrono'],...allied]:allied;
      const target=makeSelect(targetOptions);if(kind!=='self'&&kind!=='enemy-board'){text(actions,'span','Alvo direto','muted');actions.append(target);}
      actions.append(button(`Usar agora · ${card.cost} mana`,()=>{command({type:'play',cardId:card.uid,mode:'direct',targetId:target.value});selected=null;},'primary',self.mana<card.cost||((kind==='enemy'||kind==='friendly')&&!targetOptions.length)));
      text(actions,'span','Para preparar no tabuleiro, arraste a magia da mão até uma posição aliada ou rival.','muted');
    }
    if(inReserve&&(self.emanation.includes(card.uid)||card.effects&&JSON.stringify(card.effects).includes('emanat'))){
      const leaving=self.emanation.includes(card.uid);
      actions.append(button(leaving?'Voltar à reserva · 1 mana':'Entrar em Emanação · 1 mana',()=>command({type:'emanate',cardId:card.uid}),'',self.mana<1||(!leaving&&self.emanation.length>=2)));
    }
  }
  if(state.phase==='formation'&&!self.ready&&inReserve&&!self.emanation.includes(card.uid)){text(actions,'span','Arraste esta carta da reserva até uma das três posições.','muted');const spots=document.createElement('div');spots.className='entry-buttons formation-fallback';for(let lane=0;lane<3;lane++)spots.append(button(String(lane+1),()=>command({type:'assign',lane,cardId:card.uid})));actions.append(spots);}
  panel.hidden=!actions.querySelector('button');if(!panel.hidden)panel.append(actions);
}
function renderActions(){const box=$('phase-actions');box.replaceChildren();const self=seat();if(!self)return;const choiceTurn=state.phase==='prep'&&state.turn===self.id&&!state.spectator?`${state.code}:${state.round}:${self.id}`:'';if(choiceTurn!==emanationChoiceTurn){emanationChoices.clear();emanationChoiceTurn=choiceTurn;}$('game').dataset.phase=state.phase;const message=$('match-status');
  const label=state.phase==='coin'?'Moeda lançada':state.phase==='mulligan'?'Escolha da mão inicial':state.phase==='prep'?state.turn===self.id?'Sua preparação':'Preparação rival':state.phase==='vote'?'Decisão de combate':state.phase==='formation'?'Formação secreta':state.phase==='resolving'?'Confronto em curso':state.phase==='finished'?'Partida encerrada':'Aguardando';
  message.textContent=state.phase==='prep'?'':label+` · rodada ${state.round}`;message.hidden=state.phase==='prep';
  if(state.spectator){text(box,'h3','Arquibancada');text(box,'p','Você acompanha a partida sem ver as mãos nem as formações secretas.');return;}
  if(state.phase==='coin'){
    text(box,'h3','O vencedor da moeda joga primeiro.');
  }else if(state.phase==='mulligan'){
    text(box,'h3','Mão inicial');text(box,'p','Escolha as cartas na janela central.');
  }else if(state.phase==='prep'){
    if(state.turn===self.id){const clerics=self.reserve.filter(c=>self.emanation.includes(c.uid)&&c.modelId==='F03');const choices=clerics.map((cleric,index)=>{const select=makeSelect([['','Sem cura'],...self.reserve.filter(c=>c.damage>0).map(c=>[c.uid,c.name])]);const saved=emanationChoices.get(cleric.uid)||'';select.value=[...select.options].some(option=>option.value===saved)?saved:'';emanationChoices.set(cleric.uid,select.value);select.onchange=()=>emanationChoices.set(cleric.uid,select.value);select.setAttribute('aria-label',`Cura da Clériga ${index+1}`);text(box,'span',`Cura da Clériga ${index+1}:`,'muted');box.append(select);return select;});
      box.append(button('Encerrar preparação',()=>command({type:'endPrep',healTargetIds:choices.map(select=>select.value)}),'primary'));}
  }else if(state.phase==='vote'){
    if(self.voted)text(box,'p','Você recusou. Aguardando a decisão rival.','status-pill');else{box.append(button('Começar combate',()=>command({type:'vote',fight:true}),'primary'));box.append(button('Não combater',()=>command({type:'vote',fight:false})));}
  }else if(state.phase==='formation'){
    text(box,'h3','Distribua suas criaturas');text(box,'p','Arraste da reserva às posições ou de volta para retirar.');
    if(self.ready)text(box,'p','Formação confirmada. Aguardando o rival.','status-pill');else box.append(button('Confirmar formação',()=>command({type:'ready'}),'primary'));
  }else if(state.phase==='resolving'){
    text(box,'h3','Confronto em andamento');text(box,'p','Acompanhe as magias, a Revelação e os choques nas três posições. O resultado será aplicado ao fim da animação.');
  }else if(state.phase==='finished'){
    text(box,'h3',state.winner?state.winner===self.id?'Você venceu!':`${rival().name} venceu!`:'Empate!');box.append(button('Nova partida',()=>{selected=null;command({type:'reset'});},'primary'));
  }
}
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const unlockAudio=()=>{try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();}catch{}};
document.addEventListener('pointerdown',unlockAudio,{once:true});document.addEventListener('keydown',unlockAudio,{once:true});
function visualMessage(title,caption='',duration=1050){const layer=$('visual-layer');const box=document.createElement('div');box.className='visual-message';text(box,'strong',title);if(caption)text(box,'span',caption);layer.append(box);setTimeout(()=>box.remove(),duration);}
const soundFiles={impactLow:['impactGeneric_light_000.ogg','impactGeneric_light_002.ogg'],impactMedium:['impactPunch_medium_000.ogg','impactPunch_medium_002.ogg'],impactHeavy:['impactPunch_heavy_000.ogg','impactPunch_heavy_002.ogg'],grave:['bookClose.ogg','dropLeather.ogg'],place:['bookPlace1.ogg','bookPlace2.ogg'],arrow:['knifeSlice.ogg','knifeSlice2.ogg'],gun:['chop.ogg'],heal:['impactBell_heavy_000.ogg'],burn:['cloth1.ogg'],coin:['handleCoins.ogg','handleCoins2.ogg'],draw:['bookFlip1.ogg','bookFlip2.ogg','bookFlip3.ogg'],magic:['impactGlass_light_000.ogg','impactBell_heavy_002.ogg']};
const soundBuffers=new Map();let soundLoading=null;
function warmSounds(){if(soundLoading)return soundLoading;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();soundLoading=Promise.all([...new Set(Object.values(soundFiles).flat())].map(async file=>{try{const response=await fetch(gameBase+'audio/'+file);if(!response.ok)return;const buffer=await audioContext.decodeAudioData(await response.arrayBuffer());soundBuffers.set(file,buffer);}catch{}}));return soundLoading;}catch{return Promise.resolve();}}
function sound(kind='magic',attack=0){const key=kind==='impact'?(attack<=3?'impactLow':attack<=6?'impactMedium':'impactHeavy'):kind;const files=soundFiles[key]||soundFiles.magic,file=files[Math.floor(Math.random()*files.length)];const play=()=>{try{const buffer=soundBuffers.get(file);if(!buffer)return;audioContext.resume();const source=audioContext.createBufferSource(),gain=audioContext.createGain();source.buffer=buffer;gain.gain.value=kind==='heal'?.18:kind==='impact'?.42:.3;source.connect(gain).connect(audioContext.destination);source.start();}catch{}};if(soundBuffers.has(file))play();else warmSounds().then(play);}
warmSounds();
function spellSound(name,op){return /flecha|arco|besta|seta/i.test(name)?'arrow':/tiro|disparo|cartucho|pistola/i.test(name)?'gun':op==='heal'||op==='attack_modifier'?'heal':'magic';}
function impact(target,positive=false){if(!target)return;if(target.matches('.patron-card')&&!positive){patronImpact(target);return;}const pos=center(target),ring=document.createElement('div');ring.className=`spell-impact${positive?' positive':''}`;ring.style.left=`${pos.x}px`;ring.style.top=`${pos.y}px`;$('visual-layer').append(ring);for(let i=0;i<12;i++){const spark=document.createElement('span');spark.style.setProperty('--angle',`${i*30}deg`);ring.append(spark);}setTimeout(()=>ring.remove(),1050);target.classList.add('visual-hit');setTimeout(()=>target.classList.remove('visual-hit'),800);}
function healPulse(target){if(!target)return;const p=center(target),aura=document.createElement('div');aura.className='healing-aura';Object.assign(aura.style,{left:p.x+'px',top:p.y+'px'});aura.textContent='✦';$('visual-layer').append(aura);setTimeout(()=>aura.remove(),1200);}
function buffRise(target,amount=1,attackAfter=null){if(!target)return;amount=Number(amount)||0;const card=target.matches('.card')?target:target.querySelector('.card'),uid=card?.dataset.uid,shown=displayedAttack.get(uid)??(Number(card?.querySelector('.attack-value')?.textContent)||0),combatId=state?.combat?.id||null;const r=target.getBoundingClientRect(),arrow=document.createElement('div');arrow.className='buff-rise';Object.assign(arrow.style,{left:(r.right+8)+'px',top:(r.top+r.height/2)+'px'});arrow.textContent=`↑ +${amount}`;$('visual-layer').append(arrow);setTimeout(()=>{arrow.remove();if(!uid||(state?.combat?.id||null)!==combatId)return;const value=attackAfter??pendingAttack.get(uid)??Math.max(0,shown+amount);displayedAttack.set(uid,value);if(value>=(pendingAttack.get(uid)??value))pendingAttack.delete(uid);for(const node of document.querySelectorAll('.card'))if(node.dataset.uid===uid){const number=node.querySelector('.attack-value');if(number){number.textContent=String(value);number.classList.remove('attack-increased');void number.offsetWidth;number.classList.add('attack-increased');}}},1100);}
function patronImpact(patron){if(!patron)return;const pos=center(patron),ring=document.createElement('div');ring.className='patron-impact-ring';Object.assign(ring.style,{left:pos.x+'px',top:pos.y+'px'});$('visual-layer').append(ring);setTimeout(()=>ring.remove(),450);patron.classList.remove('visual-hit');const direction=patron.closest('#self-head')?1:-1;patron.animate([{transform:'translateY(0)'},{transform:`translateY(${direction*10}px)`,offset:.35},{transform:'translateY(0)'}],{duration:300,easing:'ease-out'});const tint=document.createElement('div');tint.className='patron-red-flash';patron.append(tint);setTimeout(()=>tint.remove(),350);}
function speechBubble(event){const zone=$(event.zone==='emana'?(event.playerId===seat()?.id?'self-emana':'opponent-emana'):(event.playerId===seat()?.id?'self-reserve':'opponent-reserve'));const target=zone?.querySelector(`.card[data-uid="${event.cardId}"]`)||zone;if(!target)return;const box=document.createElement('div');box.className='speech-bubble';box.textContent=event.speech||'Estou a postos!';const pos=center(target);box.style.left=`${pos.x}px`;box.style.top=`${Math.max(60,pos.y-45)}px`;$('visual-layer').append(box);setTimeout(()=>box.remove(),2600);}
function center(node){const rect=node?.getBoundingClientRect();return rect?{x:rect.left+rect.width/2,y:rect.top+rect.height/2}:{x:innerWidth/2,y:innerHeight/2};}
function fly(symbol,from,to,kind='spell'){const start=center(from),end=center(to);const node=document.createElement('div');node.className=`flying-effect ${kind}`;node.textContent=symbol;node.style.left=`${start.x}px`;node.style.top=`${start.y}px`;$('visual-layer').append(node);const animation=node.animate([{transform:'translate(-50%,-50%) scale(.7)',opacity:0},{transform:'translate(-50%,-50%) scale(1.2)',opacity:1,offset:.18},{transform:`translate(calc(${end.x-start.x}px - 50%),calc(${end.y-start.y}px - 50%)) scale(.9)`,opacity:1,offset:.84},{transform:`translate(calc(${end.x-start.x}px - 50%),calc(${end.y-start.y}px - 50%)) scale(1.8)`,opacity:0}],{duration:900,easing:'ease-in-out'});animation.finished.finally(()=>{node.remove();if(!to?.matches('.patron-card')){to?.classList.add('visual-hit');setTimeout(()=>to?.classList.remove('visual-hit'),650);}});}
function weightOf(card){return Math.max(0,Math.min(1,((card?.attack||0)+(card?.health||0)-6)/14));}
function finishVisual(uid,copy){copy?.remove();movingCards.delete(uid);for(const node of document.querySelectorAll('#game .card,#game .spell-mark'))if(node.dataset.uid===uid)node.style.visibility=state?.phase==='resolving'&&state.combat?.casualties?.some(c=>c.uid===uid)?'hidden':'';}
async function safeFlight(copy,frames,options,uid){const animation=copy.animate(frames,options);try{await Promise.race([animation.finished.catch(()=>{}),pause((options.duration||1000)+(options.delay||0)+400)]);}finally{animation.cancel();finishVisual(uid,copy);}}
function visualCard(source){const rect=source.getBoundingClientRect(),copy=source.cloneNode(true);copy.classList.remove('hand-card','dragging-source','pending-arrival','selected','arrived','snapping','visual-hit');copy.classList.add('visual-card');Object.assign(copy.style,{left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px',visibility:'',transform:'none',animation:'none',margin:'0',transformOrigin:'center',transition:'none'});$('visual-layer').append(copy);movingCards.add(source.dataset.uid);source.style.visibility='hidden';return copy;}
function animateTransfer({uid,copy,rect,card}){
 const target=tableCard(uid)||[...document.querySelectorAll('#game .spell-mark')].find(n=>n.dataset.uid===uid);if(!target)return;
 const end=target.getBoundingClientRect(),weight=weightOf(card);copy.style.setProperty('animation','none','important');revealArrival(uid);movingCards.add(uid);target.style.visibility='hidden';copy.classList.remove('hand-card','dragging-source','pending-arrival','selected','arrived','snapping','visual-hit');copy.classList.add('visual-card');Object.assign(copy.style,{left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px',visibility:'',transform:'none',margin:'0',transformOrigin:'center',transition:'none'});$('visual-layer').append(copy);
 const dx=end.left+end.width/2-rect.left-rect.width/2,dy=end.top+end.height/2-rect.top-rect.height/2,scale=end.width/rect.width;
 const duration=620+weight*260;setTimeout(()=>sound('place',weight),duration*.8);
 safeFlight(copy,[{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${dx*.88}px,${dy*.88}px) scale(${scale*1.08})`,offset:.8},{transform:`translate(${dx}px,${dy}px) scale(${scale})`,opacity:1}],{duration,easing:'cubic-bezier(.22,.65,.22,1)',fill:'forwards'},uid).then(()=>{target.animate([{transform:'scale(1.07)'},{transform:'scale(1)'}],{duration:220+weight*150});});
}
function animateOpeningToHand(cards){visualMessage('MÃO CONFIRMADA','As cartas seguem para sua mão',1100);cards.forEach((item,index)=>setTimeout(()=>animateTransfer(item),index*90));}
async function animateDraw(uid,mine=true){
 const target=mine?(state?.phase==='mulligan'&&!seat()?.mulliganReady?[...$('mulligan-cards').querySelectorAll('.card')].find(n=>n.dataset.uid===uid):tableCard(uid)):$('opponent-head');if(!target){if(mine)revealArrival(uid);return;}
 const from=center($(mine?'self-deck':'opponent-deck')),to=center(target),card=seat()?.hand?.find(c=>c.uid===uid),copy=mine&&card?cardEl(card):document.createElement('div');copy.classList.add('card');copy.classList.remove('pending-arrival');copy.classList.add('draw-flight');copy.style.left=(from.x-42)+'px';copy.style.top=(from.y-58)+'px';copy.style.width='84px';copy.style.height='116px';copy.style.visibility='';const front=copy.innerHTML;copy.innerHTML='';copy.classList.add('back');$('visual-layer').append(copy);const dx=to.x-from.x,dy=to.y-from.y;
 const flip=mine?'90deg':'0deg';const anim=copy.animate([{transform:'translate(0,0) rotateY(0deg) scale(.7)',opacity:0},{transform:`translate(${dx*.4}px,${dy*.4}px) rotateY(${flip}) scale(1)`,opacity:1,offset:.45},{transform:`translate(${dx}px,${dy}px) rotateY(0deg) scale(${mine?target.getBoundingClientRect().width/84:.7})`,opacity:1}],{duration:630,easing:'cubic-bezier(.25,.1,.25,1)',fill:'forwards'});sound('draw');
 setTimeout(()=>{if(mine){copy.classList.remove('back');copy.innerHTML=front;}},285);
 try{await Promise.race([anim.finished,pause(1050)]);}catch{}finally{copy.remove();if(mine)revealArrival(uid);}
}
async function animateLaneClash(entry){
 for(const card of entry.cards.filter(Boolean)){displayedAttack.set(card.uid,card.attack);const number=tableCard(card.uid)?.querySelector('.attack-value');if(number)number.textContent=String(card.attack);}
 const [left,right]=entry.cards,parts=entry.cards.map(card=>card?document.querySelector(`.lane[data-lane="${entry.lane}"] .card[data-uid="${card.uid}"]`):null);if(!parts.some(Boolean))return;
 const weight=Math.max(...entry.cards.filter(Boolean).map(weightOf));const attackStrength=Math.max(...entry.cards.filter(Boolean).map(c=>c.attack||0));
 if(left&&right&&parts.every(Boolean)){
  const a=center(parts[0]),b=center(parts[1]),dx=(b.x-a.x)*.46,dy=(b.y-a.y)*.46,copies=parts.map(visualCard),duration=1350+weight*350;
  const animations=copies.map((copy,i)=>copy.animate([{transform:'translate(0,0)'},{transform:`translate(${i?-dx:dx}px,${i?-dy:dy}px) scale(${1+weight*.07})`,offset:.5},{transform:'translate(0,0)'}],{duration,easing:'cubic-bezier(.4,0,.25,1)'}));
  setTimeout(()=>{parts.forEach(node=>impact(node));sound('impact',attackStrength);},duration*.5);
  await Promise.all(animations.map(a=>a.finished.catch(()=>{})));
  copies.forEach((copy,i)=>{if(entry.cards[1-i].attack>=entry.cards[i].health){copy.classList.add('visual-dead');deadVisuals.set(entry.cards[i].uid,{copy,owner:entry.cards[i].owner});}else finishVisual(entry.cards[i].uid,copy);});return;
 }
 const card=left||right,source=parts[left?0:1],patron=$(card.owner===seat()?.id?'opponent-head':'self-head')?.querySelector('.patron-card');if(!source||!patron)return;
 const copy=visualCard(source),from=center(source),to=center(patron),duration=1550+weight*350;
 setTimeout(()=>{patronImpact(patron);sound('impact',attackStrength);},duration*.5);
 await safeFlight(copy,[{transform:'translate(0,0)'},{transform:`translate(${to.x-from.x}px,${to.y-from.y}px) scale(${1.05+weight*.08})`,offset:.5},{transform:'translate(0,0)'}],{duration,easing:'ease-in-out'},card.uid);

}
function animateCasualties(battle){
 for(const card of battle.casualties||[]){let record=deadVisuals.get(card.uid);if(!record){const source=tableCard(card.uid);if(!source)continue;record={copy:visualCard(source),owner:card.owner};record.copy.classList.add('visual-dead');}const {copy}=record,from=center(copy),to=center($(card.owner===seat()?.id?'self-grave':'opponent-grave'));
 sound('grave');safeFlight(copy,[{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${to.x-from.x}px,${to.y-from.y}px) scale(.35)`,opacity:0}],{duration:850,easing:'ease-in',fill:'forwards'},card.uid);deadVisuals.delete(card.uid);}
}
async function animateEvent(event){const player=state?.players.find(p=>p.id===event.playerId);const mine=player?.id===seat()?.id;const from=$(mine?'self-head':'opponent-head');const target=event.targetPatronId?$(event.targetPatronId===seat()?.id?'self-head':'opponent-head')?.querySelector('.patron-card'):event.targetId?tableCard(event.targetId):null;
   if(event.type==='coin'){$('mulligan-overlay').classList.add('coin-pending');sound('coin');visualMessage('A MOEDA DECIDIU',`${player?.name||'Jogador'} joga primeiro`,1900);const coin=document.createElement('div');coin.className='coin-toss';coin.textContent='✦';$('visual-layer').append(coin);setTimeout(()=>coin.remove(),1900);await pause(1900);$('mulligan-overlay').classList.remove('coin-pending');}
   else if(event.type==='first'){visualMessage('ORDEM DEFINIDA',`${player?.name||'Jogador'} joga primeiro`,1500);await pause(1250);}
   else if(event.type==='opening'){if(mine){visualMessage('MÃO INICIAL','Você recebe cinco cartas',1900);const ids=[...(seat()?.hand||[])].map(c=>c.uid);for(const uid of ids){await animateDraw(uid,true);}}}
   else if(event.type==='mulligan'){visualMessage('TROCA INICIAL',`${player?.name||'Jogador'} troca ${event.count} carta(s)`,950);await pause(600);}
   else if(event.type==='turn'){visualMessage('INÍCIO DE TURNO',`${player?.name||'Jogador'} · rodada ${event.round}`,1150);await pause(1050);}
   else if(event.type==='draw'){await animateDraw(event.cardId||pendingArrival[0],mine);}
   else if(event.type==='burn'){visualMessage('CARTA QUEIMADA',`Mão cheia: ${event.name||'uma carta'} foi para o Nartvanyr`,1700);$('hand').classList.add('hand-burn');setTimeout(()=>$('hand').classList.remove('hand-burn'),1000);fly('▰',from,$(mine?'self-grave':'opponent-grave'),'burn');sound('burn');await pause(1550);}
   else if(event.type==='spell'){visualMessage(event.name,event.op==='area_damage'?'Dano em área':event.op==='heal'?'Cura':event.op==='attack_modifier'?'Aprimoramento':'Magia resolvida',1600);const destination=target||$('lanes');if(['heal','choose_one'].includes(event.op))healPulse(destination);else if(event.op==='attack_modifier'&&event.amount>0)buffRise(destination,event.amount,event.attackAfter??null);else{fly(event.op==='draw'?'▰':event.op==='area_damage'?'✷':'➶',from,destination,'spell');setTimeout(()=>impact(destination),700);}sound(spellSound(event.name,event.op==='choose_one'?'heal':event.op));await pause(1500);sound('grave');}
   else if(event.type==='creature'){if(!mine){const card=player?.reserve?.find(c=>c.uid===event.cardId),source=$(mine?'self-deck':'opponent-deck');if(card&&source)animateTransfer({uid:card.uid,card,copy:cardEl(card),rect:source.getBoundingClientRect()});}await pause(750);speechBubble(event);}
  else if(event.type==='summon'){visualMessage('CONVOCAÇÃO',event.name,950);fly('✦',from,$(mine?'self-reserve':'opponent-reserve'),'positive');await pause(900);speechBubble(event);}
   else if(event.type==='expire'){sound('grave');fly('✧',from,$(mine?'self-grave':'opponent-grave'),'spell');await pause(500);}
}
function queueEvents(){const events=state?.events||[];const newest=events.at(-1)?.id||0;if(!visualBooted){lastVisualId=newest;visualBooted=true;return;}for(const event of events.filter(x=>x.id>lastVisualId)){visualQueue=visualQueue.then(()=>animateEvent(event)).catch(()=>{});}lastVisualId=newest;}
function tickCombat(){
  const overlay=$('battle-overlay');if(!state?.combat||state.phase!=='resolving'){overlay.hidden=true;lastBattleStep='';for(const [uid,{copy}] of deadVisuals)finishVisual(uid,copy);deadVisuals.clear();return;}
  const battle=state.combat,elapsed=Math.max(0,Date.now()-serverClockOffset-battle.startedAt);let remaining=elapsed,index=0;for(;index<battle.timeline.length-1&&remaining>=battle.timeline[index].duration;index++)remaining-=battle.timeline[index].duration;
  const key=`${battle.id}:${index}`;if(key===lastBattleStep)return;lastBattleStep=key;overlay.hidden=false;
  const step=battle.timeline[index],lanes=[...document.querySelectorAll('.lane')];for(const lane of lanes){lane.classList.remove('battle-reveal','battle-magic','battle-revelation','battle-clash','battle-aftermath');for(const side of lane.querySelectorAll('.lane-side')){side.classList.remove('effect-positive','effect-negative');delete side.dataset.effect;}}
  if(step.kind==='reveal'){for(const p of state.players){const bonus=p.emanation.filter(uid=>p.reserve.find(c=>c.uid===uid)?.modelId==='R05').length;if(bonus){const target=tableCard(p.formation[0]);if(target)buffRise(target,bonus);}}}
  const classes={reveal:'battle-reveal',magic:'battle-magic',revelation:'battle-revelation',clash:'battle-clash',result:'battle-aftermath'};
  let caption={reveal:'As formações deixam de ser segredo.',revelation:'Habilidades de Revelação entram em ação.',clash:'Criaturas se chocam; posições vazias expõem o Patrono.',result:'O resultado está sendo aplicado.'}[step.kind]||'';
   if(step.kind==='magic'){const spell=step.spell;caption=`${spell.name} · posição ${laneSymbols[spell.lane]} · ${spell.positive?'efeito aliado':'efeito hostil'}`;const side=lanes[spell.lane]?.querySelector(`.lane-side[data-owner="${spell.targetSide}"]`);if(side){side.classList.add(spell.positive?'effect-positive':'effect-negative');side.dataset.effect=`${spell.positive?'+':'−'}${spell.amount||'efeito'}`;const target=side.querySelector('.card')||side;if(spell.op==='attack_modifier'&&Number(spell.amount)>0)buffRise(target,spell.amount);else if(['heal','choose_one'].includes(spell.op))healPulse(target);else{fly(spell.op==='area_damage'?'✷':'➶',$(spell.casterId===seat()?.id?'self-head':'opponent-head'),target,'spell');setTimeout(()=>impact(target,spell.positive),650);}sound(spellSound(spell.name,['heal','choose_one'].includes(spell.op)?'heal':spell.op));setTimeout(()=>sound('grave'),1050);}}
  if(step.kind==='revelation'&&step.ability){const ability=step.ability,source=tableCard(ability.sourceId),side=lanes[ability.lane]?.querySelector(`.lane-side[data-owner="${ability.targetSide}"]`),target=side?.querySelector('.card')||side;if(source&&target){const positive=ability.op==='attack_modifier'||ability.op==='heal';if(ability.op==='attack_modifier'&&ability.amount>0)buffRise(target,ability.amount);else if(ability.op==='heal')healPulse(target);else{fly('➶',source,target,'spell');setTimeout(()=>impact(target,positive),650);}sound(spellSound(ability.name,ability.op));}caption=`${ability.name} · Revelação · ${laneSymbols[ability.lane]}`;}
  if(step.kind==='clash'){const entry=battle.visual?.find(entry=>entry.lane===step.lane);if(entry)animateLaneClash(entry);caption=`Posição ${laneSymbols[step.lane]} · confronto da esquerda para a direita`; }if(step.kind==='result')animateCasualties(battle);
  lanes.forEach((lane,index)=>{if(step.kind!=='clash'||index===step.lane)lane.classList.add(classes[step.kind]);});$('battle-banner').textContent={reveal:'FORMAÇÕES REVELADAS',magic:'MAGIA EM AÇÃO',revelation:'REVELAÇÃO',clash:'CONFRONTO',result:'RESULTADO'}[step.kind];$('battle-caption').textContent=caption;
}
function render(){cleanupDrag();hideHover();renderGate();lastRevision=state?.revision??-1;if(!state){lastPhase=null;handOrder=[];pendingArrival=[];mulliganSelected.clear();return;}if(lastPhase==='resolving'&&state.phase!=='resolving')visualMessage('CONFRONTO ENCERRADO',state.phase==='finished'?'Partida concluída':'A próxima rodada começa',1250);if(lastPhase&&lastPhase!==state.phase&&state.phase==='formation')visualMessage('COMBATE INICIADO','Posicione suas criaturas em segredo',1500);if(lastPhase&&lastPhase!==state.phase&&state.phase==='mulligan')mulliganSelected.clear();lastPhase=state.phase;syncAttackDisplay();renderBoard();renderSelection();renderActions();renderMulliganOverlay();tickCombat();queueEvents();}
async function enter(mode){try{const name=$('player-name').value.trim();if(!name)throw Error('Informe seu nome.');const id=$('join-code').value.trim().toUpperCase();const role=isInvitation()?'auto':$('entry-role').value;const result=mode==='create'?await api('/api/create',{name,role,stake:document.getElementById('account-wager')?.value||''}):await api(`/api/rooms/${id}/join`,{name,role});sessionStorage.setItem('runamarca-nova-seat',JSON.stringify({code:result.code,token:result.token}));history.replaceState(null,'',`${gameBase}?room=${result.code}`);state=result.state;serverClockOffset=Date.now()-state.serverNow;render();}catch(e){err(e);}}
$('create').onclick=()=>enter('create');$('join').onclick=()=>enter('join');$('copy-link').onclick=async()=>{const link=`${location.origin}${gameBase}?room=${state.code}&invite=${state.inviteToken}`;try{await navigator.clipboard.writeText(link);err('Convite copiado. Quem receber o link entra sem código de acesso.');}catch{err(link);}};
$('add-bot').onclick=()=>command({type:'addBot',deckId:$('bot-deck').value});
$('leave-room').onclick=()=>command({type:'leave'});$('change-role').onclick=()=>command({type:state.spectator?'takeSeat':'spectate'});
$('close-detail').onclick=()=>$('card-detail').close();$('rules-toggle').onclick=()=>$('rules-dialog').showModal();$('close-rules').onclick=()=>$('rules-dialog').close();
$('close-cemetery').onclick=()=>$('cemetery-detail').close();
$('art-import').onchange=async event=>{try{const data=JSON.parse(await event.target.files[0].text());if(data.format!=='runamarca-prototipo-editor'||!Array.isArray(data.cards))throw Error('Exporte o projeto editável no novo criador de cartas.');let count=0;for(const card of data.cards){if(!card.art||!card.starterDeck)continue;const deck=models.decks.find(d=>d.id===card.starterDeck);const model=[...deck?.cards||[],deck?.patron].find(c=>c?.name===card.name);if(model){(importedArt[deck.id]??={})[model.id]={image:card.art,kind:'illustration'};count++;}}$('art-message').textContent=`${count} ilustração(ões) pronta(s). Escolha o deck depois de importar.`;}catch(e){err(e);}event.target.value='';};
const slug=name=>String(name).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
async function compactImage(file){const bitmap=await createImageBitmap(file);const scale=Math.min(1,900/bitmap.width,1260/bitmap.height);const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.74);}
$('art-files').onchange=async event=>{let count=0;try{for(const file of event.target.files){if(!['image/png','image/jpeg','image/webp'].includes(file.type))continue;const stem=slug(file.name.replace(/\.[^.]+$/,''));for(const deck of models.decks){const model=[...deck.cards,deck.patron].find(card=>slug(card.name)===stem);if(model){(importedArt[deck.id]??={})[model.id]={image:await compactImage(file),kind:'card'};count++;break;}}}$('art-message').textContent=`${count} imagem(ns) associada(s). Escolha o deck depois de importar. Os arquivos devem ter o nome da carta.`;}catch(e){err(e);}event.target.value='';};
async function init(){try{models=await (await fetch('cartas.json')).json();const room=new URLSearchParams(location.search).get('room');if(room)$('join-code').value=room.toUpperCase();const saved=sessionStorage.getItem('runamarca-nova-seat');if(room&&saved&&JSON.parse(saved).code!==room.toUpperCase())sessionStorage.removeItem('runamarca-nova-seat');await refresh();render();setInterval(refresh,500);setInterval(tickCombat,90);}catch(e){err(e);}}
init();

$('open-creator').onclick=()=>{const frame=$('creator-frame');if(!frame.getAttribute('src'))frame.src=gameBase+'criador/';$('creator-dialog').showModal();};$('close-creator').onclick=()=>$('creator-dialog').close();
