/* Interactive gallery: production renderers/effects, no game or balance changes. */
const $=id=>document.getElementById(id);let audioContext=null,visualGeneration=0;
const state={code:'GALLERY',matchId:'preview',round:1},seat=()=>({id:'self'}),pause=ms=>new Promise(r=>setTimeout(r,ms));
async function settleAnimation(a){try{await a.finished;}catch{}}
function animationCue(a,fraction,fn){const frame=()=>{if(a.playState==='idle')return;if(Number(a.currentTime)>=Number(a.effect.getTiming().duration)*fraction)fn();else requestAnimationFrame(frame);};requestAnimationFrame(frame);}
const sound=()=>{},impact=()=>{};
async function unlock(){audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state!=='running')await audioContext.resume();}
const catalogue=fetch('cartas.json').then(r=>r.json());let examples={};
async function card(model,container,uid){const n=document.createElement('div');n.className='demo-card';n.dataset.uid=uid;const canvas=document.createElement('canvas');canvas.width=900;canvas.height=820;n.append(canvas);container.append(n);await RunaCardVisual.drawCombat(canvas,{art:model.image,themeEnergy:model.affinity,rarity:model.rarity},{assets:'criador/'});const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 900 820');svg.classList.add('card-stats-svg');for(const [x,y,value] of [[83,739,model.attack],[826,744,model.health]]){const t=document.createElementNS(svg.namespaceURI,'text');t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('text-anchor','middle');t.setAttribute('dominant-baseline','central');t.textContent=value;svg.append(t);}n.append(svg);return n;}
const tableCard=uid=>document.querySelector('.demo-card[data-uid="'+uid+'"]');
(async()=>{const cat=await catalogue,models=cat.decks.flatMap(d=>d.cards),get=id=>models.find(c=>c.id===id);$('power-image').src=cat.decks.find(d=>d.affinity==='forja').patron.powers[0].image;examples.ally=await card(get('RG02'),$('ally'),'axe-source');examples.target=await card(get('FL12'),$('target'),'victim');examples.neighbor=await card(get('FL03')||get('FL01'),$('neighbor'),'neighbor');for(let count=0;count<=4;count++){const figure=document.createElement('figure');$('stacks').append(figure);await card(get('RG13'),figure,'retal-'+count);paintRetaliation('retal-'+count,count);const label=document.createElement('figcaption');label.textContent=count+' / 4';figure.append(label);}})().catch(e=>{$('result').textContent='Não foi possível carregar a galeria: '+e.message;});
const self=()=>$('self-head').querySelector('.patron-card'),enemy=()=>$('opponent-head').querySelector('.patron-card');
async function effect(kind,from,to,donor){return RunaDamageFX.play({kind,from,to,donor,getGeneration:()=>visualGeneration,onHit:()=>{$('result').textContent='Impacto · '+({shard:'1 de dano',fulgor:'6 de dano',forge:'ataque da criatura aliada',axe:'1 de dano',ember:'1 de dano',kinetic:'reverberação',cone:'dano excedente',brutal:'dano ao portador',heavy:'impacto pesado'}[kind]||'Forja');}});}
const actions=[['Estilhaço Elétrico',()=>effect('shard',self(),examples.target)],['Fulgor Final',()=>effect('fulgor',self(),enemy())],['Disparo da Forja',()=>effect('forge',self(),examples.target,examples.ally)],['Incursora · machado',()=>effect('axe',examples.ally,examples.target)],['Crias · Último Suspiro',()=>effect('ember',examples.ally,enemy())],['Impacto pesado',()=>effect('heavy',examples.target,examples.target)],['Cataclisma',async()=>{await effect('heavy',examples.target,examples.target);await effect('kinetic',examples.target,examples.neighbor);}],['Transpassar',()=>effect('cone',examples.target,enemy())],['Lâmina Brutal',()=>effect('brutal',examples.ally,examples.ally)],['Martelo e poder virado',async()=>{const b=$('self-head').querySelector('button');b.classList.remove('used-power');await playForgeHammer('self','forjar-armadura');b.classList.add('used-power');await settleAnimation(b.querySelector('.power-cost').animate([{transform:'rotateX(0deg)'},{transform:'rotateX(180deg)'}],{duration:650}));}]];
let busy=false;async function run(fn,label){if(busy)return;busy=true;document.querySelectorAll('#controls button,#retaliation-test').forEach(b=>b.disabled=true);try{await unlock();$('result').textContent=label;await fn();}catch(e){$('result').textContent=e.message;}finally{busy=false;document.querySelectorAll('#controls button,#retaliation-test').forEach(b=>b.disabled=false);}}
for(const [label,fn] of actions){const b=document.createElement('button');b.textContent=label;b.onclick=()=>run(fn,label);$('controls').append(b);}
$('retaliation-test').onclick=()=>run(async()=>{for(let i=0;i<=4;i++){paintRetaliation('retal-0',i);await pause(550);}applyRetaliationUpdates([{sourceId:'retal-0',count:4,threshold:4,targetOwner:'opponent',damage:1}]);await pause(1700);},'Retaliação · acumulando');

const center=RunaDamageFX.point,deferVisual=(fn,delay)=>setTimeout(fn,delay),patronImpact=()=>{},damagePatron=()=>{$('result').textContent='Retaliação · 1 de dano ao Patrono';};
function fly(symbol,from,to,kind='spell',onHit=null){const start=center(from),end=center(to),node=document.createElement('div');node.className=`flying-effect ${kind}`;node.textContent=symbol;node.style.left=`${start.x}px`;node.style.top=`${start.y}px`;(kind==='capture-bullet'?document.querySelector('.capture-scene'):$('visual-layer')).append(node);const animation=node.animate([{transform:'translate(-50%,-50%) scale(.7)',opacity:0},{transform:'translate(-50%,-50%) scale(1.2)',opacity:1,offset:.18},{transform:`translate(calc(${end.x-start.x}px - 50%),calc(${end.y-start.y}px - 50%)) scale(.9)`,opacity:1,offset:.84},{transform:`translate(calc(${end.x-start.x}px - 50%),calc(${end.y-start.y}px - 50%)) scale(1.8)`,opacity:0}],{duration:900,easing:'ease-in-out'});if(onHit)animationCue(animation,.84,onHit);animation.finished.catch(()=>{}).finally(()=>node.remove());return animation;}
