// Heavy forging impact: local click immediately, public effect on confirmed use.
const locallyHammeredPowers=new Set();
function hammerKey(owner,powerId){return [state?.code,state?.matchId,state?.round,owner,powerId].join(':');}
async function playForgeHammer(owner,powerId,{localClick=false}={}){
 if(localClick){locallyHammeredPowers.add(hammerKey(owner,powerId));if(locallyHammeredPowers.size>128)locallyHammeredPowers.delete(locallyHammeredPowers.values().next().value);}
 const head=$(owner===seat()?.id?'self-head':'opponent-head'),index=powerId==='forjar-armadura'?0:1,anchor=head?.querySelectorAll('.patron-power')?.[index]||head?.querySelector('.patron-card');if(!anchor)return;
 const rect=anchor.getBoundingClientRect(),x=rect.left+rect.width/2,y=rect.top+rect.height/2,layer=document.createElement('div');layer.className='forge-impact-layer';document.body.append(layer);
 const hammer=document.createElement('div');hammer.className='forge-hammer';hammer.style.left=(x-120)+'px';hammer.style.top=(y-70)+'px';hammer.style.opacity='0';
 hammer.innerHTML='<svg viewBox="0 0 240 300" aria-hidden="true"><defs><linearGradient id="forge-gold-head" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#fff8b6"/><stop offset=".2" stop-color="#ffe766"/><stop offset=".45" stop-color="#a65a17"/><stop offset=".7" stop-color="#ffc248"/><stop offset="1" stop-color="#fff3a0"/></linearGradient><linearGradient id="forge-handle" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#553016"/><stop offset=".4" stop-color="#ddb05b"/><stop offset=".6" stop-color="#f8d877"/><stop offset="1" stop-color="#7d461a"/></linearGradient></defs><path d="M106 88 L135 88 L132 267 Q119 290 105 265 Z" fill="url(#forge-handle)" stroke="#6a3815" stroke-width="4"/><path d="M106 183 L134 183 M106 202 L133 202 M107 221 L132 221 M108 240 L131 240" stroke="#55331a" stroke-width="6"/><path d="M43 39 L62 21 L175 24 L199 42 L197 91 L177 106 L59 104 L40 86 Z" fill="url(#forge-gold-head)" stroke="#9a5d22" stroke-width="5"/><path d="M52 38 L173 34 L187 44 L63 47 Z" fill="#fffad0"/><path d="M44 46 L67 48 L64 96 L46 86 Z M171 48 L193 44 L191 88 L174 99 Z" fill="#ffc744" stroke="#fff0a5" stroke-width="2"/><path d="M80 49 L156 47 L155 92 L78 91 Z" fill="#9b5319" stroke="#fff094" stroke-width="3"/><path d="M98 76 C91 61 106 52 124 59 C140 65 133 84 120 83 C108 83 110 68 120 71" fill="none" stroke="#ffed88" stroke-width="6" stroke-linecap="round"/><circle cx="72" cy="42" r="3" fill="#fff3ab"/><circle cx="167" cy="96" r="3" fill="#fff3ab"/></svg>';
 layer.append(hammer);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const animation=hammer.animate(reduced?[{opacity:0},{opacity:1,offset:.4},{opacity:0}]:[{transform:'translateY(-20px) rotate(-58deg) scale(.6)',opacity:0},{transform:'translateY(-20px) rotate(-42deg) scale(1)',opacity:1,offset:.28,easing:'cubic-bezier(.65,0,1,.4)'},{transform:'translateY(0) rotate(0deg) scale(1)',opacity:1,offset:.48},{transform:'translateY(-24px) rotate(-18deg) scale(1)',opacity:1,offset:.64},{transform:'translateY(-7px) rotate(-6deg) scale(.95)',opacity:.8,offset:.78},{transform:'translateY(-30px) rotate(-10deg) scale(.6)',opacity:0}],{duration:reduced?500:1400,easing:'linear',fill:'forwards'});
 animationCue(animation,.48,()=>{
  if(typeof RunaDamageFX!=='undefined')RunaDamageFX.play({kind:'hammer',from:anchor,to:anchor,getGeneration:()=>visualGeneration});else forgeHammerSound();const flash=document.createElement('div');flash.className='forge-flash';flash.style.left=x+'px';flash.style.top=y+'px';layer.append(flash);flash.animate([{transform:'translate(-50%,-50%) scale(.2)',opacity:1},{transform:'translate(-50%,-50%) scale(2.5)',opacity:0}],{duration:450,easing:'ease-out',fill:'forwards'});
  for(let i=0;i<(reduced?5:36);i++){const spark=document.createElement('i');spark.className='forge-spark';spark.style.left=x+'px';spark.style.top=y+'px';const angle=Math.PI*2*i/36+(i%3)*.1,distance=65+(i%7)*28;layer.append(spark);spark.animate([{transform:'translate(-50%,-50%) rotate('+angle+'rad) scale(1.4)',opacity:1},{transform:'translate('+Math.cos(angle)*distance+'px,'+(Math.sin(angle)*distance+50)+'px) rotate('+angle+'rad) scale(.2)',opacity:0}],{duration:420+(i%5)*90,easing:'cubic-bezier(.15,.7,.4,1)',fill:'forwards'});}
  for(let i=0;i<2;i++){const ring=document.createElement('i');ring.className='forge-shock-ring';ring.style.left=x+'px';ring.style.top=y+'px';layer.append(ring);ring.animate([{transform:'translate(-50%,-50%) scale(.2)',opacity:.95},{transform:'translate(-50%,-50%) scale('+(i?4:2.5)+')',opacity:0}],{duration:600+i*160,delay:i*70,easing:'ease-out',fill:'forwards'});}
  if(!reduced)head.animate([{transform:'translate(0,0)'},{transform:'translate(-5px,3px)',offset:.2},{transform:'translate(4px,-2px)',offset:.4},{transform:'translate(-2px,1px)',offset:.65},{transform:'translate(0,0)'}],{duration:340});
 });
 try{await settleAnimation(animation,reduced?500:1400);hammer.remove();await pause(180);}finally{layer.remove();}
}
async function publicForgeHammer(event,powerId){const key=hammerKey(event.playerId,powerId);if(locallyHammeredPowers.delete(key))return;await playForgeHammer(event.playerId,powerId);}

function forgeHammerSound(){if(typeof RunaDamageFX!=='undefined'){RunaDamageFX.audio('hammer','impact',{x:innerWidth/2});return;}sound('impact',10);try{if(typeof audioContext==='undefined'||audioContext?.state!=='running')return;const now=audioContext.currentTime;for(const [frequency,volume,duration] of [[120,.11,.18],[540,.045,.6],[1320,.025,.46],[2470,.014,.32]]){const tone=audioContext.createOscillator(),gain=audioContext.createGain();tone.type='sine';tone.frequency.setValueAtTime(frequency,now);if(frequency===120)tone.frequency.exponentialRampToValueAtTime(48,now+.16);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(volume,now+.003);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);tone.connect(gain).connect(audioContext.destination);tone.start(now);tone.stop(now+duration+.03);}}catch{}}
