/* Standalone visual preview. No account, pack issuance, rewards or game actions. */
(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const stage = $('pack-stage'), canvas = $('pack-fx'), ctx = canvas.getContext('2d');
  const pack = new Image(), back = new Image();
  const colors = {lacaio:'#d29b66',padrao:'#c1d9e5',elite:'#ffca53',soberano:'#c1b2ff'};
  const rarityNames = {lacaio:'Bronze',padrao:'Prata',elite:'Ouro',soberano:'Platina'};
  const clamp = (n,a=0,b=1) => Math.max(a,Math.min(b,n));
  const ease = t => 1-Math.pow(1-clamp(t),3);
  const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
  let width=1,height=1,phase='loading',time=0,last=0,speed=1,ready=false,revealed=0,frame=0,bursted=false;
  let pieces=[],particles=[],ripples=[],scheduled=[],models=[],cardNodes=[];
  let audio=null,master=null,muted=false,voices=[],drag=null,packOffset={x:0,y:0};
  const imageReady = (img,src) => new Promise((resolve,reject)=>{img.onload=()=>resolve(img);img.onerror=()=>reject(Error('Não foi possível carregar '+src));img.src=src;});
  function caption(step,message){$('pack-step').textContent=step;$('pack-status').textContent=message;}
  function layout(){const rect=stage.getBoundingClientRect();width=rect.width;height=rect.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);const g=geometry();$('pack-hit').style.width=g.w+'px';$('pack-hit').style.height=g.h+'px';}
  const geometry = () => {const h=Math.min(height*.59,510),w=h*870/1355;return {x:width/2+packOffset.x,y:height*.46+packOffset.y,w,h};};
  function controls(){const busy=phase==='opening';$('open-pack').disabled=!ready||phase!=='ready';$('pack-hit').disabled=!ready||phase!=='ready';$('pack-hit').hidden=phase!=='ready';$('reset-pack').disabled=!ready;$('pack-speed').disabled=busy;$('reveal-all').hidden=!['cards','complete'].includes(phase);$('reveal-all').disabled=revealed===4;}
  function loadSound(){if(!audio){const Context=window.AudioContext||window.webkitAudioContext;if(!Context)return;audio=new Context();master=audio.createGain();master.gain.value=muted?0:Number($('pack-volume').value)/100;master.connect(audio.destination);}if(audio.state==='suspended')audio.resume().catch(()=>{});}
  function tone(freq,duration,gain=.1,type='sine',delay=0,end=freq){if(!audio)return;const osc=audio.createOscillator(),env=audio.createGain(),at=audio.currentTime+delay;osc.type=type;osc.frequency.setValueAtTime(freq,at);osc.frequency.exponentialRampToValueAtTime(Math.max(12,end),at+duration);env.gain.setValueAtTime(.0001,at);env.gain.exponentialRampToValueAtTime(gain,at+.012);env.gain.exponentialRampToValueAtTime(.0001,at+duration);osc.connect(env);env.connect(master);osc.start(at);osc.stop(at+duration+.03);voices.push(osc);osc.onended=()=>{osc.disconnect();env.disconnect();voices=voices.filter(v=>v!==osc);};}
  function noise(duration,gain=.15,filterType='lowpass',frequency=1800,delay=0){if(!audio)return;const n=Math.ceil(duration*audio.sampleRate),buffer=audio.createBuffer(1,n,audio.sampleRate),data=buffer.getChannelData(0);let brown=0;for(let i=0;i<n;i++){brown=(brown+(Math.random()*2-1)*.08)/1.02;data[i]=brown*2.5;}const source=audio.createBufferSource(),filter=audio.createBiquadFilter(),env=audio.createGain(),at=audio.currentTime+delay;source.buffer=buffer;filter.type=filterType;filter.frequency.setValueAtTime(frequency,at);filter.frequency.exponentialRampToValueAtTime(Math.max(80,frequency*.12),at+duration);env.gain.setValueAtTime(.0001,at);env.gain.exponentialRampToValueAtTime(gain,at+.008);env.gain.exponentialRampToValueAtTime(.0001,at+duration);source.connect(filter);filter.connect(env);env.connect(master);source.start(at);voices.push(source);source.onended=()=>{source.disconnect();filter.disconnect();env.disconnect();voices=voices.filter(v=>v!==source);};}
  function stopSound(){for(const v of [...voices]){try{v.stop();}catch{}}voices=[];}
  function sound(kind,rarity='lacaio'){
    if(!audio||muted)return;
    if(kind==='charge'){tone(90,1.05,.13,'sine',0,310);tone(182,1.2,.035,'triangle',0,490);noise(.85,.12,'bandpass',850);}
    if(kind==='clasp'){[540,870,1430,2060].forEach((f,i)=>tone(f,.22+i*.055,.12/(i+1),'sine',0,f*.87));noise(.16,.15,'highpass',3100);}
    if(kind==='burst'){noise(1.05,.7,'lowpass',3600);noise(.22,.5,'highpass',5200);tone(125,.75,.36,'sine',0,24);tone(69,1.2,.2,'triangle',.025,30);[440,659,880,1175,1760].forEach((f,i)=>tone(f,1.35+i*.12,.09,'sine',.06+i*.035,f*.99));}
    if(kind==='land'){noise(.15,.07,'lowpass',550);tone(130,.17,.045,'sine',0,70);}
    if(kind==='reveal'){const n={lacaio:0,padrao:2,elite:4,soberano:7}[rarity]||0;[1,1.25,1.5,2].forEach((m,i)=>tone(330*Math.pow(2,n/12)*m,.65+i*.16,.08/(1+i*.25),'sine',i*.045));noise(.3,.085,'bandpass',rarity==='soberano'?3500:2000);}
  }
  function later(fn,delay){scheduled.push({at:time+delay,fn});}
  function outlinePath(g){ctx.beginPath();ctx.moveTo(g.x-g.w/2+4,g.y-g.h/2);ctx.lineTo(g.x+g.w/2-4,g.y-g.h/2);ctx.quadraticCurveTo(g.x+g.w/2,g.y-g.h/2,g.x+g.w/2,g.y-g.h/2+4);ctx.lineTo(g.x+g.w/2,g.y+g.h/2-4);ctx.quadraticCurveTo(g.x+g.w/2,g.y+g.h/2,g.x+g.w/2-4,g.y+g.h/2);ctx.lineTo(g.x-g.w/2+4,g.y+g.h/2);ctx.quadraticCurveTo(g.x-g.w/2,g.y+g.h/2,g.x-g.w/2,g.y+g.h/2-4);ctx.lineTo(g.x-g.w/2,g.y-g.h/2+4);ctx.quadraticCurveTo(g.x-g.w/2,g.y-g.h/2,g.x-g.w/2+4,g.y-g.h/2);ctx.closePath();}
  function drawPack(g,scale=1,rotation=0,alpha=1,polygon=null){ctx.save();ctx.globalAlpha=alpha;ctx.translate(g.x,g.y);ctx.rotate(rotation);ctx.scale(scale,scale);if(polygon){ctx.beginPath();polygon.forEach(([x,y],i)=>ctx[i?'lineTo':'moveTo']((x-.5)*g.w,(y-.5)*g.h));ctx.closePath();ctx.clip();}else{outlinePath({x:0,y:0,w:g.w,h:g.h});ctx.clip();}ctx.drawImage(pack,75,74,870,1355,-g.w/2,-g.h/2,g.w,g.h);ctx.restore();}
  function glow(x,y,r,color,alpha=1){ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=alpha;const grad=ctx.createRadialGradient(x,y,0,x,y,r);grad.addColorStop(0,color);grad.addColorStop(.16,color);grad.addColorStop(1,'#0000');ctx.fillStyle=grad;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.restore();}
  function rune(g,intensity){ctx.save();ctx.translate(g.x,g.y+g.h*.013);ctx.scale(g.w/290,g.h/450);ctx.strokeStyle='#fff1b5';ctx.shadowColor='#ffb536';ctx.shadowBlur=22*intensity;ctx.globalAlpha=intensity;ctx.lineWidth=1.3;ctx.beginPath();ctx.ellipse(0,0,93,93,0,0,Math.PI*2);ctx.moveTo(0,-112);ctx.bezierCurveTo(-13,-25,-43,-21,-98,0);ctx.bezierCurveTo(-43,21,-13,25,0,112);ctx.bezierCurveTo(13,25,43,21,98,0);ctx.bezierCurveTo(43,-21,13,-25,0,-112);ctx.stroke();ctx.restore();}
  function looseClasp(g,t){ctx.save();ctx.translate(g.x+ease(t)*g.w*.25,g.y+g.h*.01-ease(t)*g.h*.08);ctx.rotate(t*.28);const scale=1+ease(t)*.85;ctx.scale(scale,scale);ctx.globalAlpha=1-clamp((t-.72)/.28);ctx.shadowColor='#ffbc4e';ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(-g.w*.21,0);ctx.bezierCurveTo(-g.w*.1,-g.h*.075,g.w*.1,-g.h*.075,g.w*.21,0);ctx.bezierCurveTo(g.w*.1,g.h*.075,-g.w*.1,g.h*.075,-g.w*.21,0);ctx.clip();ctx.drawImage(pack,75,74,870,1355,-g.w/2,-g.h*.51,g.w,g.h);ctx.restore();}
  function sparks(x,y,count,color='#ffcf70',radius=1){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,v=(100+Math.random()*450)*radius;particles.push({x,y,px:x,py:y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:1.1+Math.random()*1.2,age:0,size:1+Math.random()*2.8,color,gravity:60+Math.random()*120});}}
  function makePieces(){
    const g=geometry(),xs=[0,.23,.5,.77,1],ys=[0,.25,.47,.59,.8,1];pieces=[];
    const points=ys.map((v,y)=>xs.map((u,x)=>[u+(x>0&&x<4?(Math.random()-.5)*.09:0),v+(y>0&&y<5?(Math.random()-.5)*.06:0)]));
    const edge=(a,b)=>{const dx=b[0]-a[0],dy=b[1]-a[1],length=Math.hypot(dx,dy),j=(Math.random()-.5)*.017;return [a,[a[0]+dx*.33-dy/length*j,a[1]+dy*.33+dx/length*j],[a[0]+dx*.66+dy/length*j,a[1]+dy*.66-dx/length*j],b];};
    const horizontal=points.map(row=>row.slice(0,-1).map((p,x)=>edge(p,row[x+1])));
    const vertical=points.slice(0,-1).map((row,y)=>row.map((p,x)=>edge(p,points[y+1][x])));
    for(let y=0;y<5;y++)for(let x=0;x<4;x++){
      const polygon=[...horizontal[y][x],...vertical[y][x+1].slice(1),...horizontal[y+1][x].toReversed().slice(1),...vertical[y][x].toReversed().slice(1)];
      const cx=(xs[x]+xs[x+1])/2,cy=(ys[y]+ys[y+1])/2,angle=Math.atan2((cy-.51)*1.6,cx-.5),push=160+Math.random()*270;
      pieces.push({polygon,cx,cy,vx:Math.cos(angle)*push,vy:Math.sin(angle)*push-60,rotation:(Math.random()-.5)*2.8,delay:Math.random()*.06,g});
    }
    sparks(g.x,g.y+g.h*.01,reduced?45:180);ripples.push({x:g.x,y:g.y,age:0,life:1.1,r:0,color:'#ffe4a0'});sound('burst');
  }
  function opening(now,dt){time+=dt*speed;const g=geometry();const charge=clamp(time/1.12);
    if(time<1.35){const shake=time>0.65&&!reduced?(time-.65)*4:0;g.x+=Math.sin(time*87)*shake;g.y+=Math.cos(time*69)*shake*.5;glow(g.x,g.y+g.h*.015,g.w*(.75+charge*.3),'#ca721e',charge*.38);drawPack(g,1+charge*.04,Math.sin(time*10)*charge*.003);rune(g,charge*(.65+Math.sin(time*14)*.12));if(time>.45&&Math.random()<.6&&!reduced)particles.push({x:g.x+(Math.random()-.5)*g.w,px:g.x,py:g.y,y:g.y+g.h*.12,vx:(Math.random()-.5)*18,vy:-70-Math.random()*65,life:.5,age:0,size:1.2,color:'#ffe8af',gravity:0});}
    if(time>=1.04&&time<1.35){if(!bursted){sound('clasp');bursted=true;caption('LEVE O SELO AO LIMITE','O fecho se rompe…');}glow(g.x,g.y+g.h*.018,g.w*.55,'#fff4c5',clamp((time-1.04)*3));looseClasp(g,(time-1.04)/.31);}
    if(time>=1.35){if(!pieces.length){makePieces();caption('O SEGREDO FOI LIBERADO','Quatro cartas despertam.');}const burst=time-1.35;for(const p of pieces){const t=Math.max(0,burst-p.delay),a=clamp(1-(t-.15)/1.2);if(!a)continue;const gg={...p.g,x:p.g.x+p.vx*t,y:p.g.y+p.vy*t+80*t*t};drawPack(gg,Math.max(.25,1-t*.38),p.rotation*t,a,p.polygon);}const flash=clamp(1-burst/.35);if(flash){ctx.fillStyle='rgba(255,227,171,'+flash*.22+')';ctx.fillRect(0,0,width,height);glow(g.x,g.y,g.w*(1+burst*4),'#fff6ce',flash*.9);}if(burst>.22&&cardNodes[0].hidden)launchCards();if(time>=3.35){phase='cards';pieces=[];controls();caption('QUATRO CARTAS · QUATRO DESCOBERTAS','Clique nas cartas para revelar.');}}
    const tasks=scheduled.filter(t=>t.at<=time);scheduled=scheduled.filter(t=>t.at>time);for(const task of tasks)task.fn();
  }
  function drawParticles(dt){ctx.save();ctx.globalCompositeOperation='screen';for(const p of particles){p.age+=dt;p.px=p.x;p.py=p.y;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=p.gravity*dt;ctx.globalAlpha=clamp(1-p.age/p.life);ctx.strokeStyle=p.color;ctx.lineWidth=p.size;ctx.beginPath();ctx.moveTo(p.px-p.vx*.014,p.py-p.vy*.014);ctx.lineTo(p.x,p.y);ctx.stroke();}particles=particles.filter(p=>p.age<p.life);for(const r of ripples){r.age+=dt;const p=clamp(r.age/r.life);ctx.globalAlpha=(1-p)*.85;ctx.strokeStyle=r.color;ctx.lineWidth=2+6*(1-p);ctx.shadowColor=r.color;ctx.shadowBlur=18;ctx.beginPath();ctx.ellipse(r.x,r.y,20+p*width*.48,15+p*height*.36,0,0,Math.PI*2);ctx.stroke();}ripples=ripples.filter(r=>r.age<r.life);ctx.restore();}
  function tick(now){const dt=Math.min((now-(last||now))/1000,.04);last=now;ctx.clearRect(0,0,width,height);if(phase==='ready'){const g=geometry();g.y+=reduced?0:Math.sin(now/1300)*3;ctx.save();ctx.shadowColor='#000b';ctx.shadowBlur=35;ctx.shadowOffsetY=15;drawPack(g);ctx.restore();glow(g.x,g.y+g.h*.05,g.w*.7,'#ac6a22',.055+.025*Math.sin(now/1000));}if(phase==='opening')opening(now,dt);drawParticles(dt*(phase==='opening'?speed:1));frame=requestAnimationFrame(tick);}
  function launchCards(){const g=geometry();$('pack-cards').hidden=false;cardNodes.forEach(n=>n.hidden=false);for(let i=0;i<cardNodes.length;i++){const node=cardNodes[i];const r=node.getBoundingClientRect();const fromX=g.x-(r.left-stage.getBoundingClientRect().left+r.width/2),fromY=g.y-(r.top-stage.getBoundingClientRect().top+r.height/2);node.animate([{opacity:0,transform:`translate(${fromX}px,${fromY}px) scale(.25) rotate(${(i-1.5)*17}deg)`},{opacity:1,transform:`translate(${fromX*.25}px,-65px) scale(1.06) rotate(${(i-1.5)*4}deg)`,offset:.55},{opacity:1,transform:'translate(0,0) scale(1) rotate(0deg)'}],{duration:(reduced?550:1400)/speed,delay:i*105/speed,easing:'cubic-bezier(.16,.8,.25,1)',fill:'backwards'});later(()=>sound('land'),1.15+i*.105);}}
  function open(){if(phase!=='ready'||!ready)return;loadSound();time=0;phase='opening';bursted=false;pieces=[];speed=Number($('pack-speed').value);controls();caption('LEVE O SELO AO LIMITE','A runa acumula energia…');sound('charge');}
  function reset(){stopSound();scheduled=[];time=0;revealed=0;bursted=false;pieces=[];particles=[];ripples=[];packOffset={x:0,y:0};drag=null;for(const n of cardNodes){n.getAnimations({subtree:true}).forEach(a=>a.cancel());n.classList.remove('revealed','revealing');n.hidden=true;n.disabled=false;n.setAttribute('aria-pressed','false');n.setAttribute('aria-label','Revelar carta '+(cardNodes.indexOf(n)+1));}phase='ready';$('pack-cards').hidden=true;controls();caption('QUATRO CARTAS SOB O SELO','Clique no pacote ou arraste-o até o centro.');}
  function reveal(index){if(!['cards','complete'].includes(phase))return;const node=cardNodes[index],model=models[index];if(node.classList.contains('revealed'))return zoom(index);loadSound();node.classList.add('revealed','revealing');node.setAttribute('aria-label',model.name+' · ampliar carta');node.setAttribute('aria-pressed','true');revealed++;const rect=node.getBoundingClientRect(),sr=stage.getBoundingClientRect();sparks(rect.left-sr.left+rect.width/2,rect.top-sr.top+rect.height/2,reduced?12:60,colors[model.rarity],.6);sound('reveal',model.rarity);node.animate([{transform:'translateY(0) scale(1)'},{transform:'translateY(-15px) scale(1.07)',offset:.45},{transform:'translateY(0) scale(1)'}],{duration:850,easing:'ease-out'});setTimeout(()=>node.classList.remove('revealing'),900);caption(rarityNames[model.rarity].toUpperCase(),model.name);if(revealed===4){phase='complete';controls();caption('PACOTE REVELADO','Clique em uma carta para ampliar ou repita a abertura.');}}
  function zoom(i){const out=$('zoom-card');out.getContext('2d').clearRect(0,0,out.width,out.height);out.getContext('2d').drawImage(cardNodes[i].querySelector('canvas'),0,0,out.width,out.height);$('pack-zoom').showModal();}
  async function makeCard(model,index){const node=document.createElement('button');node.type='button';node.className='pack-card';node.dataset.rarity=model.rarity;node.setAttribute('aria-label','Revelar carta '+(index+1));node.hidden=true;node.innerHTML='<span class="pack-card-aura" aria-hidden="true"></span><span class="pack-card-inner"><span class="pack-card-side pack-card-back"><img src="card-back.png" alt=""></span><span class="pack-card-side pack-card-front"><canvas width="1350" height="1890"></canvas></span></span><span class="pack-card-label"></span>';
    node.querySelector('.pack-card-label').textContent=rarityNames[model.rarity];node.onclick=()=>reveal(index);$('pack-cards').append(node);cardNodes.push(node);
    await RunaCardVisual.drawCard(node.querySelector('canvas'),{name:model.name,kind:model.type==='creature'?'creature':'spell',rarity:model.rarity,themeEnergy:model.affinity,art:model.image,artY:model.artY??0,artZoom:model.artZoom||100,rules:model.text,subtype:model.subtype||'',generic:model.cost,power:model.attack,health:model.health},{assets:'criador/'});
  }
  $('open-pack').onclick=open;$('reset-pack').onclick=reset;$('pack-hit').onclick=()=>{if(!drag||!drag.moved)open();};$('reveal-all').onclick=()=>{cardNodes.forEach((n,i)=>{if(!n.classList.contains('revealed'))reveal(i);});};$('pack-sound').onclick=()=>{muted=!muted;$('pack-sound').textContent=muted?'Som desligado':'Som ligado';$('pack-sound').setAttribute('aria-pressed',String(!muted));if(master)master.gain.setTargetAtTime(muted?0:Number($('pack-volume').value)/100,audio.currentTime,.03);};$('pack-volume').oninput=()=>{if(master)master.gain.setTargetAtTime(muted?0:Number($('pack-volume').value)/100,audio.currentTime,.03);};$('close-zoom').onclick=()=>$('pack-zoom').close();$('pack-zoom').onclick=e=>{if(e.target===$('pack-zoom'))$('pack-zoom').close();};
  $('pack-hit').addEventListener('pointerdown',e=>{if(phase!=='ready')return;drag={x:e.clientX,y:e.clientY,moved:false};e.currentTarget.setPointerCapture(e.pointerId);});$('pack-hit').addEventListener('pointermove',e=>{if(!drag||phase!=='ready')return;const x=e.clientX-drag.x,y=e.clientY-drag.y;drag.moved||=Math.hypot(x,y)>7;if(drag.moved){packOffset={x:clamp(x,-width*.3,width*.3),y:clamp(y,-height*.25,height*.25)};}});$('pack-hit').addEventListener('pointerup',()=>{if(!drag)return;const moved=drag.moved;drag=null;packOffset={x:0,y:0};if(moved)open();});$('pack-hit').addEventListener('pointercancel',()=>{drag=null;packOffset={x:0,y:0};});
  new ResizeObserver(layout).observe(stage);layout();frame=requestAnimationFrame(tick);
  window.addEventListener('pagehide',()=>{cancelAnimationFrame(frame);stopSound();audio?.close();});
  (async()=>{try{const [,,catalogue]=await Promise.all([imageReady(pack,'pack-preview.png'),imageReady(back,'card-back.png'),fetch('cartas.json').then(r=>{if(!r.ok)throw Error('Catálogo indisponível.');return r.json();})]);const all=catalogue.decks.flatMap(d=>d.cards);models=['RG02','FL05','FL04','RG04'].map(id=>all.find(c=>c.id===id));if(models.some(m=>!m))throw Error('Carta de demonstração não encontrada.');for(let i=0;i<models.length;i++)await makeCard(models[i],i);ready=true;reset();}catch(e){phase='error';caption('NÃO FOI POSSÍVEL PREPARAR A PRÉVIA',e.message);}})();
})();
