import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {act,join,makeRoom,view} from './game.mjs';
const catalog=JSON.parse(await readFile(path.join(path.dirname(fileURLToPath(import.meta.url)),'cartas.json'),'utf8'));
const room=makeRoom('ABC123','Van');const a=room.players[0],b=join(room,'Vitu');
const early=makeRoom('DEF456','Primeira');act(early,early.players[0],{type:'deck',deckId:'ruptura-cacada'},catalog);const late=join(early,'Segunda');assert.equal(late.deckId,null,'quem entra depois escolhe o próprio deck');
act(room,a,{type:'deck',deckId:'ruptura-cacada',art:{R01:{image:'data:image/png;base64,iVBORw0KGgo=',kind:'card'}}},catalog);act(room,b,{type:'deck',deckId:'fluxo-selos'},catalog);
assert.equal(room.phase,'coin');act(room,room.players.find(p=>p.id===room.coinWinner),{type:'first',playerId:a.id},catalog);
assert.equal(room.phase,'mulligan');assert.equal(a.hand.length,5);assert.equal(b.hand.length,5);act(room,a,{type:'confirmMulligan'},catalog);act(room,b,{type:'confirmMulligan'},catalog);assert.equal(a.hand.length,6);assert.equal(a.manaMax,1);
assert.equal(a.patron.maxHp,20);assert.equal(b.patron.hp,20);
assert.equal([...a.hand,...a.deck].find(c=>c.modelId==='R01').imageKind,'card','arte completa mantém seu modo de exibição');
const model=id=>catalog.decks.flatMap(d=>d.cards).find(c=>c.id===id);
const instance=(id,owner)=>({...structuredClone(model(id)),uid:`${id}-${Math.random()}`,modelId:id,owner:owner.id,damage:0,attackMod:0});
const emanA=instance('R05',a),emanB=instance('R05',a);a.hand.push(emanA,emanB);a.mana=10;
act(room,a,{type:'play',cardId:emanA.uid,mode:'emanate'},catalog);act(room,a,{type:'play',cardId:emanB.uid,mode:'emanate'},catalog);
assert.equal(a.emanation.length,2);assert.equal(a.mana,6,'da mão para Emanação cobra só o custo impresso');
act(room,a,{type:'emanate',cardId:emanA.uid},catalog);assert.equal(a.mana,5);assert.equal(a.emanation.length,1);
act(room,a,{type:'emanate',cardId:emanA.uid},catalog);assert.equal(a.mana,4);assert.equal(a.emanation.length,2);
a.emanation=[];a.reserve=[];
const hunter=instance('R01',a),trap=instance('R11',a),buff=instance('R09',a),apprentice=instance('M01',b);
a.reserve=[hunter];a.hand.push(trap,buff);a.mana=10;
act(room,a,{type:'play',cardId:trap.uid,mode:'lane',lane:0},catalog);
assert.equal(view(room,b).players.find(p=>p.id===b.id).prepared[0].card,null,'armadilha inimiga fica oculta');
act(room,a,{type:'play',cardId:buff.uid,mode:'lane',lane:0},catalog);
assert.equal(view(room,b).players.find(p=>p.id===a.id).prepared[0].card.name,buff.name,'magia aliada fica aberta');
act(room,a,{type:'endPrep'},catalog);assert.equal(room.turn,b.id);assert.equal(room.phase,'prep','a decisão só aparece após as duas preparações');assert.equal(room.preparationsDone,1);assert.throws(()=>act(room,a,{type:'vote',fight:true},catalog),/Aguarde sua preparação|Ação indisponível|fora de fase/);assert.equal(b.manaMax,1);
const axiomA=instance('M04',b),axiomB=instance('M04',b),consult=instance('M08',b);b.hand.push(axiomA,axiomB,consult);b.mana=10;
act(room,b,{type:'play',cardId:axiomA.uid,mode:'emanate'},catalog);act(room,b,{type:'play',cardId:axiomB.uid,mode:'emanate'},catalog);
act(room,b,{type:'play',cardId:consult.uid,mode:'direct'},catalog);assert.equal(b.mana,3,'dois Axiom reduzem a primeira magia direta de 3 para 1');
b.emanation=[];b.reserve=[];
b.reserve=[apprentice];act(room,b,{type:'endPrep'},catalog);assert.equal(room.phase,'vote');assert.equal(room.preparationsDone,2);
act(room,a,{type:'vote',fight:true},catalog);assert.equal(room.phase,'formation','um sim inicia imediatamente o combate');
assert.throws(()=>act(room,b,{type:'vote',fight:false},catalog),/indisponível na formação/);
act(room,a,{type:'assign',lane:0,cardId:hunter.uid},catalog);assert.equal(view(room,b).players.find(p=>p.id===a.id).formation[0],null,'formação rival fica secreta');
act(room,a,{type:'assign',lane:0,cardId:null},catalog);assert.equal(a.formation[0],null,'arrastar de volta à reserva libera a posição');
act(room,a,{type:'assign',lane:0,cardId:hunter.uid},catalog);
act(room,b,{type:'assign',lane:0,cardId:apprentice.uid},catalog);
act(room,a,{type:'ready'},catalog);act(room,b,{type:'ready'},catalog);
assert.equal(room.phase,'resolving');assert.equal(view(room,b).players.find(p=>p.id===a.id).formation[0],hunter.uid,'cartas são reveladas na animação');
await new Promise(resolve=>setTimeout(resolve,room.combat.duration+80));
assert.equal(b.patron.hp,16,'armadilha derrota defensor, bônus aliado eleva ataque de 2 a 4');
assert.equal(room.round,2);assert.equal(room.phase,'prep');assert.equal(a.reserve.length,1);assert.equal(b.reserve.length,0);
assert.equal(room.preparationsDone,0,'a rodada seguinte exige novamente ambas as preparações');
assert.ok(room.log.length<=10,'registro guarda no máximo dez atualizações');
assert.ok(room.log.every(entry=>Number.isInteger(entry.round)&&typeof entry.message==='string'),'registro preserva rodada e mensagem para agrupar turnos');
assert.equal(a.discard.some(c=>c.uid===trap.uid),true);assert.equal(a.discard.some(c=>c.uid===buff.uid),true);
console.log('OK: abertura, mana, sigilo, duas magias posicionadas, três fases e dano ao Patrono.');
